### ISSUE TITLE
pca: rms fitting to a reference frame

### ISSUE THREAD

**Issue by Balasubra** [Amber-MD/pytraj#1112]
I have started with a X-ray structure of an enzyme and performed md simulation in both apo and holo states. I want to perform pca first by superimposing the backbone to the X-ray structure. The documentation of pytraj-pca says that fitting is done with respect to first frame. 

Would nt be a useful if a parameter to supply user intended structure for rmsfit is added ?

pca(traj, mask, n_vecs=2, dtype='ndarray', top=None)
    perform PCA analysis by following below steps:
    
    - perform rmsfit to first frame with ``mask``
    - compute average frame with ``mask``
    - rmsfit to average frame with ``mask``
    - compute covariance matrix
    - diagonalize the matrix to get eigenvectors and eigenvalues
    - perform projection of each frame with mask to each eigenvector

**Comment by hainm** [comment]
so how's about this proposed syntax.

```python
pca(traj, mask, n_vecs=2, dtype='ndarray', top=None, ref=None)
```
if ref is not None then rmsfit to this ref else fit to 1st frame.

Here I am assuming that user should use the same mask for fitting and for structure averaging.

@drroe  @swails do you have any comment about above case? (I myself not use PCA so I am not clear if it's right thing to do).

**Comment by drroe** [comment]
> Here I am assuming that user should use the same mask for fitting and for structure averaging.

But if the user supplies a reference structure why would you need to do structure averaging? Maybe I'm just not understanding how the `pca()` function works under the hood.

**Comment by hainm** [comment]
Here is pcs code
```python
0, mask=mask)
    avg = mean_structure(traj)
    traj.superpose(ref=avg, mask=mask)
    avg2 = mean_structure(traj, mask=mask)

    mat = matrix.covar(traj, mask)
    if n_vecs < 0:
        n_vecs = mat.shape[0]
    else:
        n_vecs = n_vecs

    eigenvalues, eigenvectors = matrix.diagonalize(mat, n_vecs=n_vecs, dtype='tuple')
    projection_data = _projection(traj, mask=mask, average_coords=avg2.xyz,
                                  eigenvalues=eigenvalues,
                                  eigenvectors=eigenvectors,
                                  scalar_type='covar', dtype=dtype)
    return projection_data, (eigenvalues, eigenvectors)
```

I am using phone so it is hard to type with detail.

**Comment by hainm** [comment]
** updated ** deleted my comment and will reply later

**Comment by hainm** [comment]
@drroe 

I wrote the `pca(...)` method to simplify the workflow in cpptraj. This `pca` follow protocol that is suggested in amber list and in amber15 manual.

Reasons
- for most of users, they just need pca output without much work. (similaridea to http://thegrantlab.org/bio3d/html/pca.html)
- follow suggestions in amber mail list (mostly from yours :D)

Here is the `pca` code in pytraj

```python

    traj.superpose(ref=0, mask=mask)
    avg = mean_structure(traj)
    traj.superpose(ref=avg, mask=mask)
    avg2 = mean_structure(traj, mask=mask)

    mat = matrix.covar(traj, mask)
    if n_vecs < 0:
        n_vecs = mat.shape[0]
    else:
        n_vecs = n_vecs

    eigenvalues, eigenvectors = matrix.diagonalize(mat, n_vecs=n_vecs, dtype='tuple')
    projection_data = _projection(traj, mask=mask, average_coords=avg2.xyz,
                                  eigenvalues=eigenvalues,
                                  eigenvectors=eigenvectors,
                                  scalar_type='covar', dtype=dtype)
    return projection_data, (eigenvalues, eigenvectors)
```

This code
```python
        mask = '!@H='
        data = pt.pca(traj, mask, n_vecs=2, ref=0)
```
reproduces output from cpptraj with following input

```bash
# Step one. Generate average structure.
# RMS-Fit to first frame to remove global translation/rotation.
parm data/tz2.parm7
trajin data/tz2.nc
rms first !@H=
average crdset AVG
run
# Step two. RMS-Fit to average structure. Calculate covariance matrix.
# Save the fit coordinates.
rms ref AVG !@H=
matrix covar name MyMatrix !@H=
createcrd CRD1
run
# Step three. Diagonalize matrix.
runanalysis diagmatrix MyMatrix vecs 2 name MyEvecs
# Step four. Project saved fit coordinates along eigenvectors 1 and 2
crdaction CRD1 projection evecs MyEvecs !@H= out project.dat beg 1 end 2
```

**Comment by hainm** [comment]
so, what is your suggestion about updating `pca` code in pytraj?

(Those are several links about pca with cpptraj that I read
-  http://www.amber.utah.edu/AMBER-workshop/London-2015/pca/
- http://archive.ambermd.org/201404/0516.html
- http://archive.ambermd.org/201404/0243.html
- http://ambermd.org/doc12/Amber15.pdf (page 619 (29.14.2. Cartesian covariance matrix calculation and projection (PCA)))
)

**Comment by Balasubra** [comment]
I have just read the responses. It can be like as you have written in your first response,
I the user doesn’t give any reference structure, fit the frames to the user supplied structure. If the user doesn’t give reference structure, fit the frames to the average structure.

**Comment by hainm** [comment]
@Balasubra I just push new code. You can check it out and let me know if it works for you.

https://github.com/Amber-MD/pytraj/pull/1114/files

```python
traj = pt.load("data/tz2.nc", "data/tz2.parm7")
ref = pt.load('data/tz2.rst7', traj.top)
mask = '!@H='
pt.pca(traj, mask, n_vecs=2, ref=ref)
```

**Comment by drroe** [comment]
> so, what is your suggestion about updating pca code in pytraj?

Two things:
1) If the user provides their own reference structure, do not create an average structure (there is no point). Also, not fitting at all should be considered a legitimate option - you may want to include global rotational and translational motion in your eigenvectors.
2) You should be able to supply separate masks for fitting and creating the covariance matrix. It is common enough for example to only perform rms-fitting on heavy atoms while still wanting all atoms in eigenvectors.

**Comment by hainm** [comment]
thanks. I will work on each of your points.

**Comment by hainm** [comment]
@drroe 

done with https://github.com/Amber-MD/pytraj/pull/1115

can you have a brief look at test file here and let me know if it's good to merge after successful build? thanks. https://github.com/hainm/pytraj/blob/master/tests/test_pca.py

**Comment by Balasubra** [comment]
I have one issue with the else segment in the pca.  Here you pick the reference frame from the traj depending up on the frame number issued by the user.
else:
    ref = get_reference(traj, ref)
    traj.superpose(ref=ref, mask=mask)

If the use provides a reference structure, instead of a frame number, will it work ?. Because in the else segment, you obtain the reference structure from the traj. An example code is below,

traj=pt.load('../mytraj.dcd' , '../mytraj.prmtop' )
refstr = pt.load('../myref.pdb')
data = pt.pca( traj , mask=':1-427@CA,C,N' ,  ref=refstr  ,  n_vecs=3)

**Comment by hainm** [comment]
yes, if user give a reference (a Frame or a traj), pytraj will pick it.

check this code: https://github.com/Amber-MD/pytraj/blob/master/pytraj/get_common_objects.py#L131-L163

**Comment by hainm** [comment]
@Balasubra does the new code in `pytraj` works for your need. If so, can you close this issue.

Let us know if you have other suggestions.

 thanks.

**Comment by Balasubra** [comment]
I am sorry that i missed to update the test. Yes it works fine. Sincerely thank you for the support.

One general solution for actions commands i have is to introduce the 'slice feature for trajectory'. I also use mdanalysis for analysis and i find that feature a useful one.

**Comment by hainm** [comment]
What do you mean about slice?

**Comment by drroe** [comment]
It seems similar to the start stop and offset args you can specify to e.g.
trajin in cpptraj. The format is something like [start arg:stop arg:offset
arg] I think.

On Sunday, January 31, 2016, Hai Nguyen <notifications@github.com> wrote:

> What do you mean about slice?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Amber-MD/pytraj/issues/1112#issuecomment-177593954>.
>


-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by hainm** [comment]
If so, `pytraj` does support well

@Balasubra  you can check:

- http://amber-md.github.io/pytraj/latest/trajectory_slice.html
- http://amber-md.github.io/pytraj/latest/trajectory_exercise.html

**Comment by Balasubra** [comment]
So i can do like,  data = pt.pca( traj[1000:7000:10] , mask='@CA,C,N' ,  n_vecs=3)
thanks, i didnt realize it.

**Comment by hainm** [comment]
yes, you can do that for `pytraj.pca`.

In general you can use either

```python
pt.radgyr(traj[1000:7000:10])

# traj[1000:7000:10] is similar to slicing a Python list
```

or

```python
# use iterload for lazy loading
traj = pt.iterload(fn, tn)
pt.radgyr(traj(1000, 7000, 10))
# this does not apply for pytraj.pca
```
This is similiar to `range(1000, 7000, 10)` in python 3 (lazy evaluation): Only a single snapshot would be loaded to memory at a time. This is designed for streaming calculation, good for tens of GB or TB data.
