### ISSUE TITLE
Acceptor rather than aceptor

### ISSUE THREAD

**Issue by lambdalisue** [Amber-MD/pytraj#1159]
pytraj use a term 'aceptor' but it is a bit confusing. Is it possible to rename them to 'acceptor'?
http://amber-md.github.io/pytraj/latest/_api/pytraj.hbond_analysis.html

**Comment by hainm** [comment]
ack. my poor English. thanks. I will change it.

**Comment by lambdalisue** [comment]
Thanks :-)

**Comment by hainm** [comment]
fixed by https://github.com/Amber-MD/pytraj/pull/1160/files. Also the doc from your link is also corrected. thanks for the catch. cheers.

**Comment by lambdalisue** [comment]
;-)
