### ISSUE TITLE
Error in calculating distances after an atomicfluct  calculation

### ISSUE THREAD

**Issue by jdmadura** [Amber-MD/pytraj#1166]
When using the distance(traj,...) command after performing and rmsd(traj,...) calculation the distances are not calculated correctly.  If one re-reads the trajectory or performs the distance calculation first then the distances are calculated correctly.

**Comment by swails** [comment]
I suspect this is because the unit cell vectors are not rotated by the rmsd rotation matrix (which means the imaging is wrong).

**Comment by swails** [comment]
The fix here is not to use the unit cell parameters for any kind of imaging after rmsd is calculated (if the coordinates are fit to the reference)

**Comment by jdmadura** [comment]
Here are the requested files.  It appears that it is not the call to rmsd() but the call to calc_atomicfluct() that is the culprit. See the attached files.
[test.zip](https://github.com/Amber-MD/pytraj/files/168326/test.zip)

**Comment by hainm** [comment]
hi,

I confirm that this is because of `calc_atomicfluct` issue. For unknown reason, the coordinates of is mutated. 

```python
traj = pt.Trajectory('step4_equilibration.dcd', '../step3_pbcsetup.xplor.ext.psf')
print(traj.xyz[0, 3])
# got: [ 14.46718407  -5.56205606   2.54410934]
```

```python
traj = pt.Trajectory('step4_equilibration.dcd', '../step3_pbcsetup.xplor.ext.psf')
# add calc_atomicfluct
pt.calc_atomicfluct(traj, '@CA')
print(traj.xyz[0, 3])
# got [ 209.29941482   30.93646767    6.47249236]
```

I will fix it. thanks.

**Comment by hainm** [comment]
meanwhile you can use `iterload` method to create an immutable (on-disk) trajectory

```traj = pt.iterload(fn, tn)```

**Comment by hainm** [comment]
@drroe it's likely that DoAction in Action_AtomicFluct modified (or voided) coordinates of trajectory. But I can not find out why. Any idea why (the code in cpptraj is very clear but still need your advice).

We met a similar issue with memory before: https://github.com/Amber-MD/cpptraj/issues/172

**Comment by hainm** [comment]
adding `prinf` to debug in cpptraj

```c++
Action::RetType Action_AtomicFluct::DoAction(int frameNum, ActionFrame& frm) {
  if ( CheckFrameCounter( frm.TrajoutNum() ) ) return Action::OK;
  SumCoords_ += frm.Frm();
  printf("before 0: %f\n", frm.Frm().XYZ(0)[0]);
  SumCoords2_ += ( frm.Frm() * frm.Frm() );
  printf("after: %f\n", frm.Frm().XYZ(0)[0]);
...
}
```

output:
```bash
before 0: 15.554589
after: 241.945247
```

**Comment by jdmadura** [comment]
Thank-you for the suggested work around and attending to this so quickly.

**Comment by hainm** [comment]
@jdmadura no problem. 

@drroe found it, need to update operators (=*, *, ...) in Frame.

**Comment by drroe** [comment]
This simply should not happen. The frm.Frm() function is const. I cant look
into this right now but there must be something else going wrong. I can
look at it tomorrow.

On Thursday, March 10, 2016, Hai Nguyen <notifications@github.com> wrote:

> adding prinf to debug in cpptraj
>
> Action::RetType Action_AtomicFluct::DoAction(int frameNum, ActionFrame& frm) {
>   if ( CheckFrameCounter( frm.TrajoutNum() ) ) return Action::OK;
>   SumCoords_ += frm.Frm();
>   printf("before 0: %f\n", frm.Frm().XYZ(0)[0]);
>   SumCoords2_ += ( frm.Frm() * frm.Frm() );
>   printf("after: %f\n", frm.Frm().XYZ(0)[0]);
> ...
> }
>
> output:
>
> before 0: 15.554589
> after: 241.945247
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Amber-MD/pytraj/issues/1166#issuecomment-195165042>.
>


-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by hainm** [comment]
@drroe I just have a PR in cpptraj.

**Comment by hainm** [comment]
@jdmadura We have a fix in cpptraj, can you update cpptraj code and re-install libcpptraj and then run your notebook to validate. thanks for your report. cheers.

Below is the update guide (let us know if this does not work for you).
http://amber-md.github.io/pytraj/latest/installation.html#from-github

**Comment by drroe** [comment]
> We have a fix in cpptraj, 

Just to be clear, this is only an issue that would affect pytraj - if you ran with cpptraj only the bug does not present itself.
