### ISSUE TITLE
window

### ISSUE THREAD

**Issue by hainm** [Amber-MD/pytraj#1218]
do it, given that `pytraj` is used as one of the backends for [nglview](https://github.com/arose/nglview)

**Comment by hainm** [comment]
honesty it's freaking complicated.

**Comment by swails** [comment]
I am so confused...

**Comment by hainm** [comment]
@swails why are you confused?

**Comment by swails** [comment]
What was this issue even for? :)

**Comment by hainm** [comment]
oh, I just want to have pytraj works in Window. The motivation is to use pytraj as an backend for NGLView in Window. (visulization + simple analysis like angle, dihedral, ...).

However, I got trouble to install cpptraj in my window machine (took about ~ 1 hour to just compile ) + a bunch of window issues.

I am thinking about just using ParmEd as main backend for NGLView in Window but ParmEd does not have autoimage + superpose. :D So this is only good solution for visualize pre-process trajectory.

**Comment by swails** [comment]
Oh, Windows the operating system.  Not embedding it in some kind of GUI window or something.  Got it.

**Comment by hainm** [comment]
ack. I see. I will update the title.
