### ISSUE TITLE
Parallel hbond calculation

### ISSUE THREAD

**Issue by jludw** [Amber-MD/pytraj#1318]
When analyzing hydrogen bonds with pytraj and pt.pmap 

`data = pt.pmap(pt.search_hbonds, traj, n_cores=4)`

following error occurs:

```
File "/home/janek/amber16/lib/python2.7/site-packages/pytraj/parallel/multiprocessing_.py", line 241, in pmap return _pmap(func, traj, *args, **kwd)

File "/home/janek/amber16/lib/python2.7/site-packages/pytraj/parallel/multiprocessing_.py", line 236, in _pmap return concat_dict((x[1] for x in data))

File "/home/janek/amber16/lib/python2.7/site-packages/pytraj/tools.py", line 287, in concat_dict
    new_dict[k] = np.concatenate((new_dict[k], d[k]))
KeyError: u'ASP23_OD1-THR27_N-H'

```
The serial run on the same dataset passes without any problems. My guess is that pytraj assumes that certain hydrogen bond will occur in all chunks of the trajectory analyzed on the specific cores (function concat_dict() ) which is not the case for the short-lasting interactions like for example ASP23_OD1-THR27_N-H (0.04 occurence in whole trajectory). Any help will be much appreciated.

**Comment by drroe** [comment]
@jludw curious as to whether the same input works with cpptraj.MPI. If you get a chance to try that out let me know.

**Comment by hainm** [comment]
> The serial run on the same dataset passes without any problems. My guess is that pytraj assumes that certain hydrogen bond will occur in all chunks of the trajectory analyzed on the specific cores (function concat_dict() ) which is not the case for the short-lasting interactions like for example ASP23_OD1-THR27_N-H (0.04 occurence in whole trajectory). 

@jludw: exactly, cpptraj does that to save memory. I have not work on this yet and forgot to turn off the parallel calculation for hbond.  Will put this in my todo list.

Meanwhile, please try to use cpptraj.MPI as Daniel suggested. cheers.

**Comment by hainm** [comment]
turn outs that it's quick fix. Please try the github version

```bash
rm $AMBERHOME/lib/libcpptraj.so # so we can use cpptraj github version 
# (which will be installed by pytraj itself)
cd /to/your/favorite/dir
git clone https://github.com/Amber-MD/pytraj
cd pytraj
# if there's no git
# wget https://github.com/Amber-MD/pytraj/archive/master.zip
# unzip master
# cd pytraj-master
python setup.py install --prefix=$AMBERHOME # overwrite old version
```

This should works for `pmap` (not `pmap_mpi`) but this is a start. let us know if you get any issue. thanks for your report.

**Comment by hainm** [comment]
also support `pmap_mpi` to be used with `mpi4py`
#1321 

```bash
$ cat myscript.py

import pytraj as pt
from mpi4py import MPI
rank = MPI.COMM_WORLD.rank

traj = pt.iterload("data/tz2.nc", "data/tz2.parm7")
# hbond_data is an OrderedDict for now
hbond_data = pt.pmap_mpi(pt.search_hbonds, traj)

if rank == 0:
    print(hbond_data)

$ mpirun -n 10 python myscript.py
```

**Comment by jludw** [comment]
Hi, great thanks for the update and help with this issue. After small adjustments in my code everything works perfectly with pmap version (I'll check mpi version soon).
Just as a note (maybe you'll find it helpful in development), in the array storing the presence of certain hbond in certain frame, i.e. the time progression ([0, 0, 1, .. ... 0, 1]), the previously problematic hbonds ( the ones not occuring in all chunks of trajectory) have their values stored now as floats not ints (however after function astype(int) performed on the array everything is ok), here's a small digest of my list with previously problematic hbond marked:
`
LEU8_O-GLN12_N-H [1 0 0 ..., 1 1 0]

HIS13_O-CYS17_N-H [1 1 1 ..., 1 1 1]

THR29_O-LYS21_N-H [1 1 0 ..., 1 0 0]

ASP228_OD2-LYS21_NZ-HZ1 [1 1 1 ..., 1 1 1]

**ASP23_OD1-THR27_N-H [ 1.  0.  0. ...,  0.  0.  0.]**

THR25_OG1-THR27_OG1-HG1 [1 1 1 ..., 0 0 1]
etc.
`

**Comment by hainm** [comment]
>  the previously problematic hbonds ( the ones not occuring in all chunks of trajectory) have their values stored now as floats not ints (however after function astype(int) performed on the array everything is ok)

thanks for you suggestion. updated https://github.com/Amber-MD/pytraj/pull/1322/files.

**Comment by hainm** [comment]
I close this issue now. Feel free to open others.
