### ISSUE TITLE
Is rmsd mass weighted?

### ISSUE THREAD

**Issue by kain88-de** [Amber-MD/pytraj#1347]
I want to check some RMSD codes with custom weights. Is the rmsd function in pytraj mass weighted?

https://amber-md.github.io/pytraj/latest/rmsd.html?highlight=rmsd#pytraj.analysis.rmsd.rmsd

The docs say that there is a mass keyword but only states that they are included. I'm not sure what that means. Will they be used as weights for the coordinates?

**Comment by hainm** [comment]
Hi 

mass=True will be mass weighted.

**Comment by hainm** [comment]
See

tests/test_analysis/test_rmsd.py

**Comment by kain88-de** [comment]
thanks
