### ISSUE TITLE
[AMBER] Memory footprint goes on increasing: pytraj traj.iterchunk used, distances between bonds calculation

### ISSUE THREAD

**Issue by hainm** [Amber-MD/pytraj#1365]
from AMBER mailing list, by **SHAILESH KUMAR**

------
Dear all,

I am trying to process a big trajectory which can not fit in memory my
computer. So, I tried using Iterating over the full trajectory using
iterchunk method in pytraj. In each iteration bond lengths are calculated
for the frames in chunk, and can be written to a file (which currently is
disable for memory profiling purpose)  for further analysis because memory
footprint of the process keeps on growing.

Its pseudo code can be as follows:

```python
traj = ptraj.iterload(trajfile, prmtopfile, frame_slice=slice_info)

for chunk in traj.iterchunk(chunk_size, start=0, start=-1):
     bnd_vals = pt.distance(chunk, bnd_list, dtype='ndarray')
     # do process bnd_vals() ## curently disabled
     gc.collect()
```

But on memory profiling it was observed that memory keeps on increasing in
ievery iteration of chunks. Which indicates memory leak in
bnd_vals = pt.distance(chunk, bnd_list, dtype='ndarray')
but why is not clear to me. May be I am doing something wrong and not able
to spot it, or there is memory leak somewhere (may be in api).

Now I ask for help, if any one can help me to sort it out, it would be a
great favor. For reproduciblity i am attaching simplified code, with
necessary input files except trajectory, i can share it using dropbox when
needed. This test dataset corresponds to a small molecule. Actual problem
is to do similar for actual protein molecules.

**Comment by hainm** [comment]
Hi

iterchunk is not well written and I don't find it useful much.

can you try:

```
for frame in traj:
    dosomething(...)
```

But I will have a look at the iterchunk stuff. Thanks.

Hai

**Comment by hainm** [comment]
**SHAILESH KUMAR**:

Hi,

Thank you for reply.


Problem does not seem to be with iterchunk, because earlier I tried to do
chunking by calling ptraj.iterload inside loop emulating chunks and frame
slicing but had similar problems.

If ptraj.iterload is called inside loop with varying frame_slice combined
with range based extraction of frames, it should have not done problem, but
it did.

I suspect pytraj.distance, pytraj.angles and pytraj.dihedrals are causing
memory leaks. Apart from this, as you suggested using iterframes
it would be to costly in terms of performance to use because trajectory
have milions of frames and I am doing it to actually for coordinate system
conversion
for the molecule from cartesian to internal coordinate system. I intend to
write these bonds, angles, dihedrals sets as NETCDF4/HDF5 files with
chunking support
so that it can be efficiently read dimension wise(individual bonds/angles
/torsions) for all the frames.

Additionally, I am using netCDF4 package for writing NetCDF4 (currently
disabled for spoting memory leaks) trajectory in inernal coordinate, I
would prefer to use pytraj itself if I could write NetCDF4 with chunking
with it.

and reduce list of dependencies.

**Comment by hainm** [comment]
Hi,

so I looked further at your profile.log and saw:

```
 153    455.2 MiB     15.0 MiB               bonds_val = pt.distance(chunk, bnd_list, dtype='ndarray')
```

Isn't it expected since you save the distance val to bonds_val?

Can you try to replace bonds_val = pt.distance(...)
by 
bonds_val = some_equal_size_numpy_array
and do the profiling again?

Hai

**Comment by hainm** [comment]
> Apart from this, as you suggested using iterframes
it would be to costly in terms of performance to use because trajectory
have milions of frames and I am doing it to actually for coordinate system
conversion
for the molecule from cartesian to internal coordinate system. 

This is not my intention. I always try to encourage users to use 'iterframe'. Can you point out where I wrote that?

**Comment by shaileshp51** [comment]
Thanks Hai, 

[profile-np.txt](https://github.com/Amber-MD/pytraj/files/836956/profile-np.txt)
[profile.txt](https://github.com/Amber-MD/pytraj/files/836955/profile.txt)

a minor change to code as well:

```
@profile
def process_traj(traj, bnd_list, chunk_sz=60000):
    chunk_id = 0 
    print(len(bnd_list))
    for chunk in traj.iterchunk(chunk_sz, start=0, stop=-1):            
        chunk_end =  (chunk_id + 1) * chunk_sz if (chunk_id + 1) * chunk_sz < traj.n_frames else traj.n_frames       
        print("block stast, end: ", chunk_id * chunk_sz, chunk_end)
        if chunk_end - chunk_id * chunk_sz > 0:
            bonds_val = np.reshape(np.zeros(chunk_sz * len(bnd_list)), (32, 60000)) 
            #bonds_val = pt.distance(chunk, bnd_list, dtype='ndarray')
            print(bonds_val.shape)
            dummy()
            del bonds_val
        chunk_id += 1
        gc.collect()
```

I followed your suggestion to create a numpy array of exact shape as bonds_val and reprofile the code. 
I also tried using more frames (this time 3, millions, earlier I used 1 million).
I noticed that bonds_val = pt.distance(...) keeps on increasing memory footprint till last iteration. 
while with numpy array it increases initially some 4-5 iteration then becomes constant till the end. 

Hello Hai, I just said about what I wanted to do, I didn't mean to say anything else.

**Comment by hainm** [comment]
thanks. Sounds like a bug. I'll look at that. Meanwhile, feel free to make a pull request if you know how to fix it. cheers.

**Comment by shaileshp51** [comment]
Sure, I am trying to look into code. I don't know cython but reading about it. Thank you.

**Comment by hainm** [comment]
you can start from python code first: https://github.com/Amber-MD/pytraj/blob/master/pytraj/all_actions.py#L129

**Comment by hainm** [comment]
@shaileshp51 I really don't know if memory_profiler is very reliable. I've tried with my system and got different expectation

```python
$ python distance.py 
pytraj.TrajectoryIterator, 100000 frames: 
Size: 11.830777 (GB)
<Topology: 5293 atoms, 1704 residues, 1692 mols, PBC with box type = ortho>
           
100
block stast, end:  0 60000
(6000000,)
block stast, end:  60000 100000
(6000000,)
Filename: distance.py

Line #    Mem usage    Increment   Line Contents
================================================
    13     63.1 MiB      0.0 MiB   @profile
    14                             def process_traj(traj, bnd_list, chunk_sz=60000):
    15     63.1 MiB      0.0 MiB       chunk_id = 0 
    16     63.1 MiB      0.0 MiB       print(len(bnd_list))
    17    297.6 MiB    234.5 MiB       for chunk in traj.iterchunk(chunk_sz, start=0, stop=-1):            
    18    221.8 MiB    -75.8 MiB           chunk_end =  (chunk_id + 1) * chunk_sz if (chunk_id + 1) * chunk_sz < traj.n_frames else traj.n_frames       
    19    221.9 MiB      0.1 MiB           print("block stast, end: ", chunk_id * chunk_sz, chunk_end)
    20    221.9 MiB      0.0 MiB           if chunk_end - chunk_id * chunk_sz > 0:
    21    267.7 MiB     45.8 MiB               bonds_val = np.zeros(chunk_sz * len(bnd_list))
    22                                         # bonds_val = pt.distance(chunk, bnd_list, dtype='ndarray')
    23    267.7 MiB      0.0 MiB               print(bonds_val.shape)
    24    267.7 MiB      0.0 MiB               dummy()
    25    267.7 MiB      0.0 MiB               del bonds_val
    26    267.7 MiB      0.0 MiB           chunk_id += 1
    27    297.6 MiB     29.9 MiB           gc.collect()

```

**Comment by hainm** [comment]
Using pytraj.distance
===============

```python
$ python distance.py 
pytraj.TrajectoryIterator, 100000 frames: 
Size: 11.830777 (GB)
<Topology: 5293 atoms, 1704 residues, 1692 mols, PBC with box type = ortho>
           
100
block stast, end:  0 60000
(100, 60000)
block stast, end:  60000 100000
(100, 40000)
Filename: distance.py

Line #    Mem usage    Increment   Line Contents
================================================
    13     63.1 MiB      0.0 MiB   @profile
    14                             def process_traj(traj, bnd_list, chunk_sz=60000):
    15     63.1 MiB      0.0 MiB       chunk_id = 0 
    16     63.1 MiB      0.0 MiB       print(len(bnd_list))
    17    283.5 MiB    220.4 MiB       for chunk in traj.iterchunk(chunk_sz, start=0, stop=-1):            
    18    229.0 MiB    -54.4 MiB           chunk_end =  (chunk_id + 1) * chunk_sz if (chunk_id + 1) * chunk_sz < traj.n_frames else traj.n_frames       
    19    229.1 MiB      0.1 MiB           print("block stast, end: ", chunk_id * chunk_sz, chunk_end)
    20    229.1 MiB      0.0 MiB           if chunk_end - chunk_id * chunk_sz > 0:
    21                                         # bonds_val = np.zeros(chunk_sz * len(bnd_list))
    22    283.5 MiB     54.3 MiB               bonds_val = pt.distance(chunk, bnd_list, dtype='ndarray')
    23    283.5 MiB      0.0 MiB               print(bonds_val.shape)
    24    283.5 MiB      0.0 MiB               dummy()
    25    283.5 MiB      0.0 MiB               del bonds_val
    26    283.5 MiB      0.0 MiB           chunk_id += 1
    27    283.5 MiB      0.0 MiB           gc.collect()
```

**Comment by hainm** [comment]
Using pytraj.distance, 2nd run (different result
==================================

```python
$ python distance.py 
pytraj.TrajectoryIterator, 100000 frames: 
Size: 11.830777 (GB)
<Topology: 5293 atoms, 1704 residues, 1692 mols, PBC with box type = ortho>
           
100
block stast, end:  0 60000
(100, 60000)
block stast, end:  60000 100000
(100, 40000)
Filename: distance.py

Line #    Mem usage    Increment   Line Contents
================================================
    13     63.0 MiB      0.0 MiB   @profile
    14                             def process_traj(traj, bnd_list, chunk_sz=60000):
    15     63.0 MiB      0.0 MiB       chunk_id = 0 
    16     63.0 MiB      0.0 MiB       print(len(bnd_list))
    17    345.8 MiB    282.8 MiB       for chunk in traj.iterchunk(chunk_sz, start=0, stop=-1):            
    18    345.9 MiB      0.1 MiB           chunk_end =  (chunk_id + 1) * chunk_sz if (chunk_id + 1) * chunk_sz < traj.n_frames else traj.n_frames       
    19    346.0 MiB      0.1 MiB           print("block stast, end: ", chunk_id * chunk_sz, chunk_end)
    20    346.0 MiB      0.0 MiB           if chunk_end - chunk_id * chunk_sz > 0:
    21                                         # bonds_val = np.zeros(chunk_sz * len(bnd_list))
    22    246.0 MiB   -100.0 MiB               bonds_val = pt.distance(chunk, bnd_list, dtype='ndarray')
    23    246.1 MiB      0.2 MiB               print(bonds_val.shape)
    24    246.1 MiB      0.0 MiB               dummy()
    25    246.1 MiB      0.0 MiB               del bonds_val
    26    246.1 MiB      0.0 MiB           chunk_id += 1
    27    276.7 MiB     30.5 MiB           gc.collect()
```

**Comment by shaileshp51** [comment]
@hainm Can you try with smaller chunk size please, because for total 100000, chunk_sz=60000 would last only two iterations, my be use somthing less than 10000 for chunk_sz. I am also looking into it and will let you know my results

**Comment by hainm** [comment]
It's a good idea to run your script multiple times (10?) with `bonds_val = np.zeros(...)` and with `bonds_val = pt.distance(...)`.

**Comment by hainm** [comment]
much smaller size, 1st run with pytraj.distance
```python
$ python distance.py 
pytraj.TrajectoryIterator, 100000 frames: 
Size: 11.830777 (GB)
<Topology: 5293 atoms, 1704 residues, 1692 mols, PBC with box type = ortho>
           
100
block stast, end:  0 6000
(100, 6000)
block stast, end:  6000 12000
(100, 6000)
block stast, end:  12000 18000
(100, 6000)
block stast, end:  18000 24000
(100, 6000)
block stast, end:  24000 30000
(100, 6000)
block stast, end:  30000 36000
(100, 6000)
block stast, end:  36000 42000
(100, 6000)
block stast, end:  42000 48000
(100, 6000)
block stast, end:  48000 54000
(100, 6000)
block stast, end:  54000 60000
(100, 6000)
block stast, end:  60000 66000
(100, 6000)
block stast, end:  66000 72000
(100, 6000)
block stast, end:  72000 78000
(100, 6000)
block stast, end:  78000 84000
(100, 6000)
block stast, end:  84000 90000
(100, 6000)
block stast, end:  90000 96000
(100, 6000)
block stast, end:  96000 100000
(100, 4000)
Filename: distance.py

Line #    Mem usage    Increment   Line Contents
================================================
    13     62.8 MiB      0.0 MiB   @profile
    14                             def process_traj(traj, bnd_list, chunk_sz=60000):
    15     62.8 MiB      0.0 MiB       chunk_id = 0 
    16     62.8 MiB      0.0 MiB       print(len(bnd_list))
    17   1039.2 MiB    976.4 MiB       for chunk in traj.iterchunk(chunk_sz, start=0, stop=-1):            
    18   1039.2 MiB      0.0 MiB           chunk_end =  (chunk_id + 1) * chunk_sz if (chunk_id + 1) * chunk_sz < traj.n_frames else traj.n_frames       
    19   1039.2 MiB      0.0 MiB           print("block stast, end: ", chunk_id * chunk_sz, chunk_end)
    20   1039.2 MiB      0.0 MiB           if chunk_end - chunk_id * chunk_sz > 0:
    21                                         # bonds_val = np.zeros(chunk_sz * len(bnd_list))
    22   1039.2 MiB      0.0 MiB               bonds_val = pt.distance(chunk, bnd_list, dtype='ndarray')
    23   1039.2 MiB      0.0 MiB               print(bonds_val.shape)
    24   1039.2 MiB      0.0 MiB               dummy()
    25   1039.2 MiB      0.0 MiB               del bonds_val
    26   1039.2 MiB      0.0 MiB           chunk_id += 1
    27   1039.2 MiB      0.0 MiB           gc.collect()
```

**Comment by swails** [comment]
One thing I've noticed is that -- particularly on Windows -- monitoring memory usage in a Python script via task manager or top only tells you if a leak is possible, but not if it actually exists.  Python can hold onto memory longer than it's reachable from the Python runtime (that is, the garbage collector does not need to collect as soon as the refcount hits 0).

It's always a good idea to toss a `gc.collect()` somewhere to see if the memory profile stops increasing continuously.  But even there it's not a sure bet.

If it *is* leaking, [1] then it must be somewhere in the C/C++ code.  In that case, `valgrind` can help track it down.

[1] Pure Python doesn't technically *leak* unless the GC is broken, and it almost certainly isn't.  A Python "leak" is always some sort of collection that is accumulating objects (lists, sets, and dicts are the most common suspects) regularly without purging them.  But those objects are *always* reachable, so they can be `del`ed... if you know where to find them :).

**Comment by shaileshp51** [comment]
I tried to profile pytraj.distance and had following observation

when frame._distance was open profile looked like:
```
   206    440.4 MiB     18.6 MiB           for idx, frame in enumerate(iterframe_master(traj)):
   207                                         #pass
   208    440.4 MiB      0.0 MiB               arr[idx] = frame._distance(int_2darr)
   209                                         #arr[idx] = frame.n_atoms
```
in every iteration it went on allocation memory but not freeing possibly, so check this hypothesis i just commented line# 208 above and added another property from frame to be sure that memory is leaking from method not the frame object itself, results are below
```
   206    142.9 MiB      0.0 MiB           for idx, frame in enumerate(iterframe_master(traj)):
   207                                         #pass
   208                                         #arr[idx] = frame._distance(int_2darr)
   209    142.9 MiB      0.0 MiB               arr[idx] = frame.n_atoms
```
which indicates that frame._distance(...) is causing problem.

I tried to look into frame._distance as well and found that it is written in cython. May we should check frame._distance(...)

**Comment by hainm** [comment]
could be, because cython has its own way to manage memory. 

btw, that code is quite simple

https://github.com/Amber-MD/pytraj/blob/master/pytraj/trajectory/frame.pyx#L926-L967

**Comment by hainm** [comment]
again: you really need to run the profiling multiple times.

**Comment by shaileshp51** [comment]
Hi,
As I earlier suspected that memory is leaking in frame_distance(...) method. It seems true, and also all the functions using memoryview for  cython.array can cause so with python2.7 as it is reported [here see answer by Matt Graham](http://stackoverflow.com/questions/18462785/what-is-the-recommended-way-of-allocating-memory-for-a-typed-memory-view). 

After reading it I decided to look into it. So, performed exactly same calculations with the same script with python2.7.13 and python3.5.2 because Matt had reported there that there is memory leak problem with memoryview for cython.array with python2.7 but not with python3

profiling report with relevant part is as below
with python2.7.13:
```
File: frame.pyx
   206   1080.8 MiB     18.7 MiB           for idx, frame in enumerate(iterframe_master(traj)):
   207                                         #pass
   208   1080.8 MiB      0.0 MiB               arr[idx] = frame._distance(int_2darr)
   209                                         #arr[idx] = frame.n_atoms
```
with final footprint as:
```
Line #    Mem usage    Increment   Line Contents
================================================
   147     75.7 MiB      0.0 MiB   @profile
   148                             def process_traj(traj, bnd_list, chunk_sz=60000):
   149     75.7 MiB      0.0 MiB       chunk_id = 0 
   150     75.7 MiB      0.0 MiB       print(len(bnd_list))
   151   1080.8 MiB   1005.1 MiB       for chunk in traj.iterchunk(chunk_sz, start=0, stop=-1):            
   152   1062.1 MiB    -18.7 MiB           chunk_end =  (chunk_id + 1) * chunk_sz if (chunk_id + 1) * chunk_sz < traj.n_frames else traj.n_frames       
   153   1062.1 MiB      0.0 MiB           print("block stast, end: ", chunk_id * chunk_sz, chunk_end)
   154   1062.1 MiB      0.0 MiB           if chunk_end - chunk_id * chunk_sz > 0:
   155                                         #bonds_val = np.reshape(np.zeros(chunk_sz * len(bnd_list)), (32, 60000)) 
   156   1080.8 MiB     18.7 MiB               bonds_val = pt.distance(chunk, bnd_list, dtype='ndarray')
   157   1080.8 MiB      0.0 MiB               dummy(chunk_sz, bnd_list)
   158                                         #bonds_val = dummy(chunk_sz, bnd_list)
   159   1080.8 MiB      0.0 MiB               print(bonds_val.shape)
   160   1080.8 MiB      0.0 MiB               del bonds_val
   161   1080.8 MiB      0.0 MiB           chunk_id += 1
   162   1080.8 MiB      0.0 MiB           gc.collect()
```

while with python3.5.2, without any modification to the pytraj code frame.pyx:
```
Line #    Mem usage    Increment   Line Contents
================================================
   147     78.4 MiB      0.0 MiB   @profile
   148                             def process_traj(traj, bnd_list, chunk_sz=60000):
   149     78.4 MiB      0.0 MiB       chunk_id = 0 
   150     78.4 MiB      0.0 MiB       print(len(bnd_list))
   151    144.1 MiB     65.7 MiB       for chunk in traj.iterchunk(chunk_sz, start=0, stop=-1):            
   152    144.1 MiB      0.0 MiB           chunk_end =  (chunk_id + 1) * chunk_sz if (chunk_id + 1) * chunk_sz < traj.n_frames else traj.n_frames       
   153    144.1 MiB      0.0 MiB           print("block stast, end: ", chunk_id * chunk_sz, chunk_end)
   154    144.1 MiB      0.0 MiB           if chunk_end - chunk_id * chunk_sz > 0:
   155                                         #bonds_val = np.reshape(np.zeros(chunk_sz * len(bnd_list)), (32, 60000)) 
   156    144.1 MiB      0.0 MiB               bonds_val = pt.distance(chunk, bnd_list, dtype='ndarray')
   157    144.1 MiB      0.0 MiB               dummy(chunk_sz, bnd_list)
   158                                         #bonds_val = dummy(chunk_sz, bnd_list)
   159    144.1 MiB      0.0 MiB               print(bonds_val.shape)
   160    144.1 MiB      0.0 MiB               del bonds_val
   161    144.1 MiB      0.0 MiB           chunk_id += 1
   162    144.1 MiB      0.0 MiB           gc.collect()
```

Both of these test were performed 10 times to ruleout any memory_profiler memory usage reporting variation.

This way it was clear, first point that it is with python2, not with python3
For second point that is is with memoryview of cython.array i tweaked
``` 
 pytraj frame.pyx file 

frame._distance(...)
def _calc_distance(..):
      ...


and replaced cython.array line with equivallent numpy.array like

 947         #cdef pyarray arr0 = cparray.clone(pyarray('d', []), n_arr, zero=False)
 948         arr0 = np.arange(n_arr, dtype=np.dtype("d"))
```
 and installed this code in python2.7 and rechecked through memory profiling and found that now it does not seem to leak memory as final memory profile result is in agreement with that found using python3.5.2 as shown above.

```
Line #    Mem usage    Increment   Line Contents
================================================
   147     75.8 MiB      0.0 MiB   @profile
   148                             def process_traj(traj, bnd_list, chunk_sz=60000):
   149     75.9 MiB      0.0 MiB       chunk_id = 0 
   150     75.9 MiB      0.0 MiB       print(len(bnd_list))
   151    145.5 MiB     69.6 MiB       for chunk in traj.iterchunk(chunk_sz, start=0, stop=-1):            
   152    145.5 MiB      0.0 MiB           chunk_end =  (chunk_id + 1) * chunk_sz if (chunk_id + 1) * chunk_sz < traj.n_frames else traj.n_frames       
   153    145.5 MiB      0.0 MiB           print("block stast, end: ", chunk_id * chunk_sz, chunk_end)
   154    145.5 MiB      0.0 MiB           if chunk_end - chunk_id * chunk_sz > 0:
   155                                         #bonds_val = np.reshape(np.zeros(chunk_sz * len(bnd_list)), (32, 60000)) 
   156    145.5 MiB      0.0 MiB               bonds_val = pt.distance(chunk, bnd_list, dtype='ndarray')
   157    145.5 MiB      0.0 MiB               dummy(chunk_sz, bnd_list)
   158                                         #bonds_val = dummy(chunk_sz, bnd_list)
   159    145.5 MiB      0.0 MiB               print(bonds_val.shape)
   160    145.5 MiB      0.0 MiB               del bonds_val
   161    145.5 MiB      0.0 MiB           chunk_id += 1
   162    145.5 MiB      0.0 MiB           gc.collect()
```

On basis of above it can be concluded that there is memory leak problem with use of memoryview for cython.array with python2(atleat 2.7.13), which is not with same cython & python3.5.2 cobination.

So, I will like to use python3 for my work.
A Quick Fix may be to use with python2::: all memoryview usage with cython.array may be replaced with equivalent numpy.array for the time this cython bug is not fixed. this bug has been reported to cython developers long back see: [here](https://mail.python.org/pipermail/cython-devel/2013-September/003821.html)

Thanks for considering my problem, opening an issue open discussion and insiteful directions.
Cheers: At least we found the cause of problem

No it comes second part of my query.

Is is possible to write NetCDF5/HDF5 files with chunking using pytraj without any external package?
I am curios to know it because pytraj writes trajectory in netcdf format, so i think, it can write custom format netcdf files. Any direction from your side will be valuable.

Thanks again.

**Comment by hainm** [comment]
great. I always use python 3 so I did not see that issue. That's why. :D 

As you pointed out, this should be an easy fix. 

Per your question, can you please open in another issue? (easier to search in the future). thanks.

Hai

**Comment by hainm** [comment]
oh, never mind. pytraj only write trajectory format (actually cpptraj did that). You can not use pytraj to write any custom format.

But if you're using `conda`, you can easily install any popular packages within seconds. So I do not think this is a big issue with you.

**Comment by shaileshp51** [comment]
Its right I can use use other package, currently i use netCDF4 for this. But i was thinking to make it a function so that users willing to do coordinate conversion do not have to install to many dependencies.

OK, we can discuss over it in other issue.

**Comment by hainm** [comment]
@shaileshp51 

I've tried and I think the memory leak is due to the [`__iter__` here](https://github.com/Amber-MD/pytraj/blob/master/pytraj/trajectory/c_traj/c_trajectory.pyx#L147-L165). (I can not reproduce your observation with cython array stuff above0.

 I am not sure where the source of the leak is. :D 

My simple code
```python
import pytraj as pt
from memory_profiler import profile

traj = pt.iterload(['tz2.ortho.nc',]*4000, top='tz2.ortho.parm7')
print(traj)

@profile
def process_traj(traj):
    # for chunk in traj.iterchunk(chunk_sz, start=0, stop=-1):            
    for frame in traj:
        pass

process_traj(traj)
```

The memory increase 10 times if increasing the number of frames. Sounds serious. (I had been checking memory leak a year ago and did not see this happened).

# Run 1
```python
$ python distance.py 
pytraj.TrajectoryIterator, 4000 frames: 
Size: 0.473231 (GB)
<Topology: 5293 atoms, 1704 residues, 1692 mols, PBC with box type = ortho>
           
Filename: distance.py

Line #    Mem usage    Increment   Line Contents
================================================
     7     50.1 MiB      0.0 MiB   @profile
     8                             def process_traj(traj):
     9                                 # for chunk in traj.iterchunk(chunk_sz, start=0, stop=-1):            
    10     74.5 MiB     24.4 MiB       for frame in traj:
    11     74.5 MiB     -0.0 MiB           pass
```

# Run 2: increase n_frames 10 times

```python
pytraj.TrajectoryIterator, 40000 frames: 
Size: 4.732311 (GB)
<Topology: 5293 atoms, 1704 residues, 1692 mols, PBC with box type = ortho>
           
Filename: distance.py

Line #    Mem usage    Increment   Line Contents
================================================
     7     54.7 MiB      0.0 MiB   @profile
     8                             def process_traj(traj):
     9                                 # for chunk in traj.iterchunk(chunk_sz, start=0, stop=-1):            
    10    298.8 MiB    244.1 MiB       for frame in traj:
    11    298.8 MiB     -0.0 MiB           pass
```

**Comment by hainm** [comment]
@drroe I narrow down the issue and seems like the the leak is from `GetFrame` in cpptraj. Any idea why?

```python
    def __iter__(self):
        '''iterately getting Frame instance
        '''
        cdef int i
        cdef int n_atoms = self.n_atoms
        cdef int n_frames = self.n_frames

        # use `frame` as buffer
        cdef Frame frame = Frame()

        # del frame.thisptr # do not do this.
        frame.thisptr[0] = self.thisptr.AllocateFrame()

        for i in range(n_frames):
            # do not create new Frame inside this loop to reduce memory
            self.thisptr.GetFrame(i, frame.thisptr[0])
            if self._being_transformed:
                self._do_transformation(frame)
            yield frame
```

If I comment the line
```self.thisptr.GetFrame(i, frame.thisptr[0])```, there won't be any extra memory.

turn off `GetFrame`
==============
```python
 Line #    Mem usage    Increment   Line Contents
================================================
    13     49.0 MiB      0.0 MiB   @profile
    14                             def process_traj(traj):
    15                                 # for chunk in traj.iterchunk(chunk_sz, start=0, stop=-1):            
    16     49.0 MiB      0.1 MiB       for frame in traj:
    17     49.0 MiB     -0.0 MiB           pass
```

turn ON (leak)
==========
```python
Line #    Mem usage    Increment   Line Contents
================================================
    13     48.9 MiB      0.0 MiB   @profile
    14                             def process_traj(traj):
    15                                 # for chunk in traj.iterchunk(chunk_sz, start=0, stop=-1):            
    16     73.2 MiB     24.3 MiB       for frame in traj:
    17     73.2 MiB     -0.0 MiB           pass
```

PS: Using `tz2.ortho.nc`

**Comment by hainm** [comment]
Just updated code to reproduce the leak above.

**Comment by hainm** [comment]
Random though: above script is loading 400-4000 small files. May be the extra memory is due to allocating `Topology`?

**Comment by drroe** [comment]
@hainm the only thing I can think of depends on these three things being true:

1. You are using a DataSet_Coords_TRJ under the hood.
2. Somehow in your Frame object, the `memIsExternal_` variable is being set to `true`. 
3. Somehow in the `DataSet_Coords_TRJ::GetFrame()` function, `IDX_TrajHasChanged()` is always coming back as true [here](https://github.com/Amber-MD/cpptraj/blob/e9e664322884cb9bd6b5cb71a205e58377366183/src/DataSet_Coords_TRJ.cpp#L100-L102).

The end result of this would be that whenever you `GetFrame()` the `Frame::ReallocateX()` function ends up being called, and because `memIsExternal_` the Frame thinks it needs to reallocate the memory.

If this is the case it means that the `DataSet_Coords_TRJ` object is not being used correctly/needs to be updated to work properly for this particular use case. I don't think in this case `memIsExternal_` would need to be set, but it's been a while since I added that so maybe I'm forgetting something obvious. Anyway, this is a place to start. I can't look into it too deeply today, but will try to give it more time before the end of the week.

**Comment by hainm** [comment]
1. Yes
3. likely :D 

thanks.

**Comment by hainm** [comment]
@drroe any chance you have looked at the memory leak in DataSet_Coords_TRJ?

**Comment by drroe** [comment]
@hainm is this still a problem? If so I will prioritize before next AT release.

**Comment by hainm** [comment]
hi @drroe, I repeat the code in https://github.com/Amber-MD/pytraj/issues/1365#issuecomment-286286364 and I do not see the memory leak anymore.

thanks.
