### ISSUE TITLE
About possibility of writing custom format NetCDF4/HDF5 files pytraj+cpptraj??

### ISSUE THREAD

**Issue by shaileshp51** [Amber-MD/pytraj#1366]
Is is possible to write NetCDF5/HDF5 files with chunking using pytraj without any external package?
I am curios to know it because pytraj writes trajectory in netcdf format, so i think, it can write custom format netcdf files. Any direction from your side will be valuable.

**Comment by drroe** [comment]
Any NetCDF/HDF file writes would have to be through some sort of python API that supports that. Under the hood, CPPTRAJ (and the rest of Amber) uses NetCDF 3 (classic) format with large file support. Initial tests with HDF5 showed no performance benefit (and actually some slowdown) for MD trajectory data. However, this may have changed in recent versions - I haven't tested this in years.

**Comment by hainm** [comment]
> Is is possible to write NetCDF5/HDF5 files with chunking using pytraj without any external package?

It's not possible to do this. Even cpptraj is still using libnetcdf.
It's very cheap and easy to install netcdf and hdf5 in python. (e.g: http://www.h5py.org/).

I go ahead closing this issue. cheers.
