### ISSUE TITLE
Simple way to run single unit tests

### ISSUE THREAD

**Issue by drroe** [Amber-MD/pytraj#1369]
Right now it seems like it's either all tests, a very simple test, or nothing. It would be useful to be able to e.g. run just the multidihedral test if I see that it is failing by doing something like:
```
python run_tests.py tests/test_analysis/test_multidihedral.py
```
Also, is there any way to get more details on the failures? Right now it's either PASS, SKIP, or FAIL.

**Comment by hainm** [comment]
hi

```bash
pip install pytest
cd tests

# run all tests in test_multidihedral.py
pytest -vs test_analysis/test_multidihedral.py

# run a function name in that file
pytest -vs test_analysis/test_multidihedral.py -k pattern_mattching
```

**Comment by hainm** [comment]
add `-vv` (and even more `v`) to see more error message.

**Comment by drroe** [comment]
Cool, thanks! This may be good info to put on the pytraj wiki.

**Comment by hainm** [comment]
updated, thanks: https://github.com/Amber-MD/pytraj/wiki/run-pytraj-tests
