### ISSUE TITLE
support for pairwise energy decomposition

### ISSUE THREAD

**Issue by kellonb** [Amber-MD/pytraj#1381]
Hi Hai, 

I am currently using pt.energy_decomposition in pytraj and I find it extremely useful. 
I was wondering if there is any plans to implement a pairwise version, where I can use regular amber mask and decompose the energy pairwise.

**Comment by hainm** [comment]
cc @drroe

**Comment by hainm** [comment]
uhm I think the pairwise code is in `mmpbsa_py` program.

**Comment by hainm** [comment]
Shoud be at pysander level, not cpptraj.

**Comment by hainm** [comment]
I think this is nice feature to add. Will read pysander code if it's easy to do.

**Comment by kellonb** [comment]
Thanks Hai. I have been doing pairwise decomposition using sander but agree it will be cool if it was in pytraj even if it was similar to the pairwise cpptraj command for non bonded interactions.

**Comment by swails** [comment]
This will be quite time-consuming to add to pysander.

**Comment by hainm** [comment]
Ah I agree.

@Kellon:
Meanwhile, you can check mmpbsa_py manual for python API. (I think it dumps
data to dictionary)

Hai

**Comment by kellonb** [comment]
I will check it out Hai. Thanks!

**Comment by hainm** [comment]
@kellonb I just check `pysander` code and it's quite complicated for me to add this functionality. I don't foresee its implementation soon, so I will close this. Definitely should check out mmpbsa_py for Python API.

cheers
