### ISSUE TITLE
obtain list of residue indices

### ISSUE THREAD

**Issue by ajerschow** [Amber-MD/pytraj#1382]
I'd like to get an array of residue indices using a given mask. It seems that one can get atom indices with traj.top.select(mask), but could not find a way to do the same for not residue indices. 

What I'd like to do is select a certain residue type and then step individually through the different residues of a given type. I thought maybe residue indices would be a good way to do it, but maybe there is a better way?
Thank you

**Comment by hainm** [comment]
hi, can you please post a pseudo-code here about what you meant?

**Comment by ajerschow** [comment]
this is what I would like to do:

iterate through all residues named 'OL'
   select all H atoms in the current OL residue
   calculate distances between all the H atoms within the current 'OL' residue

one way to achieve this, I thought, may be by using something like this
traj2=traj[':1@H=']      # this would select all hydrogen atoms in residue 1
But how do I know which residue indexes are 'OL' residues? 

If I select all 'OL' residues, by using, for example,
traj3=traj[':OL@H=']
then I don't know which atoms belong to a single OL residue.

**Comment by hainm** [comment]
You can try this

```python
In [48]: from itertools import combinations

In [49]: top = traj.top.simplify() # convert cpptraj's Topology to Pytraj's Topology for easy handling.

In [52]: for residue in top.residues:
    ...:     if residue.name == 'OL':
    ...:         h_indices = [atom.index for atom in residue.atoms 
    ....                              if atom.atomic_number == 1]
    ...:         pairs = np.array(list(combinations(h_indices, 2)))
    ...:         h_distances = pt.distance(traj, mask=pairs)
    ...:     
```

Let me know that works for now. cheers.

**Comment by hainm** [comment]
>  obtain list of residue indices

```python
res_indices = [res.index for res in top.residues if res.name == 'OL']
```

**Comment by ajerschow** [comment]
Dear Hai, Thank you so much for your help! This is exactly what I need and it worked perfectly.

**Comment by hainm** [comment]
Cool.
