### ISSUE TITLE
determine directly bonded neighbors from amber topology

### ISSUE THREAD

**Issue by ajerschow** [Amber-MD/pytraj#1385]
Here is what I would like to do:

I select a series of hydrogens from residue one using :1@H2R,H3R,H4R , for example. What would be the easiest way to obtain the selection for the directly bonded carbon atoms? 
Thank you

**Comment by hainm** [comment]
You miss the description.

**Comment by ajerschow** [comment]
I am sorry, included now: 

Here is what I would like to do:

I select a series of hydrogens from residue one using :1@H2R,H3R,H4R , for example. What would be the easiest way to obtain the selection for the directly bonded carbon atoms?
Thank you

**Comment by hainm** [comment]
hi,

I don't know yet about pytraj but if you do extensive work with atom selection like that, it would be more handy to use get familiar with [parmed](http://parmed.github.io/ParmEd/html/index.html).
(both pytraj and parmed are available in AmberTools 17 (source code and binary): http://ambermd.org/#AmberTools)

e.g:
```python
import parmed
parm = parmed.load_file('your.parm7') # or anything else
In [11]: h_atoms = [atom for atom in parm.residues[0] if atom.name.startswith('H')]

In [12]: [atom.bonds for atom in h_atoms]
Out[12]: 
[[<Bond <Atom N [0]; In SER 0>--<Atom H1 [1]; In SER 0>; type=<BondType; k=434.000, req=1.010>>],
 [<Bond <Atom N [0]; In SER 0>--<Atom H2 [2]; In SER 0>; type=<BondType; k=434.000, req=1.010>>],
 [<Bond <Atom N [0]; In SER 0>--<Atom H3 [3]; In SER 0>; type=<BondType; k=434.000, req=1.010>>],
 [<Bond <Atom CA [4]; In SER 0>--<Atom HA [5]; In SER 0>; type=<BondType; k=340.000, req=1.090>>],
 [<Bond <Atom CB [6]; In SER 0>--<Atom HB2 [7]; In SER 0>; type=<BondType; k=340.000, req=1.090>>],
 [<Bond <Atom CB [6]; In SER 0>--<Atom HB3 [8]; In SER 0>; type=<BondType; k=340.000, req=1.090>>],
 [<Bond <Atom OG [9]; In SER 0>--<Atom HG [10]; In SER 0>; type=<BondType; k=553.000, req=0.960>>]]
```

Then you can certainly pass the atom index to pytraj analysis methods.

```python
In [14]: mask = [atom.idx for atom in h_atoms]

In [15]: mask
Out[15]: [1, 2, 3, 5, 7, 8, 10]

In [16]: pytraj.calc_center_of_mass(traj, mask)
Out[16]: 
array([[ -1.60271427,  10.47171429,   7.82357155],
       [  0.82371431,   5.48071432,   4.65685712],
       [  2.49642854,   4.23271424,   1.99628571],
       ..., 
       [  4.04242863,   8.89914281,   3.07514286],
       [  1.7117143 ,   9.00999996,   3.54171426],
       [  3.1932857 ,   8.77000005,   1.43985714]])

```

**Comment by hainm** [comment]
Please see @swails comment here too: https://github.com/ParmEd/ParmEd/issues/882#issuecomment-307457369

**Comment by ajerschow** [comment]
Thank you so much!
