### ISSUE TITLE
installation in Mac

### ISSUE THREAD

**Issue by taushifkhan** [Amber-MD/pytraj#1396]
Hello,
I am using Mac. I want to install pytraj but having following error,
'''
(pyMd) taushif@taushifs-MacBook-Pro:mDAnalysis$ python -c 'import pytraj'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/taushif/Taushif_Ib2/mDAnalysis/amber16/lib/python2.7/site-packages/pytraj/__init__.py", line 23, in <module>
    from .utils.misc import info
  File "/Users/taushif/Taushif_Ib2/mDAnalysis/amber16/lib/python2.7/site-packages/pytraj/utils/misc.py", line 7, in <module>
    from pytraj.core.c_options import set_world_silent
  File "/Users/taushif/Taushif_Ib2/mDAnalysis/amber16/lib/python2.7/site-packages/pytraj/core/__init__.py", line 2, in <module>
    from .topology_objects import Atom, Residue, Molecule
ImportError: dlopen(/Users/taushif/Taushif_Ib2/mDAnalysis/amber16/lib/python2.7/site-packages/pytraj/core/topology_objects.so, 2): Symbol not found: ___addtf3
  Referenced from: /usr/local/gfortran/lib/libquadmath.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/gfortran/lib/libquadmath.0.dylib
'''
I have tried following

1. installing through miniconda
2. installed amber tools and then installed pytraj.
I have configured amber tools with gcc compiler but could not able to resolve the issue.

**Comment by hainm** [comment]
Per 2nd option:

Which ambertools version? Ambertools17 already have pytraj so you dont need install pytraj independently.

How do you install them (from source code or from binary?)

**Comment by taushifkhan** [comment]
First I tried to install pytraj with miniconda. 
Then I install Amber16 and again tried installing pytraj with pip and source code.
—
Regards,

Taushif Khan
Ph.D.
Post-Doctoral Research,
Inter university Institute of Bioinformatics in Brussels (IB-Square),
Brussels, Belgium

**Comment by hainm** [comment]
Can you try to create completely new conda env and try again?

```
conda create -n test python=3.6 numpy
source activate test
pip install pytraj
```

**Comment by hainm** [comment]
(Normally posting exact commands you tried would be very helpful to debug)

**Comment by taushifkhan** [comment]
okay I did exactly as instructed,

1. created new condo environment:
conda create -n test python=3 numpy

2. installed pytraj
 pip install pytraj 

but error remains the same:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/taushif/Taushif_Ib2/mDAnalysis/amber16/lib/python2.7/site-packages/pytraj/__init__.py", line 23, in <module>
    from .utils.misc import info
  File "/Users/taushif/Taushif_Ib2/mDAnalysis/amber16/lib/python2.7/site-packages/pytraj/utils/misc.py", line 7, in <module>
    from pytraj.core.c_options import set_world_silent
  File "/Users/taushif/Taushif_Ib2/mDAnalysis/amber16/lib/python2.7/site-packages/pytraj/core/__init__.py", line 2, in <module>
    from .topology_objects import Atom, Residue, Molecule
ImportError: dlopen(/Users/taushif/Taushif_Ib2/mDAnalysis/amber16/lib/python2.7/site-packages/pytraj/core/topology_objects.so, 2): Symbol not found: ___addtf3
  Referenced from: /usr/local/gfortran/lib/libquadmath.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/gfortran/lib/libquadmath.0.dylib

—
Regards,

Taushif Khan
Ph.D.
Post-Doctoral Research,
Inter university Institute of Bioinformatics in Brussels (IB-Square),
Brussels, Belgium

**Comment by hainm** [comment]
> /Users/taushif/Taushif_Ib2/mDAnalysis/amber16/lib/python2.7/site-packages/pytraj/

If you look more carefully, this is not the pytraj version you install by pip. It's from amber16.
if you

```bash
echo $PYTHONPATH
```, you will see `/Users/taushif/Taushif_Ib2/mDAnalysis/amber16/lib/python2.7/site-packages/` in that path, that's why Python pick that amber16 directory first.

try
```
unset PYTHONPATH
python -c "import pytraj"
```

**Comment by hainm** [comment]
and you did not do as instructed. There are 3 steps  I posted above

> conda create -n test python=3 numpy

create new env

> source activate test

activate your env

> pip install pytraj

install pytraj in your "test" env

**Comment by taushifkhan** [comment]
(test) taushif@taushifs-MacBook-Pro:mDAnalysis$ unset PYTHONPATH
(test) taushif@taushifs-MacBook-Pro:mDAnalysis$ python -c "import pytraj"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/taushif/miniconda2/envs/test/lib/python3.6/site-packages/pytraj/__init__.py", line 23, in <module>
    from .utils.misc import info
  File "/Users/taushif/miniconda2/envs/test/lib/python3.6/site-packages/pytraj/utils/misc.py", line 7, in <module>
    from pytraj.core.c_options import set_world_silent
  File "/Users/taushif/miniconda2/envs/test/lib/python3.6/site-packages/pytraj/core/__init__.py", line 2, in <module>
    from .topology_objects import Atom, Residue, Molecule
ImportError: dlopen(/Users/taushif/miniconda2/envs/test/lib/python3.6/site-packages/pytraj/core/topology_objects.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libnetcdf.7.dylib
  Referenced from: /Users/taushif/miniconda2/envs/test/lib/python3.6/site-packages/pytraj/lib/libcpptraj.dylib
  Reason: image not found
—
Regards,

Taushif Khan
Ph.D.
Post-Doctoral Research,
Inter university Institute of Bioinformatics in Brussels (IB-Square),
Brussels, Belgium

**Comment by taushifkhan** [comment]
I did as posted. 
the tried inside condo environment.

—
Regards,

Taushif Khan
Ph.D.
Post-Doctoral Research,
Inter university Institute of Bioinformatics in Brussels (IB-Square),
Brussels, Belgium

**Comment by hainm** [comment]
> Library not loaded: @rpath/libnetcdf.7.dylib

you are in the right track. This mean that your computer does not have `libnetcdf` (pytraj should include this but I originally though users should have it).

May be try either of this and see if that works

1. via conda

```
conda install libnetcdf
```

or via `brew`

```
brew install libnetcdf
```

**Comment by taushifkhan** [comment]
I have installed libnetcdf using condo. 
but now its saying libquadmath error. 
Tried installing libquadmath from conda : says missing for OS X-64

(test) taushif@taushifs-MacBook-Pro:mDAnalysis$ python -c 'import pytraj'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/taushif/Taushif_Ib2/mDAnalysis/amber16/lib/python2.7/site-packages/pytraj/__init__.py", line 23, in <module>
    from .utils.misc import info
  File "/Users/taushif/Taushif_Ib2/mDAnalysis/amber16/lib/python2.7/site-packages/pytraj/utils/misc.py", line 7, in <module>
    from pytraj.core.c_options import set_world_silent
  File "/Users/taushif/Taushif_Ib2/mDAnalysis/amber16/lib/python2.7/site-packages/pytraj/core/__init__.py", line 2, in <module>
    from .topology_objects import Atom, Residue, Molecule
ImportError: dlopen(/Users/taushif/Taushif_Ib2/mDAnalysis/amber16/lib/python2.7/site-packages/pytraj/core/topology_objects.so, 2): Symbol not found: ___addtf3
  Referenced from: /usr/local/gfortran/lib/libquadmath.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/gfortran/lib/libquadmath.0.dylib
(test) taushif@taushifs-MacBook-Pro:mDAnalysis$ conda install libquadmath
Fetching package metadata .........

PackageNotFoundError: Package missing in current osx-64 channels: 
  - libquadmath
—
Regards,

Taushif Khan
Ph.D.
Post-Doctoral Research,
Inter university Institute of Bioinformatics in Brussels (IB-Square),
Brussels, Belgium

**Comment by hainm** [comment]
Please pay attention to your python path.

You are trying to use pytraj in amber16 again.

**Comment by taushifkhan** [comment]
(test) taushif@taushifs-MacBook-Pro:mDAnalysis$ conda install libnetcdf
Fetching package metadata .........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /Users/taushif/miniconda2/envs/test:
#
libnetcdf                 4.4.1                         1  
(test) taushif@taushifs-MacBook-Pro:mDAnalysis$ python -c 'import pytraj'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/taushif/miniconda2/envs/test/lib/python3.6/site-packages/pytraj/__init__.py", line 23, in <module>
    from .utils.misc import info
  File "/Users/taushif/miniconda2/envs/test/lib/python3.6/site-packages/pytraj/utils/misc.py", line 7, in <module>
    from pytraj.core.c_options import set_world_silent
  File "/Users/taushif/miniconda2/envs/test/lib/python3.6/site-packages/pytraj/core/__init__.py", line 2, in <module>
    from .topology_objects import Atom, Residue, Molecule
ImportError: dlopen(/Users/taushif/miniconda2/envs/test/lib/python3.6/site-packages/pytraj/core/topology_objects.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libnetcdf.7.dylib
  Referenced from: /Users/taushif/miniconda2/envs/test/lib/python3.6/site-packages/pytraj/lib/libcpptraj.dylib
  Reason: image not found
—
Regards,

Taushif Khan
Ph.D.
Post-Doctoral Research,
Inter university Institute of Bioinformatics in Brussels (IB-Square),
Brussels, Belgium

**Comment by hainm** [comment]
Sorry for all troubles you ar getting.
Here is the final attempt

- uninstall pytraj

conda uninstall pytraj

- then install ambertools distribution that include pytraj and libnetcdf

*conda install ambertools=17 -c
http://ambermd.org/downloads/ambertools/conda/
<http://ambermd.org/downloads/ambertools/conda/>*

*Hai*

**Comment by taushifkhan** [comment]
after installing amber tools with conda.

In [1]: import pytraj as pt
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-abfc5c294136> in <module>()
----> 1 import pytraj as pt

/Users/taushif/miniconda2/lib/python2.7/site-packages/pytraj/__init__.py in <module>()
     21 from .utils import c_commands
     22 from .utils import tools
---> 23 from .utils.misc import info
     24 from .utils.cyutils import _fast_iterptr as iterframe_from_array
     25 from .core.c_options import info as compiled_info

/Users/taushif/miniconda2/lib/python2.7/site-packages/pytraj/utils/misc.py in <module>()
      5 import os
      6 from glob import glob
----> 7 from pytraj.core.c_options import set_world_silent
      8 
      9 # external

/Users/taushif/miniconda2/lib/python2.7/site-packages/pytraj/core/__init__.py in <module>()
      1 """"""
----> 2 from .topology_objects import Atom, Residue, Molecule
      3 from .box import Box
      4 from .elements import mass_atomic_number_dict, mass_element_dict

ImportError: dlopen(/Users/taushif/miniconda2/lib/python2.7/site-packages/pytraj/core/topology_objects.so, 2): Library not loaded: @rpath/libnetcdf.7.dylib
  Referenced from: /Users/taushif/miniconda2/lib/python2.7/site-packages/pytraj/lib/libcpptraj.dylib
  Reason: image not found

In [2]: exit
(test) taushif@taushifs-MacBook-Pro:mDAnalysis$ python -c 'import pytraj'
(test) taushif@taushifs-MacBook-Pro:mDAnalysis$ 
—
Regards,

Taushif Khan
Ph.D.
Post-Doctoral Research,
Inter university Institute of Bioinformatics in Brussels (IB-Square),
Brussels, Belgium

**Comment by hainm** [comment]
I am confused. In this command:

```
(test) taushif@taushifs-MacBook-Pro:mDAnalysis$ python -c 'import pytraj'
(test) taushif@taushifs-MacBook-Pro:mDAnalysis$
```

you are clearly can import pytraj without error.

**Comment by hainm** [comment]
What's the output of 

```
ls /Users/taushif/miniconda2/lib/
```

**Comment by taushifkhan** [comment]
I was also wondering
It says it has been installed but while i am testing inside a code it giving error
—
Regards,

Taushif Khan
Ph.D.
Post-Doctoral Research,
Inter university Institute of Bioinformatics in Brussels (IB-Square),
Brussels, Belgium

**Comment by hainm** [comment]
I don't think you install ambertools in your env. If you did, there should be "libsander.dylib" in that lib/ folder. 

Which conda evironment you are using to install, the default

`/Users/taushif/miniconda2`

or the `test' env?

`/Users/taushif/miniconda2/envs/test/`

**Comment by hainm** [comment]
Please just stick with one python version, one environment, one terminal for easy debug. You kept switching python 2.7, python 3.6 and reporting both.

**Comment by hainm** [comment]
I just publish v2.0.2 that includes libetncdf.

```bash
pip install pytraj --upgrade
``` 

Hopefully this will help your case.
