### ISSUE TITLE
cannot calculate SASA using molsurf

### ISSUE THREAD

**Issue by whitleyo** [Amber-MD/pytraj#1407]
For some odd reason, with molsurf I can calculate accessible surface area from a trajectory object loaded from an mdcrd file, but not from a trajectory object made by loading a pdb generated from that same mdcrd file (via loading the mdcrd file into pytraj as a trajectory object, then writing the trajectory object to a pdb).
 
here's what I've gotten from experimenting in ipython

In [19]: traj = pt.load('5q0k_md1_238_B_nvl_prod_md1_prepped.pdb')

In [20]: traj_mdcrd = pt.load('../mdcrd_for_anal/5q0k_md1_238_B_nvl_prod_md1.mdcrd', top = '../5q0k_md1_238_B_nvl.prmtop', mask = '!:WAT,CL-,Na+', frame_indices = [49])

In [21]: traj
Out[21]: 
pytraj.Trajectory, 1 frames: 
Size: 0.000089 (GB)
<Topology: 4000 atoms, 244 residues, 2 mols, PBC with box type = ortho>
           

In [22]: traj_mdcrd
Out[22]: 
pytraj.Trajectory, 1 frames: 
Size: 0.000089 (GB)
<Topology: 4000 atoms, 244 residues, 2 mols, PBC with box type = ortho>
           

In [23]: pt.molsurf(traj)
Out[23]: array([-1.])

In [24]: pt.molsurf(traj_mdcrd)
Out[24]: array([ 12305.01828854])

**Comment by hainm** [comment]
hi,

can you try cpptraj?

```python
command = """
parm 5q0k_md1_238_B_nvl_prod_md1_prepped.pdb
trajin 5q0k_md1_238_B_nvl_prod_md1_prepped.pdb
molsurf !:WAT,CL-,Na+
"""

state = pytraj.load_cpptraj_state(command)
state.run()

print(state.data[-1].to_dict())
```

My guess is that pdb file does not atomic radii.

**Comment by hainm** [comment]
cc @drroe

**Comment by hainm** [comment]
should work if provide radii information via topology.

```python
traj = pt.load('5q0k_md1_238_B_nvl_prod_md1_prepped.pdb',  
               top = '../5q0k_md1_238_B_nvl.prmtop')
```

**Comment by whitleyo** [comment]
Hello, turns out that creating the trajectory with the correct topology provided results in a trajectory that molsurf can use.

I ended up having to create another topology file without water or ions, since the pdb file was created by loading the mdcrd as a trajectory (with mask = '!:WAT, CL-, NA+', frame_indices = [last_frame]), then writing that trajectory to the pdb.

**Comment by hainm** [comment]
Cool.

Tips: traj.top.save will do the work.
