### ISSUE TITLE
pytraj load does not properly filter by mask for pdb file

### ISSUE THREAD

**Issue by whitleyo** [Amber-MD/pytraj#1414]
Hello,

I've been trying to use openmm for MD simulations, and when I try loading an openmm generated pdb file into pytraj, if I specify '!:WAT,CL-,Na+' as a mask, those residues are not removed.

Example:

traj2 = pt.load('test_omm_heat_solv_equil1.pdb', mask = '!:WAT,CL-,Na+')

traj2
Out[37]: 
pytraj.Trajectory, 10 frames: 
Size: 0.005610 (GB)
<Topology: 25098 atoms, 7864 residues, 7751 mols, PBC with box type = ortho>

There are 115 residues in my protein, and ideally there should only be 1 molecule. It should be noted that I generated the pdb file by loading tleap generated amber crd and amber prmtop files into an openmm simulation, via the general paradigm:

prmtop = app.AmberPrmtopFile('input.prmtop')
inpcrd = app.AmberInpcrdFile('input.inpcrd')

The water and ions are within the inpcrd and prmtop files generated by tleap.

Thanks for any input as to what might be going on.

**Comment by hainm** [comment]
hi,  might be a bug

can you try

```python
traj2 = pt.load('test_omm_heat_solv_equil1.pdb')
mask = '!:WAT,CL-,Na+'
traj3 = traj2[mask] # create new trajectory with given mask

# Or
traj2.strip(':WAT,Cl-,Na+') # striping based on mask and updated coordinates.
```

**Comment by hainm** [comment]
try to get resname

```python
set(res.name for res in traj.top.residue) # not remember exact syntax right now.
```

**Comment by hainm** [comment]
I also suspect that openmm does not respect amber resname when writing pdb.

**Comment by hainm** [comment]
Just tried with [tz2.pdb](https://raw.githubusercontent.com/Amber-MD/pytraj/master/tests/data/tz2.pdb)

```python
In [8]: traj = pt.load('./tz2.pdb')

In [9]: 'WAT' in set(res.name for res in traj.top.residues)
Out[9]: True

In [10]: traj2 = pt.load('./tz2.pdb', mask='!:WAT')

In [11]: 'WAT' in set(res.name for res in traj2.top.residues)
Out[11]: False
```

Likely that my suspect is right

> I also suspect that openmm does not respect amber resname when writing pdb.

**Comment by hainm** [comment]
It's been a while and have not heard from you yet, so I am assuming things are fine. Do feel free to reopen.
