### ISSUE TITLE
Save a "cpptraj.log" when running cpptraj’s batch mode in pytraj¶

### ISSUE THREAD

**Issue by ZiadaSo** [Amber-MD/pytraj#1435]
Hi, 
I was wondering if there was a way to get a log file when running cpptraj command in pytraj using CpptrajState  (such as cpptraj.log when running cpptraj command).
Thank you. 

Sonia.

**Comment by hainm** [comment]
hi @ZiadaSo 

I don't think pytraj will support this feature. But you can use the private method in pytraj (`pytraj._verbose()`) for turning on the cpptraj log to stdout:

```bash
$ cat your.py
import pytraj as pt

pt._verbose()
traj = pt.iterload('tz2.ortho.nc', 'tz2.ortho.parm7')
state = pt.load_cpptraj_state('''
    volume''', traj)
state.run()
print(state.data[-1].to_dict())
```

turn off: `pytraj._verbose(False)`

Attached file is example of the log file:

[your.txt](https://github.com/Amber-MD/pytraj/files/1629988/your.txt)

**Comment by ZiadaSo** [comment]
Hi,

Thank you very much for your reply.
