### ISSUE TITLE
update volmap due to change in cpptraj

### ISSUE THREAD

**Issue by hainm** [Amber-MD/pytraj#1438]
https://github.com/Amber-MD/cpptraj/pull/572
<img width="860" alt="screen shot 2018-01-12 at 12 07 31 am" src="https://user-images.githubusercontent.com/4451957/34860599-9ce98d02-f72c-11e7-8f6c-ca8fe92891a9.png">

https://travis-ci.org/Amber-MD/pytraj/builds/327976419

**Comment by drroe** [comment]
Oh, is this because volmap produces an additional dataset now?

**Comment by hainm** [comment]
Yeah I guess so (have not investigated yet). Or may be the unittest in pytraj is not that good.

**Comment by hainm** [comment]
I see. cpptraj adds total volume to data set.

**Comment by hainm** [comment]
fix in #1439
