### ISSUE TITLE
Version 2.0.3 installation fails on pip

### ISSUE THREAD

**Issue by Olllom** [Amber-MD/pytraj#1450]
Hi, 

I noticed that installing pytraj 2.0.3 through pip throws an error
```
    Complete output from command python setup.py egg_info:
    sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
    Original compiler envs
    CXX =
    CC =
    COMPILER =
    use_pip = True, cpptraj_home =
    Detected use of pip; you must set CPPTRAJHOME if there is no cpptraj in the current folder
```
Is this the desired behavior?

If you want to reproduce the error:

```
conda create --name pytraj203 python=3.5
source activate pytraj203
pip install --user  pytraj==2.0.3
```

The following versions were used:
 - setuptools-39.0.1    
 - python-3.5.5      
 - wheel-0.31.0   
 - pip-9.0.3

**Comment by hainm** [comment]
let this open until I fix.

**Comment by hainm** [comment]
hi @Olllom, please try again. The pytraj for python 3.5 is uploaded. Cheers
https://pypi.org/project/pytraj/#files

**Comment by Olllom** [comment]
Great! It works. 
Thank you.

**Comment by francescalb** [comment]
Hi, i hvae the same problem. I have made a new python environment (python3.7) separate from the amber installation and wish to add pytraj here. How can I point to the correct folder for cpptraj?

**Comment by hainm** [comment]
Do you mean to install from source code? There is no binary distribution
for python 3.7 yet.

For source code compilation, just git clone pytraj repo and “python
setup.py install”, pytraj will handle cpptraj for you.

Hai

**Comment by francescalb** [comment]
Thank you. I thought a flag could be set in some way for pip, but installation from source worked perfectly.

**Comment by Manish315** [comment]
I was having the same error as **francescalb**   i:e I have made a new python environment (python3.7) separate from the amber installation and wish to add pytraj here. Then I i followed the installation method given in "From source code (hard way - expert only)" from https://amber-md.github.io/pytraj/latest/installation.html.

_git clone https://github.com/Amber-MD/cpptraj
cd cpptraj
bash configure -shared -openmp -amberlib gnu
make libcpptraj -j4  # this showed several warnings but was completed successfully.
export CPPTRAJHOME=`pwd`_

then when I go to python and try to import pytraj, it shows the following error:

_File "/home/waj/share/amber18/lib/python2.7/site-packages/pytraj-2.0.5-py2.7-linux-x86_64.egg/pytraj/__init__.py", line 24, in <module>
    from .utils.misc import info
  File "/home/waj/share/amber18/lib/python2.7/site-packages/pytraj-2.0.5-py2.7-linux-x86_64.egg/pytraj/utils/misc.py", line 7, in <module>
    from pytraj.core.c_options import set_world_silent
  File "/home/waj/share/amber18/lib/python2.7/site-packages/pytraj-2.0.5-py2.7-linux-x86_64.egg/pytraj/core/__init__.py", line 2, in <module>
    from .topology_objects import Atom, Residue, Molecule
ImportError: dynamic module does not define module export function (PyInit_topology_objects)_

From what I see in the error message, I am able to guess that when I import pytraj it is still calling the old version of python 2.7 where amber18 was installed. Where as, I have the new pytraj in the following directory:
_/home/karplus/anaconda3/lib/python3.7/site-packages/pytraj-2.0.5.dev0-py3.7-linux-x86_64.egg_

Can someone please help me out?

Thanks
Manish

**Comment by hainm** [comment]
hi @Manish315: The error means that the pytraj (python 2.7) is still in PYTHONPATH in your python 3.7 environment. If that happened,  I guess you did `source amber.sh` (or so on) in your .bashrc (for example) so it will be auto-executed. 

Can you please `echo $PYHONPATH` to doublecheck and might then do `export PYTHONPATH=""` to exclude the python 2.7 path? cheers.

**Comment by Manish315** [comment]
It worked out. Earlier it was linking to my python 2.7 PYTHONPATH. After exporting the new PYTHONPATH in bashrc, pytraj is working fine.

Thanks for your quick response.

**Comment by hainm** [comment]
great.

**Comment by Juliyan96** [comment]
I am also face with the same situation and I have added the amber.sh to the .bashrc script. Should I be changing the PYTHONPATH in the amber.sh or in a separate line in the .bashrc file? And what should be the end folder for the PYTHONPATH if I'm changing it to Python version 3.4 from 2.7?
