### ISSUE TITLE
pytraj.pca uses excessive memory

### ISSUE THREAD

**Issue by tuckerburgin** [Amber-MD/pytraj#1451]
This is an issue that I suspect is more to do with my ineptitude than with an actual bug or flaw in the code.

I am interested in running a principle component analysis on a relatively short trajectory (hundreds of frames):

```
traj = pytraj.load('my_traj.nc','my_prmtop')
pca_data = pytraj.pca(traj,mask='!@H=',n_vecs=2)
```

Whenever I attempt this, however, all 16 GB of my machine's RAM are quickly consumed and the computation stalls. In order to debug I have attempted to perform the analysis on just one frame, and have verified that the trajectory object is tiny:

```
> traj = pytraj.io.load('different_traj.nc','different_prmtop',frame_indices=range(0, 1, 1))
> traj
pytraj.Trajectory, 1 frames: 
Size: 0.001379 (GB)
<Topology: 61680 atoms, 18601 residues, 18161 mols, PBC with box type = ortho>
```

But the problem persists. In fact, I am unable even to run this analysis on an HPC cluster with 40 GB of memory assigned (the batch system complains of too much memory usage.) Attempts with even more memory are currently pending, but surely this should not be necessary! I am using pytraj version 2.02.

---

I am aware that pytraj's pca implementation is designed to echo the implementation in cpptraj:

```
# Step one. Generate average structure.
# RMS-Fit to first frame to remove global translation/rotation.
parm myparm.parm7
trajin mytraj.nc
rms first !@H=
average crdset AVG
run
# Step two. RMS-Fit to average structure. Calculate covariance matrix.
# Save the fit coordinates.
rms ref AVG !@H=
matrix covar name MyMatrix !@H=
createcrd CRD1
run
# Step three. Diagonalize matrix.
runanalysis diagmatrix MyMatrix vecs 2 name MyEvecs
# Step four. Project saved fit coordinates along eigenvectors 1 and 2
crdaction CRD1 projection evecs MyEvecs !@H= out project.dat beg 1 end 2
```

I have attempted to use this option as well, but I get similar issues; depending on the environment in which I run cpptraj, I am either unable to start the "matrix" step due to insufficient memory, or else it begins and then segfaults. I am using cpptraj version 16.16.

---

What's the remedy here? Please let me know if there is any more information I can provide.

**Comment by hainm** [comment]
@drroe Do you have any comment here? Seems like cpptraj issue?

**Comment by drroe** [comment]
What is the size of `my_traj.nc`? The `createcrd` command is saving the trajectory to memory, and since you're not doing any stripping of coordinates the entire thing has to fit in memory. If it's a large trajectory (i.e. bigger than your available memory) you have to either 1) strip it down so it fits (so in your case strip all hydrogens - if there are waters you probably want to strip those as well) or 2) keep the trajectory on-disk and run in two passes. The thing to keep in mind with 2) is that you need to make sure the input trajectory is processed the same way when projecting the coordinates as when generating the covariance matrix, e.g.
```
# Step one. Generate average structure.
# RMS-Fit to first frame to remove global translation/rotation.
parm myparm.parm7
trajin mytraj.nc
rms first !@H=
average crdset AVG
run
# Step two. RMS-Fit to average structure. Calculate covariance matrix.
rms ref AVG !@H=
matrix covar name MyMatrix !@H=
run
# Step three. Diagonalize matrix.
runanalysis diagmatrix MyMatrix vecs 2 name MyEvecs
# Step four. Project saved fit coordinates along eigenvectors 1 and 2
# Note that we must RMS-fit the input trajectory the same as when
# generating the covariance matrix.
rms ref AVG !@H=
projection evecs MyEvecs !@H= out project.dat beg 1 end 2
run
```

**Comment by tuckerburgin** [comment]
Ah -- ineptitude confirmed!! How could I forget to strip out the waters first. I have done so now and the calculation is proceeding. I also realize now that I forgot to tell the software that I'm actually looking for the by-residue correlation, which obviously reduces the problem size dramatically.

Thank you for your helpful comment!

**Comment by hainm** [comment]
> 2) keep the trajectory on-disk and run in two passes.

Equal to pytraj: is to use `iterload` method
```
traj = pt.iterload(...)
pt.pca(traj, ...)
```

**Comment by hainm** [comment]
oh, I am sorry. That's true. :(

**Comment by hainm** [comment]
@tuckerburgin  ha, turns out that we support lazy trajectory in latest pytraj (2.0.3)

```
In [6]: import pytraj

In [7]: traj = pytraj.iterload('tz2.nc', 'tz2.parm7')

In [8]: pca_data = pytraj.pca(traj,mask='!@H=',n_vecs=2)

In [9]: pca_data
Out[9]: 
(array([[ -4.93425131, -13.80002308, -20.61605835, ...,  57.92280579,
          61.25728607,  52.85142136],
        [ -4.03333616,   6.9132452 ,  14.53991318, ...,   6.757936  ,
          -2.1086719 ,   3.60922861]], dtype=float32),
 (array([ 1399.36472919,   240.42342439]),
  array([[-0.00251526, -0.0405033 ,  0.0084492 , ..., -0.04534061,
           0.09515649,  0.0475896 ],
         [-0.0313375 , -0.12882763,  0.02338202, ...,  0.00380469,
           0.04104856,  0.04230317]])))

In [10]: pt.__version__
Out[10]: '2.0.3'
```
