### ISSUE TITLE
Write trajectory methods with time support in netcdf format

### ISSUE THREAD

**Issue by pindakaas42** [Amber-MD/pytraj#1455]
Using the pytraj methods to write trajectories in the .nc format will remove all times, especially since pytraj includes times when reading .nc trajectoreis generated with AMBER16 it would  be really useful wo keep them. This is hopefully easy to fix as it probably is just the cpptraj option notime being set to True by default, which is not very useful. Would be very helpful. Thanks

**Comment by hainm** [comment]
thanks. I will have a look.

**Comment by hainm** [comment]
@pindakaas42  should be done now in #1456 , please check the master branch. Cheers.
