### ISSUE TITLE
Explained Variance for PCA

### ISSUE THREAD

**Issue by lacoperon** [Amber-MD/pytraj#1457]
Hi there,

I found myself (for some MD calculations) implementing mostly trivial code which calculates the proportion of the variance explained by each principal component derived from pytraj's PCA function. 

Given that this is a common use case (and that some might find it hard to translate eigenvalue terminology to variance numerically), would it be worthwhile implementing this as a function within pytraj? I could very easily do a quick efficient version of this using numpy and do a pull request -- just was wondering whether or not it would be worthwhile.

Thanks,
 Elliot

**Comment by hainm** [comment]
> I could very easily do a quick efficient version of this using numpy and do a pull request -- just was wondering whether or not it would be worthwhile.

Yes, go head to make a PR for it. The code should have unittest too. Thanks and cheers.

**Comment by hainm** [comment]
it's been a while and there is no progress so I close this case. thanks.
