### ISSUE TITLE
PyPI/Conda binaries incompatible with recent glibc versions?

### ISSUE THREAD

**Issue by Olllom** [Amber-MD/pytraj#1459]
We are having trouble installing pytraj (2.0.3) on recent Ubuntu versions (18.0.4).

```
ImportError while importing test module '/home/ubuntu/coffe-master/tests/misc/test_mk_torsion_conformers.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/misc/test_mk_torsion_conformers.py:8: in <module>
    from coffe.analysis import pdb_reader
coffe/analysis/pdb_reader.py:12: in <module>
    import pytraj as pt
../.local/lib/python2.7/site-packages/pytraj-2.0.3-py2.7-linux-x86_64.egg/pytraj/__init__.py:24: in <module>
    from .utils.misc import info
../.local/lib/python2.7/site-packages/pytraj-2.0.3-py2.7-linux-x86_64.egg/pytraj/utils/misc.py:7: in <module>
    from pytraj.core.c_options import set_world_silent
../.local/lib/python2.7/site-packages/pytraj-2.0.3-py2.7-linux-x86_64.egg/pytraj/core/__init__.py:2: in <module>
    from .topology_objects import Atom, Residue, Molecule
E   ImportError: /home/ubuntu/.local/lib/python2.7/site-packages/pytraj-2.0.3-py2.7-linux-x86_64.egg/pytraj/core/../.libs/libresolv-2-c4c53def.5.so: symbol __res_maybe_init version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
```

As far as I understand this, the binaries were compiled using glibc < 2.26, while Ubuntu 18.0.4, by default, comes with glibc 2.27. 

`ldd Version:ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27`
https://sourceware.org/glibc/wiki/Release/2.26#Removal_of_.27xlocale.h.27

Or am I missing something?
Do you see any way to fix this, other than manually downgrading glibc on my system?

**Comment by hainm** [comment]
Hi,

I saw that error before, may be it's due to recent change in auditwheel (I don't know why/how) that was used to make compatible linux distro.

Would you please try to uninstall pytraj and install ambertools that includes pytraj?

```
conda install ambertools=18 -c http://ambermd.org/downloads/ambertools/conda/
```

In this version, we don't use auditwheel. 
Thanks.

**Comment by hainm** [comment]
>  may be it's due to recent change in auditwheel (I don't know why/how) 

Corrected: May be I used out-dated version of auditwheel to fix the binary.

**Comment by Olllom** [comment]
Thanks for the solution.

Are you still going to fix the distributed binaries using a more recent version of auditwheel?

**Comment by hainm** [comment]
> Are you still going to fix the distributed binaries using a more recent version of auditwheel?

hi, that's my guess but the error might due to the docker image I used to build pytraj. The image is based on the one from manylinux (https://github.com/pypa/manylinux#docker-images).
We used centos 5 image to build ambertools.

I will definitely fix the error but I am not sure I can make it happen soon. For now, please use ambertools. Thanks.

**Comment by ehashman** [comment]
Hello! I'm one of the auditwheel maintainers.

The removal of `xlocale.h` is a red herring---that would only pose an issue at build time. If you're ever curious whether a system library affects a binary wheel's compatibility, [here are all the whitelisted libraries](https://www.python.org/dev/peps/pep-0513/#the-manylinux1-policy) according to manylinux1 policy.

What the error above means is that a symbol, `__res_maybe_init`, was referenced by the library `libresolv-2-c4c53def.5.so` with version `GLIBC_PRIVATE`, but couldn't be found. The `GLIBC_PRIVATE` version means that this symbol is not part of GLIBC's public ABI and that its implementation is unstable: it can change between versions of libc. `GLIBC_PRIVATE` versions are not permitted in `manylinux` policy.

I believe this is an issue with `libresolv-2.so` referencing that symbol when they shouldn't, and an auditwheel update would not fix this. I recommend you report a bug against the libresolv maintainers. (Let me know if you need help with that.)

**Comment by ppxasjsm** [comment]
Is there any progress on this? I am running into the same problem, but can't really use ambertools as a solution.

**Comment by hainm** [comment]
Hi, there is no progress yet.
Why can’t you use ambertools? It’s just ‘conda install’

Hai

**Comment by karlkirschner** [comment]
Hi,
  I just installed ambertools18 using the above conda commands, but pytraj was not included in the bin directory.
Bests,
Karl

**Comment by hainm** [comment]
Dear @Olllom, please try again with pytraj v2.0.4 via `pip install pytraj==2.0.4`. Should work now. 
https://github.com/Amber-MD/pytraj/issues/1464#issuecomment-478210141
