### ISSUE TITLE
Suppress internal errors?

### ISSUE THREAD

**Issue by CheckerBored** [Amber-MD/pytraj#1460]
This is a minor, quality-of-life-type question.

I have a process flow where I want to programmatically call `pytraj.iterload()` on a list of trajectory files and, if they have a non-zero number of frames, do something with them. This is working fine, but whenever iterload encounters a file that does have zero frames, it reports an internal error into my stdout:

`Error: Could not set up <traj> for reading.`
`Error: Could not set up trajectory '<traj>'`
`Error: NetCDF file has no frames.`

I can catch this error by simply checking if the iterload object exists after I attempt to create it, but I haven't found a way to suppress the internal error, which is cluttering my output stream. Does such an option exist? For portability, I would like to avoid making any changes to the pytraj code directly.

Thank you!

**Comment by hainm** [comment]
hi, there is no way to suppress the error and I think it's intention. You need to check if your trajectory is valid like you're doing (or you can use netcdf library to check the frame). Cheers.

**Comment by CheckerBored** [comment]
Understood, and thanks for the suggestion re: the netcdf library!
