### ISSUE TITLE
Please upgrade auditwheel to 1.9

### ISSUE THREAD

**Issue by ehashman** [Amber-MD/pytraj#1464]
It looks like auditwheel was pinned a little over a year ago and hasn't been updated. Would you mind bumping the version to 1.9.0 and seeing if that works?

Thanks!

**Comment by hainm** [comment]
thanks @ehashman. I will test that.

**Comment by dprada** [comment]
Hi!
I tried to overcome the problem with auditwheel installing ambertools 18 with conda. But then I realized that I have to downgrade the environment from Python 3.7 to 3.6. Having a conda package built to be used with Python 3.7 would be great.
Thanks in advance for considering this suggestion.

**Comment by hainm** [comment]
thanks. I will work on that.

**Comment by slochower** [comment]
Hi @hainm , I'm not sure that I'm being blocked by the same dependency, but I also can't get `pytraj` to run on a Travis Python 3.7 environment. Do you have a rough estimate of when you think a 3.7-compatible version will be ready? 

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - python=3.7
  - pytraj -> python=3.6
Use "conda search <package> --info" to see the dependencies for each package.
```

**Comment by hainm** [comment]
hi @slochower, both pytraj and ambertools 18 were released before python 3.7 so there are no 3.7 versions yet

> Edit: I am installing `ambertools` from `http://ambermd.org/downloads/ambertools/conda/` channel and `pytraj` from `ambermd`. Is there a better way to do this?

pytraj is already included in ambertools (official release hosted in amber server), so you don't need to install pytraj from `ambermd` channel in anaconda server. Sorry for the confusion.

> Do you have a rough estimate of when you think a 3.7-compatible version will be ready?
it's pretty easy to get this done on Linux but I got some header file missing issue with new MacOS update. Do you only need 3.7 for Linux?

**Comment by slochower** [comment]
> hi @slochower, both pytraj and ambertools 18 were released before python 3.7 so there are no 3.7 versions yet

Got it.

> pytraj is already included in ambertools (official release hosted in amber server), so you don't need to install pytraj from `ambermd` channel in anaconda server. Sorry for the confusion.

To be clear, are you saying that I should be able to install both `ambertools` and `pytraj` from the  `http://ambermd.org/downloads/ambertools/conda/` channel?

```
$ conda install pytraj -c http://ambermd.org/downloads/ambertools/conda/
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pytraj
```

> it's pretty easy to get this done on Linux but I got some header file missing issue with new MacOS update. Do you only need 3.7 for Linux?

I think both would be ideal, but Linux support would definitely be welcome :) I personally am not using any Python 3.7 features, but I'm migrating one of my repositories to the [MolSSI cookiecutter](https://github.com/molssi/cookiecutter-cms) that includes MacOS and Linux Python 3.7 builds on Travis.

**Comment by dprada** [comment]
> > it's pretty easy to get this done on Linux but I got some header file missing issue with new MacOS update. Do you only need 3.7 for Linux?

Thumbs up.

**Comment by hainm** [comment]
> To be clear, are you saying that I should be able to install both `ambertools` and `pytraj` from the `http://ambermd.org/downloads/ambertools/conda/` channel?

No. I meant you can just install ambertools from that channel since it already has pytraj. There is no pytraj standalone install in that channel. :D 

I personally prefer to install pytraj via pip since it's super quick to do that (it takes time for conda to resolve the conflicting recently).

> but I'm migrating one of my repositories to the [MolSSI cookiecutter](https://github.com/molssi/cookiecutter-cms) that includes MacOS and Linux Python 3.7 builds on Travis.

I see.

PS: Since there are several request for ambertools 3.7 (e.g: https://github.com/openforcefield/openforcefield/issues/153#issue-394092437), I will try to make it happen asap. cheers.

**Comment by hainm** [comment]
Dear all, I am sorry for the long delay. I am finally done with few things
- Upgrade auditwheel to v2.0 that makes pytraj work with `Ubuntu 18.04`
- Support python 3.7 (only available via `pip install` or macOS conda; drop support for python 3.4.
    - Due to some compiling issues with conda, python 3.5 release for MacOS is only available via `pip install`.
- Release pytraj v2.0.4 (will be soon released in AmberTools 19 too). It should be available in `ambermd` conda channel or in pypi (pip install).

Please let me know if there's any unresolved issue. Thanks.

```
root@6696a5051e30:/work# cat /etc/os-release  |grep VERSION
VERSION="18.04.2 LTS (Bionic Beaver)"
VERSION_ID="18.04"
VERSION_CODENAME=bionic

root@6696a5051e30:/work# /root/miniconda3/bin/python 
Python 3.7.1 (default, Dec 14 2018, 19:28:38) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytraj as pt
p>>> pt.__version__
'2.0.4'
>>> traj = pt.datafiles.load_tz2()
>>> pt.rmsd(traj, mask='@CA', ref=0)
array([1.94667955e-07, 2.54596866e+00, 4.22333034e+00, ...,
       4.97189564e+00, 5.53947712e+00, 4.83201237e+00])
```

**Comment by hainm** [comment]
In short, I recommend to install `pytraj v2.0.4` via `pip install` (thanks to the amazing work from `auditwheel` folks.

**Comment by dprada** [comment]
Thanks!
