### ISSUE TITLE
More Explicit RMSD Documentation

### ISSUE THREAD

**Issue by RMeli** [Amber-MD/pytraj#1467]
It is not entirely clear from the documentation that `rmsd()` and `symmrmsd()` need the atoms in the same order for the reference structure and the trajectory. If the atoms are not in the same order, the RMSD is computed without warnings/error, but the result is obviously wrong.

I suggest to make this clearer in the documentation or to add a check to verify that the atoms are provided in the same order for both the reference structure and the trajectory.

**Comment by hainm** [comment]
@drroe: what do you think?

**Comment by RMeli** [comment]
To clarify, the following code gives a non-zero RMSD
```
import pytraj as pt

a = pt.iterload("benzene.pdb")
b = pt.iterload("benzene_HC.pdb")

rmsd = pt.symmrmsd(traj=a, ref=b)
print(rmsd)
```
with the following two PDB files for benzene:
```
TITLE     benzene.pdb
CRYST1    0.000    0.000    0.000   0.00   0.00   0.00 P 1           1
ATOM      1  H   UNK S   1       0.000   2.486   0.000  1.00  0.00      SYST H
ATOM      2  C   UNK S   1       0.000   1.391   0.000  1.00  0.00      SYST C
ATOM      3  H   UNK S   1      -2.153   1.243   0.000  1.00  0.00      SYST H
ATOM      4  C   UNK S   1      -1.205   0.696   0.000  1.00  0.00      SYST C
ATOM      5  H   UNK S   1      -2.153  -1.243   0.000  1.00  0.00      SYST H
ATOM      6  C   UNK S   1      -1.205  -0.696   0.000  1.00  0.00      SYST C
ATOM      7  H   UNK S   1      -0.000  -2.486   0.000  1.00  0.00      SYST H
ATOM      8  C   UNK S   1      -0.000  -1.391   0.000  1.00  0.00      SYST C
ATOM      9  H   UNK S   1       2.153  -1.243   0.000  1.00  0.00      SYST H
ATOM     10  C   UNK S   1       1.205  -0.696   0.000  1.00  0.00      SYST C
ATOM     11  H   UNK S   1       2.153   1.243   0.000  1.00  0.00      SYST H
ATOM     12  C   UNK S   1       1.205   0.696   0.000  1.00  0.00      SYST C
END
```
```
TITLE     benzene_HC.pdb
CRYST1    0.000    0.000    0.000   0.00   0.00   0.00 P 1           1
ATOM      1  H   UNK S   1       0.000   2.486   0.000  1.00  0.00      SYST H
ATOM      2  H   UNK S   1      -2.153   1.243   0.000  1.00  0.00      SYST H
ATOM      3  H   UNK S   1      -2.153  -1.243   0.000  1.00  0.00      SYST H
ATOM      4  H   UNK S   1      -0.000  -2.486   0.000  1.00  0.00      SYST H
ATOM      5  H   UNK S   1       2.153  -1.243   0.000  1.00  0.00      SYST H
ATOM      6  H   UNK S   1       2.153   1.243   0.000  1.00  0.00      SYST H
ATOM      7  C   UNK S   1       1.205   0.696   0.000  1.00  0.00      SYST C
ATOM      8  C   UNK S   1       0.000   1.391   0.000  1.00  0.00      SYST C
ATOM      9  C   UNK S   1      -1.205   0.696   0.000  1.00  0.00      SYST C
ATOM     10  C   UNK S   1      -1.205  -0.696   0.000  1.00  0.00      SYST C
ATOM     11  C   UNK S   1      -0.000  -1.391   0.000  1.00  0.00      SYST C
ATOM     12  C   UNK S   1       1.205  -0.696   0.000  1.00  0.00      SYST C
END
```

**Comment by hainm** [comment]
thanks @RMeli, I've opened a new issue in cpptraj repo to see if warning/error should be raised: https://github.com/Amber-MD/cpptraj/issues/667

**Comment by drroe** [comment]
> It is not entirely clear from the documentation that `rmsd()` and `symmrmsd()` need the atoms in the same order for the reference structure and the trajectory.

This is omitted from the manual because as far as I know most major analysis tools that calculate RMSD between a target and reference require this. In every definition of RMSD (or RMSE) that I have seen, the difference is taken between a reference and target element with the same subscript.

However, there is no harm in making the documentation more explicit. In addition, users can make use of the `atommap` command prior to `rmsd` to attempt to reorder the target atoms in the proper way. In fact, there is an `rmsfit` keyword for `atommap` precisely because this was an issue I encountered a long time ago when I was doing a docking study.

**Comment by RMeli** [comment]
Yes, I completely understand but it took me a while to realize the problem.  I didn't come across `atom_map`, thank you very much for mentioning this.

It would definitely be helpful to have it mentioned in the documentation (and possibly link to `atom_map`). I can try to do it and open a PR, or let you experts handle it (if agreed).

I'm doing some docking studies as well and some software change the order of atoms in the output ligands compared to the input (or reference) ligand.

**Comment by hainm** [comment]
Hi Rocco,

PR is always welcome.

Cheers
