### ISSUE TITLE
Pytraj needs to handle new disk-cached data sets (CPPTRAJ)

### ISSUE THREAD

**Issue by drroe** [Amber-MD/pytraj#1478]
See related CPPTRAJ pull request [here](https://github.com/Amber-MD/cpptraj/pull/641). DataSet_integer is now a base class for an integer data set that can either be in memory (DataSet_integer_mem) or on disk via NetCDF (DataSet_integer_disk).

**Comment by hainm** [comment]
I will address this. Thanks.

**Comment by hainm** [comment]
@drroe  When you make a PR to gitlab for cpptraj, please also include pytraj since pytraj depends on it.

**Comment by drroe** [comment]
OK - I'll make sure I update both subtrees. Thanks Hai!

**Comment by hainm** [comment]
Thanks Dan.
