### ISSUE TITLE
A question about superpose function of pytraj

### ISSUE THREAD

**Issue by Juanrong** [Amber-MD/pytraj#1484]
I am trying to align a trajectory to the crystal structure which has the same prmtop file with that trajectory. I only want to use a part of CA as the criterion for alignment. So I use pytraj.superpose(traj,ref,ref_mask). I found when I use all CA as ref_mask it worked well (ref_mask="@CA"). When I want to use the CA of first 200 residues, the result was not correct by using ref_mask=":1-200@CA". Could you tell me how I should set up ref_mask if I want to do this (only use CA of the first 200 residues)?

**Comment by hainm** [comment]
hi, your syntax seems correct to me. Can you please elaborate how the result was not correct? thanks.

**Comment by hainm** [comment]
oh, I think you should just
```
pt.superpose(traj, mask=':1-200@CA')
```

`ref_mask` is only useful if you want to align two different sets of atoms from `traj` and from the reference structure.

**Comment by Juanrong** [comment]
Thank you. The result was correct by using
 pt.superpose(traj, mask=':1-200@CA')

From your explanation about ref_mask, do I need mask and ref_mask to define that two different sets of atoms if want to to align two different sets of atoms from a trajectory and from the reference structure?

**Comment by hainm** [comment]
> From your explanation about ref_mask, do I need mask and ref_mask to define that two different sets of atoms if want to to align two different sets of atoms from a trajectory and from the reference structure?

yeah, you have too. If you only specify `mask`, the `ref_mask` will be the same as `mask` unless you explicitly set it.
One useful case:

```python
ref = pt.load([your reference]) # load some structure with missing atoms 
traj = pt.load([your traj])

pt.superpose(traj, mask=':1-10@CA', ref=ref, ref_mask=':10-20@CA')
```

**Comment by Juanrong** [comment]
Got it. Thank you so much.

**Comment by hainm** [comment]
great.
