### ISSUE TITLE
Segmentation fault when loading trajectory without mask

### ISSUE THREAD

**Issue by RMeli** [Amber-MD/pytraj#1486]
If I try to load a trajectory without specifying the mask as follows
```python
traj = pt.load("mytraj.nc", "mytop.parm7") # Segfault
```
I get a segmentation fault:
```bash
[1]    29056 segmentation fault (core dumped)  ipython
```

However, if a specify a mask (even an empty one), there is no problem:
```python
traj = pt.load("mytraj.nc", "mytop.parm7", mask="") # OK
```

I'm working with Ubuntu 18 and I installed `pytraj` using `conda` (in a Python 3.6 environment) as follows:
```bash
conda install ambertools=18 -c http://ambermd.org/downloads/ambertools/conda/
```

**Comment by hainm** [comment]
thanks for your report. Can you please try again with the data in pytraj (tz2.nc, tz2.parm7): https://github.com/Amber-MD/pytraj/tree/master/tests/data

**Comment by hainm** [comment]
and does this cause segmentation fault too?
```pyhon
traj = pt.iterload("mytraj.nc", "mytop.parm7")
traj = traj[:]
```

**Comment by RMeli** [comment]
The following
```python
traj = pt.load("tz2.nc", "tz2.parm7") # OK
```
works without segmentation fault, while
```python
traj = pt.iterload("mytraj.nc", "mytop.parm7") # OK
traj = traj[:]  # Segfault
```
fails as before.

**Comment by RMeli** [comment]
Interestingly,
```python
traj = pt.iterload("2boi_n1.nc", "2boi.parm7", mask="") # OK
traj = traj[:] # Segfault
```
fails.

**Comment by hainm** [comment]
is that possible to share your data (one or few frames)? I have never seen the issue before and don't know how to reproduce it.

**Comment by RMeli** [comment]
Yes, but if I load the trajectory with the only working method
```python
traj = pt.load("mytraj.nc", "mytop.parm7", mask="") # OK
```
and then save a few frames as required
```python
pt.save("mytraj_short.nc", traj, frame_indices=[0,1,2,3,4]) # OK
```
everything seems to work fine...
```python
traj = pt.load("mytraj_short.nc", "mytop.parm7") # OK
```

**Comment by hainm** [comment]
ha, that's odd. I bet one of your frames is corrupted.

Can you please try
```
traj = pt.iterload("mytraj.nc", "mytop.parm7")
for index, frame in enumerate(traj):
    print(index, frame) # does segmentation fault happen at specific frame
```

**Comment by RMeli** [comment]
If I try
```python
traj = pt.iterload("mytraj.nc", "mytraj.parm7")
for idx, frame in enumerate(traj):
    print(idx, frame)
```
as suggested, no segmentation fault happens (all the indices are printed and all the frame have the correct number of atoms).

Strangely enough, also saving the whole trajectory from `pytraj` makes the problem disappear:
```python
traj = pt.load("mytraj.nc", "mytop.parm7", mask="") # OK
pt.save("mytraj_pt.nc", traj) # OK (Visualized w/ VMD)
traj_pt = pt.load("mytraj_pt.nc",  "mytop.parm7") # OK
```
The saved trajectory `mytraj_pt.nc` is around half the size of the original one.

I'll quickly confirm I can share the whole trajectory and come back to you, if you don't have any other ideas what this weird problem might be.

**Comment by hainm** [comment]
Just for the record: I just got your files offline and I am investigating this.

**Comment by hainm** [comment]
> The saved trajectory mytraj_pt.nc is around half the size of the original one.

Your trajectory has `force` data and the new one does not (default False for writing force).
I think pytraj does not handle slicing the force array properly (but at least we have some clues now).

**Comment by RMeli** [comment]
Yes, I realized that the fact that the new trajectory was half the size was due to the forces not being saved. Thank you very much for looking into this.

**Comment by hainm** [comment]
should be fixed in #1487

**Comment by hainm** [comment]
thanks @RMeli  for bringing this issue to us.

**Comment by RMeli** [comment]
No, problem. Thank you for taking care of this so quickly!
