### ISSUE TITLE
Distance between atoms in pytraj

### ISSUE THREAD

**Issue by diallobakary4** [Amber-MD/pytraj#1489]
I am trying to compute the distance between some atoms (a MN atom (index 6601) and some other atoms) in a trajectory and find the closest atoms (in a radius of 3 angstroms).  
I am using the [distance function ](https://amber-md.github.io/pytraj/latest/_api/pytraj.all_actions.html#pytraj.all_actions.distance) for that. 
But the resulting distances are not very meaningful. 
In the output the last line makes sense, the distance between MN and itself is zeros.  However, the first line is unexpectedly zeros.  The atoms of residue 409, are simply the last atoms of the chain. When MN is more located in the center.  They are far apart when visualized. 
![image](https://user-images.githubusercontent.com/13533717/60115137-8df32200-9775-11e9-9bd4-af62511b4073.png)
I am a bit confused.

**Comment by drroe** [comment]
Hi,

I'm not as familiar with pytraj syntax so I'm not sure what might be amiss here (although make sure that imaging is not the culprit for shorter-than-expected distances), but I can provide some hopefully useful info from a cpptraj perspective.

If you just need the identity of the atoms you can use the equivalent of the `mask` action of cpptraj (@hainm is the `mask` Action supported by pytraj)?

In cpptraj syntax this would be something like:
```
mask "(@6601 <@ 3.0)" maskout atomsWithin3ofMn.out
```
To print a PDB or mol2 file for each frame with the selected atoms you could use the `maskpdb`/`maskmol2` keywords.

**Comment by hainm** [comment]
hi @diallobakary4  the atom index is 0-based  while the atom mask (string) is 1-based.  So
```
str(e.index) should be str(e.index+1)
@6601 should be @6602
```

Or you can use the array-base syntax
```
pt.distance(traj, [[e.index, 6601]]) # return 2D array because you can provide multiple atom pairs.
```

> @hainm is the mask Action supported by pytraj

@drroe  not conveniently supported but user can use cpptraj's State
```python
In [28]: import pytraj as pt                                                                                                                                                                                       

In [29]: t = pt.datafiles.load_tz2()                                                                                                                                                                               

In [30]: s = pt.load_cpptraj_state(""" 
    ...: mask "(@1 <@ 3.0)" maskout atomsWithin3ofMn.out""", t)                                                                                                                                                    

In [31]: s.run()                                                                                                                                                                                                   
Out[31]: 
CpptrajState, include:
<datasetlist: 1 datasets>

In [32]: !head atomsWithin3ofMn.out                                                                                                                                                                                
#Frame    AtomNum Atom   ResNum  Res   MolNum
       1        1 N           1 SER         1
       1        2 H1          1 SER         1
       1        3 H2          1 SER         1
       1        4 H3          1 SER         1
       1        5 CA          1 SER         1
       1        6 HA          1 SER         1
       1        7 CB          1 SER         1
       1        8 HB2         1 SER         1
       1       10 OG          1 SER         1

```

**Comment by diallobakary4** [comment]
Changing the indices did solve it.
Thank you for your replies.

**Comment by hainm** [comment]
great.
