### ISSUE TITLE
Concatenate trajectories?

### ISSUE THREAD

**Issue by khoroshyy** [Amber-MD/pytraj#1491]
Hi.
I have not  found any mailing list or something similar to ask a question. So I post it here.
I know that I can load multiple files into one trajectory, but in my case it does not work because of memory issues. Can I  concatenate two trajectories?
Load one file into trajectory, strip atoms i do not need.
Load another file into another trajectory, strip unnecessary files.
Concatenate two trajectories.
I may be blind but I was not able to find a command or example to concatenate trajectories.
Thanks.
Petro

**Comment by hainm** [comment]
hi @khoroshyy 

Memory should not be an issue with pytraj if you're using `pytraj.iterload`, which returns an on-disk trajectory. 

```python
traj = pytraj.iterload([list of filenames], top=...)
# create in-memory trajectory
traj2 = traj['!@CA']
```
Let me know if that helps.

**Comment by hainm** [comment]
You can have a look here too: https://amber-md.github.io/pytraj/latest/trajectory.html

**Comment by hainm** [comment]
Alternatively, you can specify the `mask` option

```
pytraj.load([...], top=..., mask='@CA')
```

**Comment by hainm** [comment]
>  example to concatenate trajectories.

But going back to  your original question:
```
import numpy as np
traj.xyz = np.vstack((traj.xyz, traj2.xyz))
# do the same thing for traj.unitcells, traj.velocities,
# traj.forces if they're not None)
# Then you're good to go.
```

**Comment by khoroshyy** [comment]
Thanks.
Iterload does not help me. If I load trajectory using iterload I cannot strip water for example. Mask also does not work with iterload.
The last thing might be the thing I am looking for. But I have not tried it yet.

**Comment by hainm** [comment]
> Iterload does not help me. If I load trajectory using iterload I cannot strip water for example.

have you tried the example in that post yet?
```
# This is one of the ways to "strip`. In this case is to strip non-CA atoms.
traj2 = traj['!@CA']
```

**Comment by hainm** [comment]
I assume your issue is resolved (it not, please reopen it).
