### ISSUE TITLE
cpopvtime is not saving to file

### ISSUE THREAD

**Issue by karlkirschner** [Amber-MD/pytraj#1492]
Hello,

  I am having trouble with the cpopvtime option. When I specify "cpopvtime cpopvtime.agr normframe" in my kmeans cluster, I do not obtain the cpopvtime.agr. No messages are given (ie. no error), so I am not sure what is going on.

  The clustering itself seems to work fine, and all of the other output files are generated. Here is the code that I am using:

cluster_data_ligand = kmeans(protein, mask='!@H*', n_clusters=10,
                      options= 'out cnumvtime.dat \
                      summary cluster_summary.txt \
                      info cluster_info.txt \
                      cpopvtime cpopvtime.agr normframe \
                      clusterout cluster_trj crd \
                      avgout cluster_avg avgfmt pdb \
                      repout cluster_rep repfmt pdb')

I'm using pytraj v. 2.0.3 with python v. 3.6.6. Thanks in advance, and thanks for creating and maintaingin pytraj.
Bests,
Karl

**Comment by hainm** [comment]
hi @karlkirschner, it sounds like a bug in pytraj (it works fine in cpptraj). I will have a look. cheers.

**Comment by hainm** [comment]
hi again, it turns out that the `options` must be a single line (pytraj should handle this better).
Please try again with below example:

```
import pytraj as pt

pt._verbose(True)
protein = pt.datafiles.load_tz2()                                                                                                                                                                            

cluster_data_ligand = pt.cluster.kmeans(protein, mask='!@h*', n_clusters=10, 
options= """out cnumvtime.dat summary cluster_summary.txt info cluster_info.txt cpopvtime cpopvtime.agr normframe clusterout cluster_trj crd  avgout cluster_avg avgfmt pdb repout cluster_rep repfmt pdb""")
print(cluster_data_ligand.summary()) # to get cpptraj output in this case.
```

**Comment by hainm** [comment]
Nevermind, I don't see the " cpopvtime.agr" either. Uhm, let me dig further.

**Comment by hainm** [comment]
I've checked pytraj's code and it turns out that pytraj has not supported writing cpptraj's datafile for clustering yet.

To overcome this, you can either use cpptraj directly, or use pytraj to call cpptraj

```
import pytraj as pt

protein = pt.iterload('tz2.nc', 'tz2.parm7') # Must use `iterload`

pt._verbose(True)
state = pt.load_cpptraj_state(
"""createcrd DEFAULT_NAME
cluster !@h* crdset DEFAULT_NAME kmeans clusters 10 randompoint kseed 1 maxit 100 rms out cnumvtime.dat summary cluster_summary.txt info cluster_info.txt cpopvtime cpopvtime.agr normframe clusterout cluster_trj avgout cluster_avg avgfmt pdb repout cluster_rep repfmt pdb""",
protein)
state.run()
```

**Comment by karlkirschner** [comment]
Hi - thanks for the feedback. It is good to know that I wasn't overlooking
something. I'll modify my jupyter notebook to call cpptraj.
Bests,
Karl

**Comment by drroe** [comment]
@hainm is this something that a code change on the cpptraj side can help facilitate for pytraj?

**Comment by hainm** [comment]
@drroe: let me look at pytraj’s code first. 
By the way, pytraj only call “Analyze” method of Analysis class, so I guess this won’t trigger writing datafile?

Cheers.

**Comment by drroe** [comment]
> By the way, pytraj only call “Analyze” method of Analysis class, so I guess this won’t trigger writing datafile?

No - to avoid multiple potentially redundant file writes, data file writing is triggered via a call to `CpptrajState::MasterDataFileWrite()` (which calls the write routine for the `DataFileList` class; see e.g. https://github.com/Amber-MD/cpptraj/blob/585842232192a7d2e59cd730f465760a843009a0/src/Exec_RunAnalysis.cpp#L55).

**Comment by hainm** [comment]
I see. I guess pytraj won't need to use the `Analysis_[...]` class directly but use the (new) `Exec_[...]`.
This is a chance to clean up pytraj's code. Thanks.

**Comment by hainm** [comment]
It turns out it's an easy fix. Please see #1493

**Comment by hainm** [comment]
thanks @karlkirschner  for your report. If you ever want to use `pytraj` for the reported issue, please patch the cluster/__init__.py in here: https://github.com/Amber-MD/pytraj/pull/1493/files#diff-666dccc706a7155273e92106aa021ac8

cheers

**Comment by karlkirschner** [comment]
Before I forget, I wanted to say thanks for the work and update.
Bests,
Karl
