### ISSUE TITLE
Slicing a Trajectory to one frame returns a Frame instead of a new trajectory

### ISSUE THREAD

**Issue by bradakstx** [Amber-MD/pytraj#1497]
Not sure if this is a bug or just unexpected behavior. I want to read in a single frame from a trajectory (the last one, say) and write to a single structure file format. However the following fails:

>> traj = pt.load(<mdcrd>, <prmtop>)
>> traj = traj[-1]
>> traj.save('foo.rst7')
AttributeError: 'pytraj.trajectory.frame.Frame' object has no attribute 'save'

The same error can also be obtained by:
>> traj = pt.load(<mdcrd>, <prmtop>, frame_indices=(0))
>> traj.save('foo.rst7')
AttributeError: 'pytraj.trajectory.frame.Frame' object has no attribute 'save'

It looks like pytraj is refusing to make a single Frame Trajectory object -- is that true? Is that intentional?

**Comment by hainm** [comment]
> It looks like pytraj is refusing to make a single Frame Trajectory object -- is that true? Is that intentional?

True and False
True: traj[0] -> Frame
False: traj[0:1] -> a new Trajectory with a single frame. :D 

It's design intention for performance. Cheers.

**Comment by hainm** [comment]
```python
In [1]: x = [1, 2]

In [2]: x[0]
Out[2]: 1

In [3]: x[0:1]
Out[3]: [1]
```

**Comment by hainm** [comment]
> I want to read in a single frame from a trajectory (the last one, say) and write to a single structure file format. 

Alternatively,
```
traj = pytraj.iterload(...)
pytraj.write_traj('abc.pdb', traj, frame_indices=[5])
```

**Comment by bradakstx** [comment]
Indeed that works out. 

>> traj = traj[-1:] # trajectory with 1 frame

Is there any way to do this via slicing syntax during load() or iterload()? Right now frame_indices has to be whole numbers but I'd love to be able to just directly load the last frame as a single frame trajectory (or maybe that isn't actually faster?).

**Comment by hainm** [comment]
may be this?

```
In [10]: pt.iterload(fname, topfname, frame_slice=(1, 2))                                                                                                                                                          
Out[10]: 
pytraj.TrajectoryIterator, 1 frames: 
Size: 0.000118 (GB)
<Topology: 5293 atoms, 1704 residues, 1692 mols, PBC with box type = ortho>
```

or  this
```
In [13]: pt.load(fname, topfname, frame_indices=[-1])                                                                                                                                                              
Out[13]: 
pytraj.Trajectory, 1 frames: 
Size: 0.000118 (GB)
<Topology: 5293 atoms, 1704 residues, 1692 mols, PBC with box type = ortho>
 ```

**Comment by bradakstx** [comment]
That second example gives me the error "Internal Error: Global index -1 is out of range". Maybe a versioning issue? Or a difference in the NetCDF parser?

**Comment by hainm** [comment]
I see. You're right. That feature was added recently (I did not recall if I released it or not :D).

https://github.com/Amber-MD/pytraj/pull/1474

**Comment by bradakstx** [comment]
Good to know! Thanks for all of the clarifications.
