### ISSUE TITLE
Issue loading in a trajectory pdb 

### ISSUE THREAD

**Issue by jschiffe-jnj** [Amber-MD/pytraj#1500]
Hello, 

i'm trying to read in a PDB trajectory. I've written the trajectory from both VMD as well as the mdconvert tool in MDtraj and neither of the outputs are recognized by pt.iterload or pt.Trajectory. Iterload is saying that there are no atoms, and Trajectory returns an UnboundLocalError that the local variable 'top_' is referenced before the assignment.

**Comment by hainm** [comment]
Can you please upload your pdb file (you might need to rename `your.pdb` to `your.pdb.txt` to able to attach and your code here? thanks.

**Comment by hainm** [comment]
> i'm trying to read in a PDB trajectory. 

By the way, why do you need to convert to a PDB trajectory instead of using `.nc` fomat or so on?

**Comment by hainm** [comment]
Close this case since there's no further interest (?).
