### ISSUE TITLE
loading GROMACS trajectory

### ISSUE THREAD

**Issue by aCompChemist** [Amber-MD/pytraj#1502]
I'm having trouble loading a gromacs trajectory. Any help would be appreciated. See the code, error, and files below. 

The topology loads correctly, but any trajectory shows up as empty (traj.n_frames=0).

[Archive.zip](https://github.com/Amber-MD/pytraj/files/4016791/Archive.zip)

Thanks,
Joe

```
import pytraj as pt
import nglview as nv

traj = pt.load('Y2F00.gro', top='Y2F.top')

traj.n_frames

view = nv.show_pytraj(traj)
```

> 
>  IndexError                                Traceback (most recent call last)
> <ipython-input-3-d7d06e2fe12e> in <module>
>       6 traj.n_frames
>       7 
> ----> 8 view = nv.show_pytraj(traj)
> 
> ~/.local/lib/python3.6/site-packages/nglview/show.py in show_pytraj(pytraj_trajectory, **kwargs)
>     313 
>     314     trajlist = [PyTrajTrajectory(traj) for traj in trajlist]
> --> 315     return NGLWidget(trajlist, **kwargs)
>     316 
>     317 
> 
> ~/.local/lib/python3.6/site-packages/nglview/widget.py in __init__(self, structure, representations, parameters, **kwargs)
>     240             for trajectory in trajectories:
>     241                 name = py_utils.get_name(trajectory, kwargs)
> --> 242                 self.add_trajectory(trajectory, name=name, **kwargs)
>     243         else:
>     244             if structure is not None:
> 
> ~/.local/lib/python3.6/site-packages/nglview/widget.py in add_trajectory(self, trajectory, **kwargs)
>    1138             trajectory = trajectory
>    1139 
> -> 1140         self._load_data(trajectory, **kwargs)
>    1141         setattr(trajectory, 'shown', True)
>    1142         self._trajlist.append(trajectory)
> 
> ~/.local/lib/python3.6/site-packages/nglview/widget.py in _load_data(self, obj, **kwargs)
>    1206         if not is_url:
>    1207             if hasattr(obj, 'get_structure_string'):
> -> 1208                 blob = obj.get_structure_string()
>    1209                 kwargs2['ext'] = obj.ext
>    1210                 passing_buffer = True
> 
> ~/.local/lib/python3.6/site-packages/nglview/adaptor.py in get_structure_string(self, index)
>     348 
>     349     def get_structure_string(self, index=0):
> --> 350         return _get_structure_string(self.trajectory[index:index + 1].save)
>     351 
>     352 
> 
> ~/.local/lib/python3.6/site-packages/pytraj/trajectory/trajectory.py in __getitem__(self, index)
>     303         """
>     304         if self.n_frames == 0:
> --> 305             raise IndexError("Your Trajectory is empty, how can I index it?")
>     306 
>     307         if is_int(index):
> 
> IndexError: Your Trajectory is empty, how can I index it?

**Comment by hainm** [comment]
hi @drroe, do you have any comment on this? Please see error with `cpptraj` below. thanks.

```
 $ cpptraj 

CPPTRAJ: Trajectory Analysis. V4.14.0 (AmberTools V19.09)
    ___  ___  ___  ___
     | \/ | \/ | \/ | 
    _|_/\_|_/\_|_/\_|_

| Date/time: 01/02/20 13:00:32
| Available memory: 551.223 MB

	Loading previous history from log 'cpptraj.log'
> parm Y2F.top         
  [parm Y2F.top]
	Reading 'Y2F.top' as Gromacs Topology
Warning: Currently only basic topology info (no parameters) read from gromacs topologies.
Warning: Could not process '#include' file 'gromos53a6.ff/forcefield.itp', skipping.
Warning: Could not process '#include' file 'gromos53a6.ff/spc.itp', skipping.
Warning: Could not process '#include' file 'gromos53a6.ff/ions.itp', skipping.
	1 instances of molecule Protein
Warning: Y2F.top: Determining default bond distances from element types.
> trajin Y2F00.gro 
  [trajin Y2F00.gro]
	Reading 'Y2F00.gro' as GRO file
Error: Number of atoms 6480 does not match associated parm Y2F.top (21)
Error: Could not set up 'Y2F00.gro' for reading.
Error: Could not set up input trajectory 'Y2F00.gro'.
> 
```

**Comment by hainm** [comment]
hi @aCompChemist, does the `Y2F00.gro` file has the same number of atoms as the `Y2F.top`?

**Comment by hainm** [comment]
Both .gro and .trr have `6480` atoms but the `Y2F.top` has only 21 atoms.

**Comment by hainm** [comment]
By the way, below code helps your visualization:

![p](https://user-images.githubusercontent.com/4451957/71684116-9058b900-2d62-11ea-81c6-9f408b14d180.png)

**Comment by aCompChemist** [comment]
Hi @hainm,

Thanks for the rapid response. I am actually a newbie with gromacs...I've used amber for the past couples years.

I think the topology file, Y2F.top, doesn's explicitly list the solvent molecules, but at the final line of the file it accounts for the number of solvent molecules. This file is used in gmx grompp to preprocess and create the tpr file for input in the actual MD run. 

I'm not sure if that clarifies things. I'm not sure what other topology file to load other than Y2F.top, which was used to generate the .gro file.

**Comment by hainm** [comment]
@aCompChemist  Please check my above example :D.

**Comment by aCompChemist** [comment]
Yes that helps! Though there is some PBC issues as you can see the edge waters wanting to bond through the whole cell. 

I appreciate the help @hainm and thanks for all the great work on pytraj!

**Comment by hainm** [comment]
> hough there is some PBC issues as you can see the edge waters wanting to bond through the whole cell.

Can you please try `traj.autoimage()` first?

**Comment by aCompChemist** [comment]
Yes, just tried. No luck. 

It appears that the box info isn't being read into the topology.

<img width="796" alt="Screen Shot 2020-01-02 at 8 57 30 PM" src="https://user-images.githubusercontent.com/59450353/71703474-b0a86800-2da2-11ea-92f4-f7cd533296d0.png">

**Comment by hainm** [comment]
hi @aCompChemist, can you please try to create the box (code below) from `parmed`'s Structure?

```
In [27]: traj.top.box = pt.core.Box(p.box)                                                                                                                                                                         

In [28]: traj.top                                                                                                                                                                                                  
Out[28]: <Topology: 6480 atoms, 2154 residues, 2154 mols, PBC with box type = ortho>

traj.autoimage()
```
