### ISSUE TITLE
Align two molecules within one frame?

### ISSUE THREAD

**Issue by khoroshyy** [Amber-MD/pytraj#1503]
Hi.
I have two protein units in one frame.
Can I align them?
Thanks.
Petro

**Comment by hainm** [comment]
May be something like below?

```
import pytraj as pt
stock_traj  = pt.load('your.pdb')
traj = pt.load('your.pdb')
ref = pt.load('your.pdb')
pt.rmsd(traj, ref=ref, mask='your 2nd unit', ref_mask='your 1st unit')
# Now taking the coordinates of your 1st unit from `stock_traj` and update them in `traj.xyz`? 
```

**Comment by khoroshyy** [comment]
Thanks I will give it a try...

**Comment by khoroshyy** [comment]
Works like a charm, just one more question. After realignment, of two structures in nglview widget bonds are formed between close atoms of two different structures. Any way to avoid it?
Thanks.

**Comment by khoroshyy** [comment]
Problem with bonds was solved by adding each molecule as a separate trajectory.
