### ISSUE TITLE
residue numbering after striping?

### ISSUE THREAD

**Issue by khoroshyy** [Amber-MD/pytraj#1510]
Hi.
I have stripped from a trajectory everything but residues 201-400.
The residues are shown in nglview with numbers 201-400.
But  when I try to select mask on the stripped residues I have to address them as 1-200. Is it expected behavior?
Thanks.
Petro.

**Comment by hainm** [comment]
> But when I try to select mask on the stripped residues I have to address them as 1-200.

hi, yes, that's expected.

**Comment by khoroshyy** [comment]
OK. It took me some time to realize it :)
