### ISSUE TITLE
importing Trajectory in load_mdtraj

### ISSUE THREAD

**Issue by wwilla7** [Amber-MD/pytraj#1513]
I installed pytraj and mdtraj using the following commands:
```
conda create -n test -c ambermd pytraj
conda activate test
conda install -c conda-forge mdtraj
```

and then I ran in a python prompt

```
import pytraj as pt
import mdtraj as md
structure_md = md.load("bcd_pbc.rst7", top = "bcd_pbc.prmtop")
traj_md = pt.externals.load_mdtraj(structure_md, top = "bcd_pbc.prmtop")
```

and I got
> ImportError: cannot import name 'Trajectory' from 'pytraj.trajectory'

This seems like an easy fix (from `pytraj import Trajectory` instead of `from pytraj.trajectory import Trajectory`). 

Does this also happen for you, and if so, should I open a PR to fix the import statments?
[files.zip](https://github.com/Amber-MD/pytraj/files/4131870/files.zip)

**Comment by hainm** [comment]
hi @wwilla7, it's a deprecated function and I don't see why pytraj users need to use `load_mdtraj` anymore. My original aim to introduce that function is to read its (`mdtraj`) own HDF5 format. 

But thank you for your report. Cheers.
