### ISSUE TITLE
writing trajectoreis deletes time information

### ISSUE THREAD

**Issue by pindakaas42** [Amber-MD/pytraj#1515]
Using the save method of the Trajectory object as a .nc file sets all time information in eacht frame to zero. (also happens with TrajectoryIterator)
Version: pytraj-2.0.5-py2.7-linux-x86_64.egg

**Comment by hainm** [comment]
hi @pindakaas42, can  you please try `pytraj.write_traj` with `time=True`?

https://github.com/Amber-MD/pytraj/pull/1456

**Comment by pindakaas42** [comment]
okay that works, thanks.

**Comment by pindakaas42** [comment]
my only question would be why you would want to write zeros instead of the actual time? This should save neither computation time in any relevant way nor disk space, as the file is filled with zeros.

**Comment by hainm** [comment]
@pindakaas42  good question. When I introduced the `time=False` option, I thought that time won't be written to the output file. Let me doublecheck and turn it on as default if what you said is true. thanks.

**Comment by hainm** [comment]
> my only question would be why you would want to write zeros instead of the actual time?

... when there is no actual time, e.g: writing a bunch of pdb files to .nc format.
