### ISSUE TITLE
pt.closest with dtype='trajectory'  takes forever to run

### ISSUE THREAD

**Issue by khoroshyy** [Amber-MD/pytraj#1518]
Hi.
I am trying to select waters closest to a residue
sym_wat = pt.closest(sym, mask=':66', n_solvents=10)
Thai command runs fine, but if I want a trajectory output it takes forever. It does not matter if I have 10 frames or 500. The system has about 1000 water molecules.
sym_wat = pt.closest(sym, mask=':66', n_solvents=10,dtype='trajectory')
Any hints on it?
Thanks.

**Comment by drroe** [comment]
One general way to debug things in pytraj is to run the same calculation in cpptraj if possible. This will help determine if the issue is with the underlying cpptraj code or with the python interface.

**Comment by khoroshyy** [comment]
> One general way to debug things in pytraj is to run the same calculation in cpptraj if possible. This will help determine if the issue is with the underlying cpptraj code or with the python interface.

Hi. 
That came in my mind to, It works flawlessly with cpptraj. 
%%file 01-autoimage.in
parm 03-cerulean.parm7
trajin 010-cerulean_md_wat_NTP.nc
autoimage :66
closest 10 :66 outprefix strip parmout 03-cerulean_closest.parm7
trajout 010-cerulean_md_wat_NTP_ai.nc    
run

I may switch to cpptraj for some things, but I would like to avoid it. As I don't want to have different versions of trajectories  saved on my HDD.

One thing which I cannot grasp is how to use "generator object" which is output of the first command: sym_wat = pt.closest(sym, mask=':66', n_solvents=10)

**Comment by hainm** [comment]
I don't see the issue with my testing systems. Do you have any toy files so I can test? thanks.

> One thing which I cannot grasp is how to use "generator object" which is output of the first command: sym_wat = pt.closest(sym, mask=':66', n_solvents=10)

Please see the usage here: 
https://github.com/Amber-MD/pytraj/blob/61cb9d23e294e771f6d60b74877fffa99dfc1ffc/tests/test_analysis/test_closest.py#L28

**Comment by hainm** [comment]
The reason the generator object is default is to avoid out of memory for big trajectory.

**Comment by khoroshyy** [comment]
> I don't see the issue with my testing systems. Do you have any toy files so I can test? thanks.
> 
> > One thing which I cannot grasp is how to use "generator object" which is output of the first command: sym_wat = pt.closest(sym, mask=':66', n_solvents=10)
> 
> Please see the usage here:
> 
> https://github.com/Amber-MD/pytraj/blob/61cb9d23e294e771f6d60b74877fffa99dfc1ffc/tests/test_analysis/test_closest.py#L28

Thanks.
