### ISSUE TITLE
slicing of pt.TrajectoryIterator traj[:-1] creates MemoryError

### ISSUE THREAD

**Issue by pindakaas42** [Amber-MD/pytraj#1520]
The title says it all. This operation works with pt.Trajectory. I don't see why an object like TrajectoryIterator, which has a length should have a problem with this.
PS:
Also the traj[2::] for example causes this same error.
Same for traj[::2]. 

Since traj.iterframe works fine and returns an object, that I would guess is used internally to iterate over the Trajectory Iterator anyway this should be an easy fix, at least I hope so. 

Version : pytraj-2.0.5-py2.7-linux-x86_64.egg/

**Comment by pindakaas42** [comment]
Okay this appears to be a result of the fact that a pt.Trajectory is created in this process and thus all out of memory would be loaded into RAM, is this necessary? Could the indexing not just return, what would basically be a frame iterator, so out of memory, wrapped in a TrajectoryIterator object?

**Comment by hainm** [comment]
You can try:

`traj(start,stop,stride)` (if I remember correctly) or `pytraj.iterframe`. 

Using `[ ]` to return in-memory traj is intentional design. 

Please read further here: 

https://amber-md.github.io/pytraj/latest/trajectory_exercise.html

**Comment by pindakaas42** [comment]
Okay, but why would I need an indexed trajectory to become loaded into memory? If I want that I would have loaded it into memory right? It's your design choice obviously, it just confused me and it's a pretty heavy side effect that most people won't be expecting from simple indexing.

**Comment by hainm** [comment]
> it's a pretty heavy side effect that most people won't be expecting from
simple indexing.

You are quite subjective when saying “most people” here.

The design was chosen so both on-disk and in-memory have similar API. It
also made the implementation easier.

For example, pytraj has this syntax

traj[[1, 3]][‘@CA’] for both types of trajectories. If it follows your
idea, it’s harder to implement.

**Comment by pindakaas42** [comment]
Wouldn't it be more consistent to expect the "out of memory" object to stay that way unless I take a very explicit action? 

Unless you'd like to discuss software design here I won't bore you with my opinions on this matter further It's you library after all.

**Comment by hainm** [comment]
> Wouldn't it be more consistent to expect the "out of memory" object to stay that way unless I take a very explicit action? Slicing seems to me the kind of thing that should not change something fundamental, at least that's how numpy uses it.

Yes, that's what I really wanted to do but I did not know how to implement it when I first started. I am open to the idea of "how to do it right", especially when you want to index the trajectory with arbitrary array, like `traj[[1, 5, 4]]`

**Comment by pindakaas42** [comment]
I am using this class now, I would like to make it return Trajectory iterators not Frame iterators, but I am not familiar with how your integration of cpptraj works so this is an extremely suboptimal solution, also it has not been tested a lot. 
This is probably not the right place so forgive me, but could you point me towards any literature on how you integrated cpptraj into python? 
I would really like to understand this aspect so I can contribute more sensible code.
```
class mytraj(pt.TrajectoryIterator):
    '''returns Frame iterators when sliced or given boolean index arrays.'''
    def __getitem__(self, index):
        if type(index) == int:
            return super(mytraj, self).__getitem__(index)
        elif type(index) == slice:
            if index.start is not None:
                start = index.start
            else:
                start = 0
            if index.step is not None:
                step = index.step
            else:
                step = 1
            return self.iterframe(start, index.stop,step)
        else:            
            if type(index[0]) == bool or (hasattr(index, 'dtype') and index.dtype == np.bool_):
                index = np.where(index)[0]
            return self.iterframe(frame_indices=index)

```

**Comment by hainm** [comment]
hi @pindakaas42  thanks for your code.

> This is probably not the right place so forgive me, but could you point me towards any literature on how you integrated cpptraj into python?
> I would really like to understand this aspect so I can contribute more sensible code.

Please see this file:
[ ] - https://github.com/Amber-MD/pytraj/blob/master/pytraj/trajectory/c_traj/c_trajectory.pyx#L284
This is where the `__getitem__` is implemented. 
[ ] - https://github.com/Amber-MD/pytraj/tree/master/tests/test_trajectory

(pay attention to https://github.com/Amber-MD/pytraj/blob/master/tests/test_trajectory/test_fancy_indexing.py)

The main idea is make sure `Trajectory` and `TrajectoryIterator` to have the same (or similiar) API. 
For example: if `traj_on_mem[[1, 2, 4]]` works, `traj_on_disk[[1,2,4]]` should work too.

The point of keeping the API is that the caller code does not need to use `if` statement:

```
if isinstance(traj, Trajectory):
    do this
elif isinstance(traj, TrajectoryIterator):
   do that
```

let me know if you have further questions.

**Comment by pindakaas42** [comment]
I was talking more about generally if you

**Comment by hainm** [comment]
I go ahead closing this issue since I won't able to make the change due to my limitation in designing the API.  Thanks @pindakaas42 for your suggestion.
