### ISSUE TITLE
carving closest solvent

### ISSUE THREAD

**Issue by craldaz** [Amber-MD/pytraj#1527]
When I carve the closest solvent for a trajectory the resulting carved trajectory is very strange. Essentially large chunks of solvent fly off. 

I think this is because the closest function has a reference with respect to the initial frame. However, even if I save the frames individually and reload them separately, the same result occurs. 

How can I carve the closest n solvent for all frames of the trajectory properly?

**Comment by hainm** [comment]
hi @craldaz, can you please try `cpptraj` directly to see if the issue still exists? 
Or can you please post your toy trajectory with similar issue so we can reproduce it?

**Comment by craldaz** [comment]
Hi @hainm , cpptraj worked! Thanks
