### ISSUE TITLE
Import Issue

### ISSUE THREAD

**Issue by hl2500** [Amber-MD/pytraj#1542]
Good afternoon, I recently installed pytraj via conda and was trying to import it in a python file, but I got the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/progs/amber16/lib/python2.7/site-packages/pytraj/__init__.py", line 12, in <module>
    from .cpp_options import info as compiled_info
ImportError: dynamic module does not define module export function (PyInit_cpp_options)
```

Seems like there is a conflict between the python2.7 packages which come with amber and python3.7 that I 'm trying to use. How can I solve this problem? Thank you!

**Comment by hainm** [comment]
hi @hl2500, make sure to unset the PYTYHONPATH (point to `/home/progs/amber16/lib/python2.7/`) and try again. e.g: python3 your_script.py

**Comment by hl2500** [comment]
Thank you! I set the PYTHONPATH to python3. Since I'm also using MMPBSA.py with amber, would this influence the usage of amber python packages?

**Comment by hainm** [comment]
@hl2500 is there any reason you don't want to use `pytraj` in amber itself? (the one in /home/progs/amber16/lib/python2.7/site-packages/pytraj/)

**Comment by hl2500** [comment]
I wrote a script with python3 using pytraj to analyze the trajectory. I wasn't sure if python3 is compatible with pytraj under the python2.7 directory, so I installed pytraj package for python3. Are they compatible with each other? If so, I think I can uninstall the one for python3.

**Comment by hainm** [comment]
@hl2500 Uhm, why don't you just build amber with python 3 then?

**Comment by hainm** [comment]
By the way, you can use different terminals with different python versions. I don't see any issue with that.

**Comment by hl2500** [comment]
Okay, thank you for the suggestion! The amber was built many years ago. I may have to rebuild it.

**Comment by hainm** [comment]
> The amber was built many years ago. I may have to rebuild it.

FYI: If you just need AmberTools, you can install it via conda too from conda-forge channel.
