### ISSUE TITLE
Modified bases Analysis

### ISSUE THREAD

**Issue by Manish315** [Amber-MD/pytraj#1544]
Hi Hai,

Is there any way to extract base-pair parameters using *nastruct* command for a nucleic acid sequence containing custom bases like Formyl Cytosine, Hydroxyl Cytosine, or Methyl Cytosine? Or do I have to manually make changes in the 4 files as suggested by Daniel Roe here:

http://archive.ambermd.org/201602/0387.html

Regards
Manish

**Comment by hainm** [comment]
hi @Manish315, can you please try the latest release with `resmap` option?
https://github.com/Amber-MD/pytraj/blob/66e181535900dbac6befb357302a3bf8f6c6ceb3/pytraj/analysis/nucleic_acid_analysis.py#L44

I beleived @drroe added `resmap` a while ago for `cpptraj`.

**Comment by Manish315** [comment]
Hi @hainm, 

Thanks a lot for the quick response. `resmap` option in the `nastruct` command did the job.

Regards 
Manish
