### ISSUE TITLE
Trajectory mask with only solvent molecules?

### ISSUE THREAD

**Issue by markperri** [Amber-MD/pytraj#1545]
I have a box of just water (using NAMD) and want to display the water molecules within a certain radius of one of the water molecules.  I'm using pytraj with nglview in a Jupyter notebook.  If I use:

`mask = ':50<:100.0'`
`print (traj[mask])`
`view3 = nv.show_pytraj(traj[mask])`
`view3`

The result is:
`pytraj.Trajectory, 1000 frames: `
`Size: 0.000067 (GB)`
`<Topology: 3 atoms, 1 residues, 1 mols, non-PBC>`

And just one water molecule (:50) is displayed.

Using closest works just fine:
`closest = pt.closest(traj, mask=':50', n_solvents=50, dtype='trajectory')`
Shows me waters around my selected water molecule.

Is there a way to use traj[mask] to select all waters within a certain distance of my chosen water molecule?

**Comment by hainm** [comment]
> Is there a way to use traj[mask] to select all waters within a certain distance of my chosen water molecule?

There is a non-easy way to do it, but your system's topology would change since the number of atoms will be changed from frame to frame (you're asking to extract ANY atoms within 100A from `:50`

Are you sure if that's helpful for your analysis?

**Comment by hainm** [comment]
Please try this code. The code will generate new `n_frames` trajectories.

```python
import numpy as np
import pytraj as pt

traj = pt.datafiles.load_tz2_ortho()
top = traj.top.copy()

for frame in traj:
    top.set_reference(frame)
    atom_indices = top.select(':50<@10')
    print(atom_indices.shape)
    new_top = top[':50<@10'] # based on the reference frame set above
    new_traj = pt.Trajectory(xyz=np.array([frame.xyz[atom_indices]]), top=new_top)
    print(new_traj)
```

**Comment by markperri** [comment]
Thanks, that works!
Mark
