### ISSUE TITLE
Question about use Jupyter notebook remotely

### ISSUE THREAD

**Issue by ZihanChen1995** [Amber-MD/pytraj#1546]
Hi! Thank you so much for this handy and great library. I just read your instruction: [use Jupyter notebook remotely](https://amber-md.github.io/pytraj/latest/tutorials/remote_jupyter_notebook). It works perfectly on my laptop and server. However, I meet a question when I try to change the directory of my workspace. May I ask why this happens?

***
Here are some details:

1. Firstly, I just follow the steps: 
```
# In remote host, open the terminal, change directory to where you have your notebooks and type:
jupyter notebook --no-browser --port=8889

# Then in my local computer, open terminal, then type:
ssh -N -f -L localhost:8888:localhost:8889 username@your_remote_host_name

# Finally open web browser (google chrome) and type:
localhost:8888
```

It asks me to input the token, I do it and it opens the jupyter notebook normally. However, when I try to move to another directory on my host sever, it keeps directing me to the previous directory. 
```
# I stop the jupyter server on host, and kill the port on my local computer firstly
# ctrl+c to stop the Jupyter server
lsof -ti:8888 | xargs kill -9 # to empty the port

# then I move to new directory on host, and repeat the steps
cd /new_dir
jupyter notebook --no-browser --port=8889
ssh -N -f -L localhost:8888:localhost:8889 username@your_remote_host_name
```

However, when I type `localhost:8888` in the browser, it directs me to the directory `/old_dir` but not the `/new_dir`. May I ask why this happen and how can I fix it?

(My host server is Ubuntu 18.04, and local computer is Mac OS 10.13.6)

Thank you so much in advance!

**Comment by hainm** [comment]
hi @ZihanChen1995: Can you try to use `ps ux` in both local and server to see if you still need to `kill` some processes? I can not think of any reason besides that.

**Comment by ZihanChen1995** [comment]
Hi @hainm Thank you for your reply. I've figured this out. This is because `ssh -N -f -L localhost:8888:localhost:8889 username@your_remote_host_name` map the Jupyter Notebook from host 8888 to 8889 on the server, but `Jupyter Notebook stop` only kills the process on port 8888. Hence `lsof -ti:8888 | xargs kill -9` doesn't work. To slove this I just `jupyter notebook stop 8889` instead, once `jupyter notebook list` says `Currently running servers:`, then I can move to new directory and start a new workspace.

Thank you so much for your time. Have a nice day!
