### ISSUE TITLE
pytraj.analysis.rmsd.rmsd is not working : calculating rmsd  without fitting

### ISSUE THREAD

**Issue by 01-ForestGump** [Amber-MD/pytraj#1548]
rmsd_data = rm(traj, ref=i, mask='@C,N,O', nofit = False)
It seems that the nofit = True/False is returning same RMSD.

This is my code :

import pytraj as pt
from pytraj.all_actions import rmsd as rm
from pytraj import matrix
import pandas as pd
df = pd.DataFrame()
traj = pt.iterload("md.trj", "../system/4ey5.wet.complex.prmtop")

list1 = [0, 500]
for i in list1:
    **### rmsd_data = rm(traj, ref=i, mask='@C,N,O', nofit = False)**
    string = "Frame_" + str(i)
    df[string] = rmsd_data
df.to_csv("RMSD.csv")

The RMSD data generated has a very huge offset when nofit = False. This is the issue.

frame RMSD
1,  29.93368087717184,
2  ,35.11188324712822,
3,  38.16446780167874,
4,  40.842250866770584,
5,  42.65177310836225,
6,  44.390397872297655,
7,  45.79464719425711,
8,  47.16732188324002,
9,  48.32410412330032,
10,  48.94858484275818

**Comment by 01-ForestGump** [comment]
rmsd_data = rm(traj, ref=i, mask='@C,N,O', nofit = False)
It seems that the  nofit = True/False is returning same RMSD.

**Comment by hainm** [comment]
@01-ForestGump I am not sure about your system, but the `nofit=True/False` works well with the test system.
Please try this:

```python
In [4]: traj = pt.datafiles.load_tz2()                                                                                                              

In [5]: pt.rmsd(traj, ref=1, nofit=True, mask='@CA')                                                                                                
Out[5]: 
array([2.75411761, 0.        , 2.87101254, ..., 6.17071137, 6.41362752,
       6.07758999])

In [6]: traj = pt.datafiles.load_tz2()                                                                                                              

In [7]: pt.rmsd(traj, ref=1, nofit=False, mask='@CA')                                                                                               
Out[7]: 
array([2.54596866, 0.        , 2.65172968, ..., 5.49644953, 5.88539744,
       5.1679794 ])
```

**Comment by hainm** [comment]
Note that if your trajectory is mutable and if you used `nofit=False` first, the trajectory coordinates would be updated, after that using `nofit=True/False` does not make sense.

**Comment by hainm** [comment]
In other words, `rmsd` command has side effect, it does the rms calculation with fitting and also mutate the trajectory.

**Comment by hainm** [comment]
To avoid the side effect, use `update_coordinate=False`

**Comment by 01-ForestGump** [comment]
Thanks for your help and quick response.
It seems that I was starting ref=0 which should be instead started from one.
Now calculation is running correctly

**Comment by hainm** [comment]
Glad to help. Cheers.
