### ISSUE TITLE
load_MDAnalysis fails

### ISSUE THREAD

**Issue by tclick** [Amber-MD/pytraj#1559]
If I have the following code

```python
import MDAnalysis as as mda
import pytraj as pt

top = 'protein.parm7'
traj = 'protein.nc'
u = mda.Universe(top, traj)
univ = pt.externals.load_MDAnalysis(u)
```
The following exception is thrown:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-71-f17cfb88e9d8> in <module>
----> 1 pt.externals.load_MDAnalysis(u)

~/.conda/envs/python-qaa/lib/python3.8/site-packages/pytraj/externals/load_other_packages.py in load_MDAnalysis(universe, top)
     87 
     88     from MDAnalysis import Universe
---> 89     from pytraj.Trajectory import Trajectory
     90     from ..Frame import Frame
     91 

ModuleNotFoundError: No module named 'pytraj.Trajectory'

I am using pytraj 2.0.5, MDAnalysis 1.0.0, and Python 3.8 from Anaconda.

**Comment by hainm** [comment]
hi @tclick: I think most of the methods in `external` is deprecated because there is no point to use them. 
(The original aim was to load `.xtc` format via `mdanalysis`, but cpptraj/pytraj can load .xtc natively now).

Please just use `pytraj.load(traj, top)`

**Comment by tclick** [comment]
Thank you.

**Comment by hainm** [comment]
I go ahead closing this case. Please feel free to open other issues if any. Cheers.
