### ISSUE TITLE
Matrix Distance not working as expected 

### ISSUE THREAD

**Issue by dylanabramson33** [Amber-MD/pytraj#1560]
The documentation makes it seem that pytraj.analysis.matrix.dist(trajectory) is supposed to return a tensor with the distance matrix for each frame in the trajectory. When I run it, I only get the distance matrix for the first frame. Is this the expected behavior?

**Comment by hainm** [comment]
hi @dylanabramson33, I think the output is the average value of all the frames.

**Comment by dylanabramson33** [comment]
Hi @hainm, okay got it. If I pass in a frame for frame_indices it will output the distances for that frame, right?

**Comment by hainm** [comment]
> If I pass in a frame for frame_indices it will output the distances for that frame, right?

yeah, that seems right.

**Comment by dylanabramson33** [comment]
Great, thanks!
