### ISSUE TITLE
issue importing from source installation

### ISSUE THREAD

**Issue by patricklawton** [Amber-MD/pytraj#1565]
Hello!

I installed pytraj (and thus cpptraj) from source code following the instructions on the pytraj github. When I try to import from a python (3.8.3) shell, though, I get the error pasted below. I made sure that pytraj was not simultaneously installed in my conda environment by running 'conda uninstall pytraj' and I added the path to my pytraj installation to my PYTHONPATH variable, but I still get this error. Appreciate any help greatly!

>>> import pytraj
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/patrick/pkgs/pytraj/pytraj/__init__.py", line 24, in <module>
    from .utils.misc import info
  File "/data/patrick/pkgs/pytraj/pytraj/utils/misc.py", line 7, in <module>
    from pytraj.core.c_options import set_world_silent
  File "/data/patrick/pkgs/pytraj/pytraj/core/__init__.py", line 2, in <module>
    from .topology_objects import Atom, Residue, Molecule
ModuleNotFoundError: No module named 'pytraj.core.topology_objects'

**Comment by hainm** [comment]
hi @patricklawton, I think you're in the root folder of the source code (`/data/patrick/pkgs/pytraj`) that has `pytraj` folder.

Can you `cd` to another location and try again? 

PS: The installed pytraj should be somewhere like:
```
miniconda3/lib/python3.8/site-packages/pytraj
```

**Comment by patricklawton** [comment]
I tried importing pytraj while in a different folder (`/home/patrick`) as well as the root folder as you mentioned and received the same error in both locations. 

Also, please correct me if I'm wrong, but shouldn't the installed pytraj exist wherever I cloned the pytraj git repo (which in my case is `/data/patrick/pkgs`)? I am no expert in package management but I'm going off [this](https://amber-md.github.io/pytraj/latest/installation.html#from-source-code-easy-way-linux-osx) guide. I mentioned conda just to say that I uninstalled it from my conda environment to avoid conflicting installation issues. 

Thanks!

**Comment by hainm** [comment]
> Also, please correct me if I'm wrong, but shouldn't the installed pytraj exist wherever I cloned the pytraj git repo (which in my case is /data/patrick/pkgs)? 

No, it's not right.

You need to run `python setup.py install` as described:

```
git clone https://github.com/Amber-MD/pytraj
cd pytraj

python ./setup.py install
```

and you DO NOT need to set PYTHONPATH to the source folder. You have to unset it.
Saying if your have python3 in `$HOME/miniconda3/` path, the installed pytraj (after running the setup command above) will be `$HOME/miniconda3/lib/python3.8/site-packages/pytraj` or something like that.

**Comment by patricklawton** [comment]
Thank you Hai, I removed the cpptraj and pytraj directories I had installed and re-installed from source as you suggested. There then exists a folder `/data/patrick/pkgs/miniconda3/lib/python3.8/site-packages/pytraj-2.0.5.dev0-py3.8-linux-x86_64.egg/pytraj` as you suggested I may find. 

However, when I try again to import pytraj without changing my PYTHONPATH as you suggest, it appears my system is trying to use a different installation of pytraj from the one I installed from source (`/opt/amber16/lib/python3.6/site-packages/pytraj`). This was installed by a previous user of the computer I am using. This leads to a different error: "ModuleNotFoundError: No module named 'pytraj.cpp_options'". 

If I add `/data/patrick/pkgs/miniconda3/lib/python3.8/site-packages/pytraj-2.0.5.dev0-py3.8-linux-x86_64.egg/pytraj` to the front of my PYTHONPATH, I am no longer able to open python from my terminal ("AttributeError: partially initialized module 'io' has no attribute 'DEFAULT_BUFFER_SIZE' (most likely due to a circular import)"). 

If I add `/data/patrick/pkgs/pytraj` to the front of my PYTHONPATH, I once again receive "ModuleNotFoundError: No module named 'pytraj.core.topology_objects'".

My apologies for bringing this issue away from the original post, if you are able to provide any more guidance it would be very much appreciated!

**Comment by hainm** [comment]
Please try this:

- open a new terminal
- unset PYTHONPATH # to remove any existing path in your .bashrc 
- Try: 
```bash
/data/patrick/pkgs/miniconda3/bin/python3 -c 'import pytraj; print(pytraj)'
```

Does that work?

**Comment by patricklawton** [comment]
The output I get is "<module 'pytraj' from '/data/patrick/pkgs/miniconda3/lib/python3.8/site-packages/pytraj-2.0.5.dev0-py3.8-linux-x86_64.egg/pytraj/__init__.py'>". Which I believe means it "worked"?

**Comment by hainm** [comment]
> Which I believe means it "worked"?

Yes, it did. I bet your original python is not in `/data/patrick/pkgs/miniconda3/bin/`
(try `which python` to see what I mean).

**Comment by patricklawton** [comment]
Great, thank you so much for the help! Just to clarify, I think the main issue may have been that my bashrc was automatically setting my python path to look in the directory corresponding to the old version of pytraj on my system. If I open up a new terminal and simply `unset PYTHONPATH` before I try to run python and import pytraj, it works fine and successfully imports my anaconda version. `which python` actually returns `/data/patrick/pkgs/miniconda3/bin/python`. Nevertheless, thanks so much for your help; I am happy getting started on my analysis now!

**Comment by hainm** [comment]
Great, happy analysis.
