### ISSUE TITLE
Nan in water coordinates after autoimage

### ISSUE THREAD

**Issue by briza81** [Amber-MD/pytraj#1566]
Hello, 

I am observing situation similar to http://archive.ambermd.org/202011/0220.html#start220, water coordinates after autoimage have nan or inf values but no troubles when using cpptraj directly. I have tried with fresh conda env as suggested on the mailing list, unfortunatley without success.  I wonder if there is some difference in environment, like used python version behind this?
Thank you.

**Env:**
python 3.8.6
numpy 1.20.0
pytraj 2.0.5
cptraj V4.25.6

**Code:**
        md_traj = pt.load(self.traj, self.top)
        print(md_traj)
        print(md_traj.xyz[0, 0:10, :]) # protein coords
        print(md_traj.xyz[0, -10:-1, :])   # water coords
        traj2 = pt.autoimage(md_traj)
        print(traj2)
        print(md_traj.xyz[0, 0:10, :])   # protein coords
        print(traj2.xyz[0, -10:-1, :])   # water coords

**Outcome:**
pytraj.Trajectory, 2 frames: 
Size: 0.002066 (GB)
<Topology: 46206 atoms, 10707 residues, 10415 mols, PBC with box type = truncoct>
           
[[55.73551941 27.63397026 45.11804962]
 [56.21062851 26.96479607 44.52933884]
 [55.70878601 27.14682579 46.00240326]
 [56.31634903 28.44925308 44.98370743]
 [54.30559921 27.96389008 44.7003746 ]
 [53.71137238 28.42972183 45.48649979]
 [54.26465988 28.95418167 43.55887604]
 [54.79854584 28.51947975 42.71382904]
 [52.77580643 29.19128418 43.11860275]
 [52.36390305 28.24370384 42.77143478]]
[[40.60223389 58.08405304 11.83193588]
 [40.64941406 58.38656235 11.1102581 ]
 [27.64909363 19.80669403 65.03728485]
 [28.27474403 19.19961548 65.07118225]
 [28.06599426 20.51477242 64.74407959]
 [27.80309868 19.82161331 64.99897766]
 [81.27116394 50.26408768 34.32173538]
 [80.77339935 50.96031189 34.49098969]
 [80.88722229 49.90134811 33.6273613 ]]
pytraj.Trajectory, 2 frames: 
Size: 0.002066 (GB)
<Topology: 46206 atoms, 10707 residues, 10415 mols, PBC with box type = truncoct>
           
[[17.1329719  27.67204606 45.12995204]
 [17.608081   27.00287186 44.54124125]
 [17.1062385  27.18490159 46.01430568]
 [17.71380152 28.48732888 44.99560985]
 [15.7030517  28.00196587 44.71227702]
 [15.10882487 28.46779763 45.4984022 ]
 [15.66211237 28.99225747 43.57077845]
 [16.19599833 28.55755555 42.72573146]
 [14.17325892 29.22935998 43.13050517]
 [13.76135554 28.28177964 42.7833372 ]]
[[-inf  nan  nan]
 [-inf  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]
 [-inf  nan  nan]
 [-inf  nan  nan]
 [-inf  nan  nan]]

**Comment by hainm** [comment]
hi @briza81 
Can you reproduce the issue with our tests data: `tz2.truncoct.{nc,parm7}`
https://github.com/Amber-MD/pytraj/tree/master/tests/data

**Comment by briza81** [comment]
vow super-quick response time :),

yup, have the same problem


pytraj.Trajectory, 2 frames: 
Size: 0.000260 (GB)
<Topology: 5827 atoms, 1882 residues, 1870 mols, PBC with box type = truncoct>
           
[[ -0.04731956   3.25585413  -8.62939644]
 [  0.68805903   3.92066956  -8.43616199]
 [  0.17160061   2.37129807  -8.19381142]
 ...
 [ -1.26814055   4.94501019 -10.27486324]
 [  0.47727728   4.94215965 -10.56071854]
 [ -0.65732551   4.31193542 -12.15196228]]
[[  1.52087581   0.5168227   13.75290203]
 [-10.4646101   15.33790398   3.9037056 ]
 [-10.88588905  14.74562359   4.52656984]
 ...
 [ -7.76200676  -0.51509833   7.48117971]
 [  2.3647902   -5.24273872   8.65899467]
 [  2.59730363  -5.35627413   7.73743105]]
pytraj.Trajectory, 2 frames: 
Size: 0.000260 (GB)
<Topology: 5827 atoms, 1882 residues, 1870 mols, PBC with box type = truncoct>
           
[[-6.65870858 24.33457648 25.99060475]
 [-5.92332999 24.9993919  26.18383919]
 [-6.43978841 23.45002042 26.42618977]
 ...
 [-7.87952958 26.02373253 24.34513795]
 [-6.13411174 26.020882   24.05928265]
 [-7.26871453 25.39065777 22.46803891]]
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]
 ...
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]]

**Comment by hainm** [comment]
Thanks. I will investigate this issue.

**Comment by hainm** [comment]
> vow super-quick response time :),
> 
> yup, have the same problem
> 
> pytraj.Trajectory, 2 frames:
> Size: 0.000260 (GB)
> <Topology: 5827 atoms, 1882 residues, 1870 mols, PBC with box type = truncoct>
> 
> [[ -0.04731956 3.25585413 -8.62939644]
> [ 0.68805903 3.92066956 -8.43616199]
> [ 0.17160061 2.37129807 -8.19381142]
> ...
> [ -1.26814055 4.94501019 -10.27486324]
> [ 0.47727728 4.94215965 -10.56071854]
> [ -0.65732551 4.31193542 -12.15196228]]
> [[ 1.52087581 0.5168227 13.75290203]
> [-10.4646101 15.33790398 3.9037056 ]
> [-10.88588905 14.74562359 4.52656984]
> ...
> [ -7.76200676 -0.51509833 7.48117971]
> [ 2.3647902 -5.24273872 8.65899467]
> [ 2.59730363 -5.35627413 7.73743105]]
> pytraj.Trajectory, 2 frames:
> Size: 0.000260 (GB)
> <Topology: 5827 atoms, 1882 residues, 1870 mols, PBC with box type = truncoct>
> 
> [[-6.65870858 24.33457648 25.99060475]
> [-5.92332999 24.9993919 26.18383919]
> [-6.43978841 23.45002042 26.42618977]
> ...
> [-7.87952958 26.02373253 24.34513795]
> [-6.13411174 26.020882 24.05928265]
> [-7.26871453 25.39065777 22.46803891]]
> [[nan nan nan]
> [nan nan nan]
> [nan nan nan]
> ...
> [nan nan nan]
> [nan nan nan]
> [nan nan nan]]

I can not reproduce the issue. Can you please:

* Show me the exact commands you used

* 
> cptraj V4.25.6

My cpptraj version is `'V4.26.3'`
Can you please try with the latest AmberTools

```
conda create -n at20 python=3.8 
conda install ambertools -c conda-forge 
source  activate at20
```

**Comment by hainm** [comment]
<img width="644" alt="Screen Shot 2021-02-01 at 2 57 09 PM" src="https://user-images.githubusercontent.com/4451957/106511106-c7395b00-649d-11eb-867c-474df79777ab.png">

**Comment by briza81** [comment]
Made a fresh conda env as suggested:
`conda create -n at20 python=3.8`
`conda activate at20`
`conda install ambertools -c conda-forge`

surprisingly, ambertools seems to come from pypi rather then conda-forge
`conda list`
`amberlite                 16.0                     pypi_0    pypi`
`ambertools                20.15                    pypi_0    pypi`

cpptraj version is still V4.25.6, sourced from the proper env, there are no collisions with other packages. I wonder if there is a difference between MacOS and Linux (Ubuntu)?

![nan_pytraj](https://user-images.githubusercontent.com/78376206/106586657-0375c580-6549-11eb-9bfb-a2f30a32d3fe.png)

**Comment by briza81** [comment]
just to update, installing from source code(http://amber-md.github.io/pytraj/latest/installation.html#from-source-code-easy-way-linux-osx) I got to pytraj 2.0.5.dev0 equipped with cpptraj V5.0.4. Here, the autoimaging works as expected. 

So the trouble seems to be that conda install ambertools -c conda-forge does not deliver pytraj compatible cpptraj for Linux machines.

**Comment by hainm** [comment]
>  I wonder if there is a difference between MacOS and Linux (Ubuntu)?

> So the trouble seems to be that conda install ambertools -c conda-forge does not deliver pytraj compatible cpptraj for Linux machines.

thanks @briza81 for your investigation. Yeah, I am using MacOs and you're using Linux in your example. 
Can you please check where your libcpptraj is?
```
~/miniconda3/envs/at20/lib/python3.8/site-packages/pytraj () $ ldd topology/*so
```

I am suspecting that you have the old `libcpptraj` somewhere.

**Comment by hainm** [comment]
Never mind, I can reproduce your issue in a new docker environment to separate the old `libcpptraj` issue.

**Comment by hainm** [comment]
> cpptraj version is still V4.25.6,

My bad. I was using the wrong `pytraj` version (dev version). After switching to the correct `pytraj`, I can see the 
```
In [16]: pt.__cpptraj_version__
Out[16]: 'V4.25.6'
```

To conclude, there is discrepancy between Linux and MacOs build and I don't know why. 
I am glad that installing the dev version resolve your issue. Hopefully this will be really resolved in the next release. Cheers.

**Comment by briza81** [comment]
ok, I can confirm that libcpptraj coming from new ambertools pckg is being used...

What is your estimate on the next release date?
Thank you.

**Comment by hainm** [comment]
According to the past releases, it should be around April.

**Comment by briza81** [comment]
just a small addon, it seems that the problem is gone when pt.iterload is used in place of pt.load
