### ISSUE TITLE
pytraj somehow prints output with suppressed stdout and stderr? 

### ISSUE THREAD

**Issue by tuckerburgin** [Amber-MD/pytraj#1567]
I want pytraj to be quiet, even when something is wrong with the files I give it (I have a use-case for loading files that may be broken in specific ways). For example, when attempting to load an empty trajectory, it complains:

```
>>> traj = pytraj.iterload('empty_traj.rst7', 'my_topology.prmtop')
Error: Error reading coordinates from Amber restart 'empty_traj.rst7'.
Error: Could not set up 'empty_traj.rst7' for reading.
Error: Could not set up trajectory 'empty_traj.rst7'
```

That's normal, but what I'm surprised by is that even when stdout and stderr have been suppressed, it manages to get through:

```
>>> print('hello world')
hello world
>>> raise RuntimeError('error')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
RuntimeError: error
>>> sys.stdout = open(os.devnull, "w")
>>> sys.stderr = open(os.devnull, "w")
>>> print('hello world')
>>> raise RuntimeError('error')
>>> traj = pytraj.iterload('atesa/tests/test_data/test.nc_no_frames.rst7', topology)
Error: Error reading coordinates from Amber restart 'empty_traj.rst7'.
Error: Could not set up 'empty_traj.rst7' for reading.
Error: Could not set up trajectory 'empty_traj.rst7'
```

Frankly I'm not even sure how that's possible -- are there output channels other than sys.stderr and sys.stdout? I couldn't seem to find the place in the code where these error messages are defined (perhaps it's actually apart of Amber?) Can someone explain this for me?

Thanks!

**Comment by hainm** [comment]
hi @tuckerburgin 

Please try `with pytraj.utils.context.capture_stdout()`:
```
In [15]: pt.load('./tz2.weird.nc', './tz2.parm7')
Error: Could not determine trajectory '/Users/nguyen/programs/pytraj/tests/data/tz2.weird.nc' format.
Error: Could not set up trajectory '/Users/nguyen/programs/pytraj/tests/data/tz2.weird.nc'
Out[15]: 
pytraj.Trajectory, 0 frames: 
Size: 0.000000 (GB)
<Topology: 223 atoms, 13 residues, 1 mols, non-PBC>
           

In [16]: with pt.utils.context.capture_stdout() as out:
    ...:     pt.load('./tz2.weird.nc', './tz2.parm7')
    ...: 

In [17]: print(out[1].read())
Error: Could not determine trajectory '/Users/nguyen/programs/pytraj/tests/data/tz2.weird.nc' format.
Error: Could not set up trajectory '/Users/nguyen/programs/pytraj/tests/data/tz2.weird.nc'
```

**Comment by hainm** [comment]
>  are there output channels other than sys.stderr and sys.stdout? 

Yes, the errors emitted from C++ code in cpptraj. Python does not know how to capture that.

**Comment by tuckerburgin** [comment]
Thanks @hainm !

`with pytraj.utils.context.capture_stdout()` works great, and is a much better solution than the workarounds I had been using before. Thanks also for the detail about Python not capturing C++ output.
