### ISSUE TITLE
FYI and two questions/requests

### ISSUE THREAD

**Issue by hmayes** [Amber-MD/pytraj#1571]
FYI: an image is not loading correctly on the documentation page, https://amber-md.github.io/pytraj/latest/index.html, under "Try pytraj online" (http://mybinder.org/assets/images/logo.svg)
<img width="326" alt="image" src="https://user-images.githubusercontent.com/13154631/107414024-b48ed980-6ace-11eb-9507-5f97e02c8b7c.png">
The same issue happens here (and perhaps other pages, too): https://amber-md.github.io/pytraj/latest/cookbook.html, also also under "Try pytraj online" (http://mybinder.org/assets/images/logo.svg)
<img width="172" alt="image" src="https://user-images.githubusercontent.com/13154631/107414077-c2445f00-6ace-11eb-945f-3f01dfa49c62.png">

Questions/requests:
1) Is it possible to join 2 traj objects? I didn't see this option in either the documentation or the pytraj code. The reason I'm looking for it is that I want to join two trajectories with different frame slices. Right now, I process the two (or more) files separately, save them, and then iterload them both (with all frames, since they have already been processed). Clearly it would be more efficient to only have to read each file only once, and this work around has them read twice.

2) Is it possible to modify a traj topology to specify that it has a pbc? My set of dcd files with LAMMPS and CHARMM-style psfs do not indicate that they have orthorhombic PBCs so load as "No PBC", but they do contain unit cell information. I'm not sure this is necessary since the images are unwrapped in the dcds, so I think the properties I'm calculating (e.g. radius of gyration) are being properly calculated. If I could see if the properties differed if cpptraj knows about the PBC, it would provide some additional confidence. 

Thanks!

**Comment by hainm** [comment]
hi @hmayes again,

> FYI: an image is not loading correctly on the documentation page,

Thanks. Noted.

1. 
> Is it possible to join 2 traj objects?

Here is the easiest way given your description. The example is from the docs of `pytraj.iterload`:
```python
traj = pt.iterload(['traj0.nc', 'traj1.nc'], '2koc.parm7', frame_slice=[(0, 10), (0, -1)])
```

**Comment by hainm** [comment]
2.
> Is it possible to modify a traj topology to specify that it has a pbc? My set of dcd files with LAMMPS and CHARMM-style psfs do not indicate that they have orthorhombic PBCs so load as "No PBC", but they do contain unit cell information. 

You can try below code:
```
In [12]: traj = pt.iterload('./tz2.nc', 'tz2.parm7')

In [13]: print(traj.top.box)
<Box: nobox, (x, y, z, alpha, beta, gamma) = (0.0, 0.0, 0.0, 0.0, 0.0, 0.0)>

In [14]: traj.top.box = pt.core.Box([1,2,3,4,5,6])

In [15]: print(traj.top.box)
<Box: nonortho, (x, y, z, alpha, beta, gamma) = (1.0, 2.0, 3.0, 4.0, 5.0, 6.0)>
```

**Comment by hainm** [comment]
Per 2: Another suggestion is to use [parmed](https://github.com/ParmEd/ParmEd) to read your psf file and edit anything you want.

Then.

```
parm = parmed.load_file("your.psf")
# edit here
parm.save("new.psf") # or parm.save("new.parm7") # amber format

traj = pt.iterload("your.dcd", top="new.psf")
# do something here
```

**Comment by hmayes** [comment]
many thanks for all your responses!

**Comment by hainm** [comment]
Close this issue now. Feel free to open others. Cheers.
