### ISSUE TITLE
mindist stops working when called multiple times

### ISSUE THREAD

**Issue by hherce** [Amber-MD/pytraj#1572]
I am using a for loop to analyze a the minimum distance of a series of individual atoms to a group. I am doing it in the following manner:

```python
alldist = []
for j in range(40):
	dist = []
	frame_indices = [j]
	traj0 = pt.load('tmp.trr', 'tmp.pdb', frame_indices=frame_indices)
	for i in resatoms:
		dist.append(pt.mindist(traj0,':RES&@'+i+' @1-242')[0])
	alldist.append(dist)
```

It runs fine until the loop reaches 21 frames (j=21) and gets stuck there. The problem is specifically with pt.mindist. I could stop the calculation and try to run again the distances for j=1 and it wont do it, I need to restart python for mindist to work again. I also run j=21 just to be sure that there is nothing wrong with the trajectory itself. Is it possible that mindist contains a variable that keeps increasing with each iteration of the function and this ends up saturating my computer memory? I would also appreciate if you could let me know a way around it while you fix the code.
Thanks!
Henry

**Comment by hherce** [comment]
I am almost sure that it is a memory issue, if I reduce the number of atoms in resatoms by half, the loop hangs now in frame 35.

**Comment by hainm** [comment]
thanks @hherce  for your report. I can reproduce the issue with below code (to use pytraj's data):

```python
import pytraj as pt


alldist = []
resatoms = range(10)

for j in range(40):
    dist = []
    frame_indices = [j]
    traj0 = pt.load('tz2.nc', 'tz2.parm7', frame_indices=frame_indices)
    for i in resatoms:
        dist.append(pt.mindist(traj0,':2 :3')[0])
    alldist.append(dist)

print(alldist)
```

**Comment by hainm** [comment]
I am investigating now.

**Comment by hherce** [comment]
Awesome! just let me know if you have any questions.
Thanks!
Henry

**Comment by hainm** [comment]
@hherce Please turn off the `capture_stdout`, which is problematic:

```
import pytraj as pt
from contextlib import contextmanager


class Dummy:
    def __enter__(self):
        return self

    def __exit__(self):
        return

    def read(self):
        return ""


@contextmanager
def mock_capture():
    yield Dummy(), ""

pt.analysis.c_action.capture_stdout = mock_capture


alldist = []
resatoms = range(40)

for j in range(40):
    dist = []
    frame_indices = [j]
    traj0 = pt.load('tz2.nc', 'tz2.parm7', frame_indices=frame_indices)
    for i in resatoms:
        dist.append(pt.mindist(traj0,':2 :3')[0])
    alldist.append(dist)

print(alldist)
```

Related issues: 
1. https://github.com/Amber-MD/pytraj/issues/1498#issuecomment-558360392
2. https://github.com/Amber-MD/pytraj/issues/1569

**Comment by hherce** [comment]
Great! Thanks so much! It seems that is working now and I would have never figured out a way around this.
Thanks again and best regards,
Henry
