### ISSUE TITLE
H bonds analysis

### ISSUE THREAD

**Issue by IsmaheneMesbah** [Amber-MD/pytraj#1576]
Hi,

I have generated a Heatmap representing the number of H bonds vs Frames. I want to track the residue number that the H bond comes from, I have been looking in the doc and I could not find a function that enables that. am I missing something? It is possible to get the residue numbers for each H bond ? 

```
traj = pt.load(xtc_file, pdb_file)
hbonds = pt.search_hbonds(traj)

hbonds_values= hbonds.values

heat_map = sns.heatmap(hbonds_values,vmin=0, vmax=1, cmap='Blues')

heat_map.set(xlabel='Frames', ylabel='N of H')
```

Thank you.

Best,

**Comment by hainm** [comment]
hi @IsmaheneMesbah, you can use `d = hbonds.data.to_dict()`
`1` - Yes
`0` - No
for each frame and each pairs.

```
In [15]: hbonds = pt.hbond(pt.datafiles.load_trpcage())

In [16]: 

In [16]: d = hbonds.data.to_dict()

In [17]: list(d.keys())
Out[17]: 
['total_solute_hbonds',
 'ASN1_O-GLN5_N-H',
 'ARG16_O-TRP6_NE1-HE1',
 'TYR3_O-LEU7_N-H',
 'ILE4_O-LYS8_N-H',
 'LEU7_O-GLY10_N-H',
 'ASP9_O-SER14_OG-HG',
 'SER14_O-ARG16_N-H',
 'ASP9_OD2-ARG16_NH1-HH12',
 'ASP9_OD2-ARG16_NH2-HH22',
 'LEU2_O-TRP6_N-H',
 'GLN5_OE1-LYS8_NZ-HZ1',
...
]
```

**Comment by IsmaheneMesbah** [comment]
Thank you. 
Please, How do you give the indexes to the H-bonds? Are these indexes obtained in `hbonds.values ` matrix based on occupancy of the bond? 

Thank you

```
hbonds = pt.search_hbonds(traj)

## # get raw data, ndarray with shape=(n_hbonds+1, n_frames)

hbonds_values= hbonds.values

```

**Comment by hainm** [comment]
Please try my example first then you can understand.
