### ISSUE TITLE
search_neighbors

### ISSUE THREAD

**Issue by tienmng** [Amber-MD/pytraj#1578]
Hello!

I am wondering if pytraj.search_neighbors considers those distances that are larger than half of the box for pbc?

I have this question because I realized that I have to add "image=True" when using pytraj.distance() for distances to be treated with pbc. Pytraj.search_neighbors doesn't have this argument.

Thank you!

**Comment by hainm** [comment]
hi @tienmng: May be trying `autoimage` first before using `search_neighbors`

**Comment by tienmng** [comment]
Thanks! I will try autoimage with search_neighbors.
