### ISSUE TITLE
Convert dcd and pdb to .np and .parm7 file

### ISSUE THREAD

**Issue by TianmingQu** [Amber-MD/pytraj#1582]
Dear all,
How can I convert the dcd and pdb file to the .np and .parm7 file I need to use in pytraj?

**Comment by TianmingQu** [comment]
Thanks! So then I can follow the instructions to do pca analysis with this dcd file directly, is this correct?

**Comment by hai-schrodinger** [comment]
> Also another question is that, can pytraj be used to do cavity volume analysis in protein MD simulation? Sorry for my so many questions😰

I don't think so. Alternatively, you can use `mdanalysis` or `mdtraj` to see if they can.
