### ISSUE TITLE
mass-weighted PCA: Eigenvalue Dimension and Descending Order

### ISSUE THREAD

**Issue by igordub** [Amber-MD/pytraj#1586]
Hi, there

I've performed carbon-alpha PCA analysis on my simulations data using `pytraj.pca` function.
I'm only interested in the resulting eigenvalues, but they don't appear in the format I expect them to be:
```
524.00180
115.00595
76.08004
...
```
First of all, the values are of a too-large magnitude. Secondly, the eigenvalues are decreasing with the mode number.
In `pytraj` PCA tutorial ([here](https://amber-md.github.io/pytraj/latest/tutorials/tutorial_pca.html)), the first two eigenvalues are in decreasing order:
```
eigvenvalues of first two modes [ 1399.36472919   240.42342439]
```

When I performed PCA using [this](https://amberhub.chpc.utah.edu/introduction-to-principal-component-analysis/) `cpptraj` tutorial, I received excepted results.
Here is the code:
```
parm complex.no_water.prmtop
trajin traj.no_water.nc

rms first :*&@CA=
average crdset structure-average
createcrd structure-trajectories
run

crdaction structure-trajectories rms \ 
  ref structure-average :*&@CA=
  
crdaction structure-trajectories matrix mwcovar \
  name structure-covar :*&@CA=

runanalysis diagmatrix structure-covar out eigmodes.dat \
  vecs 1197

go
```
The first three eigenvalues from `cpptraj` PCA:
```
1.05365
2.24907
2.76520
...
```

My questions are:
- What is the dimension of eigenvalues produced by `pytraj.pca`?
- Does/can it perform mass-weighted PCA?
- Why eigenvalues are decreasing as the mode number increases?

Thank you very much in advance!
Igor

**Comment by hainm** [comment]
hi @igordub  I need to double check. Cheers.

**Comment by hainm** [comment]
hi @igordub again, if you change `mwcovar` keyword to `covar`, you should get the same results between cpptraj and pytraj. 

> What is the dimension of eigenvalues produced by pytraj.pca?

1D array with len = n_vecs

> Does/can it perform mass-weighted PCA?

`pytraj` does not support yet.

> Why eigenvalues are decreasing as the mode number increases?

cpptraj gives order too if using `covar`. Please see the the attached output from `cpptraj`. I am using our toy `tz2.nc`, `tz2.parm7 system, change 'mwcovar` to `covar` keyword  and change `vecs 1197` to `vecs 5`

[eigmodes.txt](https://github.com/Amber-MD/pytraj/files/7590699/eigmodes.txt)

Let  me know if I miss any of your questions. Cheers.

**Comment by hainm** [comment]
[pca_mw.txt](https://github.com/Amber-MD/pytraj/files/7590796/pca_mw.txt)

@igordub Please use the `pca_mw` function in attached file. It should give you exact output from cpptraj. 
(You need to rename `.txt` -> `.py`)

**Comment by igordub** [comment]
@hainm Thank you for your time!

`pca_mw` does the job! It will make my analysis all in Pyhton and more coherent.

Regarding dimensions:
Actually, I meant physical dimensions/units. In the [manual](https://amberhub.chpc.utah.edu/diagmatrix/) states:
> Eigenvalues are given in cm^{-1} in the case of a mass-weighted covariance matrix and in the units of the matrix elements in all other cases. 

Now, when mass-weighting is applied in `pca_mw`, these are the units. I guess the choice of units determines the actual magnitude of the eigenvalue. Thus, they can ascend or descend with increasing mode numbers.

One more thing.
`get_reference` module is missing in `pca_mw.txt`. I've created a [gist](https://gist.github.com/igordub/0f96b0b5d5fdf67840cefa673a5accae) for the function.

Cheers.

**Comment by igordub** [comment]
Just noticed a little issue with `pca_wmw`.

When using `n_vencs=-1` option to print all eigenvalues, 6 unphysical eigenvalues appear at the end of the array.
At the moment, I'm solving this by specifying the total number of the real eigenvalues.
