### ISSUE TITLE
Atom mask selection not working for TrajectoryIterator

### ISSUE THREAD

**Issue by igordub** [Amber-MD/pytraj#1587]
Hello,

I'm trying to load trajectories without water into memory using [this](https://github.com/Amber-MD/pytraj/blob/master/examples/example_strip_solvent.py) example.

When I attempt to mask water the program runs forever until I interrupt it and the following error message occur:
```
Traceback (most recent call last):
  File "analyse_traj.py", line 23, in <module>
    traj = traj_water['!:WAT']
  File "pytraj/trajectory/c_traj/c_trajectory.pyx", line 314, in pytraj.trajectory.c_traj.c_trajectory.TrajectoryCpptraj.__getitem__
NotImplementedError: not supported keyword !:WAT
```

Package versions:
```
pytraj                    2.0.6
python                    3.7.11
```

Thanks

**Comment by hainm** [comment]
hi @igordub Can you please post your code?

**Comment by igordub** [comment]
@hainm my apologies,
Everything works fine! I didn't wait long enough for water to strip, considering the large number of frames I have.
