### ISSUE TITLE
Not Compatible with Python >3.8?

### ISSUE THREAD

**Issue by hl2500** [Amber-MD/pytraj#1591]
Hello,
I was trying to install Pytraj with conda on M1 Mac, but it seemed pytraj would only be compatible with python version <3.8. However, M1 Mac can only install python > 3.8. Is there a way I can still install pytraj? Thank you!

**Comment by hainm** [comment]
> Hello, I was trying to install Pytraj with conda on M1 Mac, but it seemed pytraj would only be compatible with python version <3.8. However, M1 Mac can only install python > 3.8. Is there a way I can still install pytraj? Thank you!

hi @hl2500: You can install `pytraj` by one of the following:
- Install `AmberTools`:  `conda install -c conda-forge ambertools=21 compilers`
(See `Option 2: Binary distribution via conda` in https://ambermd.org/GetAmber.php)
- Install from source code: https://amber-md.github.io/pytraj/latest/installation.html#from-source-code-easy-way-linux-osx

Let me know if you have any further issue. Cheers.

**Comment by hl2500** [comment]
Thank you for the suggestion! 
I tried the first option, but ambertools package was not available from the channels of miniforge (arm64).
I also tried the second one, it worked.

**Comment by hl2500** [comment]
Can I ask if I need to keep the source code cloned from github after the installation?

**Comment by hai-schrodinger** [comment]
> Can I ask if I need to keep the source code cloned from github after the installation?

You don't need the source code but you do need the `libcpptraj` in `pytraj/cpptraj/lib` folder.

**Comment by hainm** [comment]
> I tried the first option, but ambertools package was not available from the channels of miniforge (arm64).

Why didn't you try the `conda-forge` channel in the command I showed?

**Comment by hl2500** [comment]
I was using that command, but it said:
```
PackagesNotFoundError: The following packages are not available from current channels:

  - ambertools=21

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

```

**Comment by hainm** [comment]
> Build on M1 / osx-arm64 conda-forge/ambertools-feedstock#77

I see. There is an work-in-progress to build AmberTools for this arch too: https://github.com/conda-forge/ambertools-feedstock/issues/77

**Comment by hl2500** [comment]
Thank you so much for the information! Hopefully it will be available soon.
