### ISSUE TITLE
Print out the PCs in PCA results

### ISSUE THREAD

**Issue by TianmingQu** [Amber-MD/pytraj#1592]
Hi, I am trying to save the PCA results (saved in "data") into a text file, I use the np.savetxt() but some error comes out, could someone help me with this?

  (File "/Users/TMQ/venv/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1375, in savetxt
    raise ValueError('fname must be a string or file handle')
ValueError: fname must be a string or file handle)

**Comment by hainm** [comment]
numpy.savetxt(“your_filename.txt”, data)

Is that your command-like?

**Comment by hainm** [comment]
> ValueError: fname must be a string or file handle

This indicates your arguments were in the wrong order.
