### ISSUE TITLE
What does the data print out from command pt.matrix.dist(traj,'@CA') represent?

### ISSUE THREAD

**Issue by TianmingQu** [Amber-MD/pytraj#1594]

**Comment by TianmingQu** [comment]
the data length equals to the number of CA atoms in the pdb file, i am confused about what these data represent?

**Comment by hainm** [comment]
> the data length equals to the number of CA atoms in the pdb file, i am confused about what these data represent?

Hi, per @drroe explained: `The values are the average distance between the given atom pair over all frames.`

http://archive.ambermd.org/201406/0073.html
