### ISSUE TITLE
Energy analysis with PBSA

### ISSUE THREAD

**Issue by thepoole** [Amber-MD/pytraj#1605]
When using the pytraj.esander for pbsa calculations (i.e., igb=10, or with mm_options, ipb>0), the second time it runs there is a memory allocation error leading to a total crash.

I provide here a minimum example using the test trajectory. 

`import pytraj as pt
from pytraj.testing import get_fn
import sander

## Sander options
options = sander.gas_input(8)
options.igb = 0
options.ipb = 2

## Example trajectory
fn, tn = get_fn('ala3')
traj = pt.Trajectory(fn, tn)

## execution using mm_options
first=pt.esander(traj=traj, mm_options=options)
second=pt.esander(traj=traj, mm_options=options)

## alternative execution using igb=10

first=pt.esander(traj=traj, igb=10)
second=pt.esander(traj=traj, igb=10)`

**Comment by hainm** [comment]
Thanks @thepoole for your report.

**Comment by hainm** [comment]
hi @thepoole 
I already replied to you in the maillist but this is for the record:

```
Oh you need a proper prmtop file for that. So you need to prepare it via Leap

Here is an example (I have not validated the result yet, just want to make sure the code runnable)

In [1]: import pytraj as pt

In [3]: traj = pt.iterload("./Tc5b.crd", "Tc5b.prmtop")

In [4]: pt.esander(traj, igb=10) # or: pt.esander(traj, prmtop='Tc5b.prmtop', igb=10)
The data is in here: https://github.com/Amber-MD/pytraj/tree/master/tests/data
```
