### ISSUE TITLE
Mask selection on topology causes memory leak

### ISSUE THREAD

**Issue by tonyyzy** [Amber-MD/pytraj#1615]
```
top = traj.top
while True:
    top[":1"]
```
This would lead to crashes by using up all system memory.

On pytraj 2.0.6

**Comment by tonyyzy** [comment]
Note that `top.atom(0)` leaks memory as well

**Comment by hainm** [comment]
Thanks @tonyyzy for your reports. It's been a while seeing you.

**Comment by hainm** [comment]
@tonyyzy I think @hichiaty fixed the issue in master branch in #1617 

Cheers

**Comment by tonyyzy** [comment]
Thanks both! @hainm @hichiaty
