### ISSUE TITLE
Typo in Output of _explain() Function

### ISSUE THREAD

**Issue by bdemir09** [Amber-MD/pytraj#1623]
Hi, I noticed a small typo in the output of the `_explain()` function. The current output is: `[title] Base pair step tilt.`, but it should be `[tilt] Base pair step tilt.`
Thanks!

**Comment by hainm** [comment]
> Hi, I noticed a small typo in the output of the `_explain()` function. The current output is: `[title] Base pair step tilt.`, but it should be `[tilt] Base pair step tilt.` Thanks!

Dear @bdemir09: Thank you very much. I've pushed the fix to master here: https://github.com/Amber-MD/pytraj/commit/03f5c1bfcb66dfb1fc5189f28be44d6bbc86c57a

@drroe I copied the docs from cpptraj many years ago, I hope you already fixed that in cpptraj. Cheers. 
https://github.com/Amber-MD/pytraj/blob/3d844a45bbbcee64d7ebfd1902b00cff6a9c9172/pytraj/analysis/nucleic_acid_analysis.py#L236-L265
