### ISSUE TITLE
energy_decompostion throws "Fortran runtime error: Bad value during integer read"

### ISSUE THREAD

**Issue by spadavec** [Amber-MD/pytraj#1630]
I ran a very short apo run of MD using OpenMM and am trying to use the energy_decomposition function:

```py
import pytraj


traj = pytraj.iterload('output/Jnk1_apo_traj.nc',
                       'output/Jnk1_apo_minimised.pdb')


data = pytraj.energy_decomposition(traj, igb=6)
print(data)
```
But it throws this error:

```
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
At line 120 of file /home/conda/feedstock_root/build_artifacts/ambertools_1661778975619/work/AmberTools/src/sander/rdparm.F90 (unit = 8, file = '/home/user/project/JamaisVu/output/Jnk1_apo_minimised.pdb')
Fortran runtime error: Bad value during integer read


```

Any ideas on how to get around this?

**Comment by hainm** [comment]
> Any ideas on how to get around this?

@spadavec You need to generate a legit AMBER's topology file (e.g: which has the force field information).
So this `energy_decomposition` is only helpful if you're comfortable with AMBER.
