### ISSUE TITLE
ModuleNotFoundError: No module named 'pytraj.core.topology_objects'

### ISSUE THREAD

**Issue by JSurayut** [Amber-MD/pytraj#1637]
Hello, I want to use pytraj for my research but when I run on jupyter or in terminal. It shows "ModuleNotFoundError: No module named 'pytraj.core.topology_objects'", Please advice me how to fix it. Thank you

**Comment by hainm** [comment]
hi @JSurayut, how did you install pytraj? 
(e.g: you can install AmberTools that includes pytraj: https://ambermd.org/GetAmber.php)

**Comment by JSurayut** [comment]
Hello, Mr. Hai Nguyen

 I installed pytraj by using AmberTools

เมื่อ อ. 8 ส.ค. 2566 เวลา 21:50 Hai Nguyen ***@***.***>
เขียนว่า:

**Comment by JSurayut** [comment]
No, I have checked in my folder that I opened jupyter, It  does not have any pytraj source code.

**Comment by hainm** [comment]
um, that's odd. can you try `import parmed; print(parmed)` to see if that works?

**Comment by hainm** [comment]
Your issue is similar to #1565

**Comment by JSurayut** [comment]
> 

I try this and it shows the messege
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-37ea80baaced> in <module>()
----> 1 import parmed; print(parmed)

/home/cadd/amber22/lib/python3.10/site-packages/parmed/__init__.py in <module>()
     19 
     20 from . import exceptions, periodic_table, residue
---> 21 from . import unit, utils
     22 from .topologyobjects import *
     23 from .structure import Structure, StructureView

/home/cadd/amber22/lib/python3.10/site-packages/parmed/utils/__init__.py in <module>()
      2 from ..exceptions import MoleculeError as _MoleculeError
      3 from .pairlist import find_atom_pairs
----> 4 from ..topologyobjects import Atom
      5 from shutil import which
      6 from typing import List, Set, Tuple

/home/cadd/amber22/lib/python3.10/site-packages/parmed/topologyobjects.py in <module>()
      7 import enum
      8 import math
----> 9 from functools import cached_property
     10 from typing import Optional
     11 import warnings

ImportError: cannot import name 'cached_property'

**Comment by JSurayut** [comment]
> um, that's odd. can you try `import parmed; print(parmed)` to see if that works?

I try this and It show a message

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-17-489948254972> in <module>()
----> 1 import parmed

/home/cadd/amber22/lib/python3.10/site-packages/parmed/__init__.py in <module>()
     19 
     20 from . import exceptions, periodic_table, residue
---> 21 from . import unit, utils
     22 from .topologyobjects import *
     23 from .structure import Structure, StructureView

/home/cadd/amber22/lib/python3.10/site-packages/parmed/utils/__init__.py in <module>()
      2 from ..exceptions import MoleculeError as _MoleculeError
      3 from .pairlist import find_atom_pairs
----> 4 from ..topologyobjects import Atom
      5 from shutil import which
      6 from typing import List, Set, Tuple

/home/cadd/amber22/lib/python3.10/site-packages/parmed/topologyobjects.py in <module>()
      7 import enum
      8 import math
----> 9 from functools import cached_property
     10 from typing import Optional
     11 import warnings

ImportError: cannot import name 'cached_property'

**Comment by freeenergylab** [comment]
I encountered the same problem. Now AmberTools22 will download and install python 3.11 version miniconda. When the pytraj module is compilered, the following error appeared: 
![bug](https://github.com/Amber-MD/pytraj/assets/9461715/9d779e07-8d59-4f6f-bafe-05a5e6cc6c61)
However, when I used python 3.9 in my own conda enviroment, the pytraj can be installed successfully.

**Comment by hainm** [comment]
Pleaser try ambertools 23
Ps: it’s not same issue

Cheers

**Comment by freeenergylab** [comment]
Thanks, Hai Nguyen. I can compile ambertools23 successfully where I noticed one update.3 you patched for AmberTools23.
And I noticed that you have fixed the compatibility issue between Python 3.11 and CPython for pytraj. Nice work! Cheers!

**Comment by JSurayut** [comment]
> 

```
sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
['', '/home/cadd/amber22/lib/python3.10/site-packages', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3/dist-packages/IPython/extensions', '/home/cadd/.ipython']
```

**Comment by hainm** [comment]
Your jupyter notebook comes from python 3.6 but the one in amber is 3.10

**Comment by JSurayut** [comment]
> Your jupyter notebook comes from python 3.6 but the one in amber is 3.10

What should I do, could you give me some advice please?

**Comment by hainm** [comment]
it's hard to tell you what do to if I don't know the detail.

Basically:
- which python path did you use to compile ambertools? how (exactly) did you run jupyter? 
- saying you find it, source the amber.sh as the manual suggested, then run `/path/to/python3 -m jupyter notebook`
- in the notebook, `import sys; print(sys.version); print(sys)` to make sure you are using the correct python path?
