### ISSUE TITLE
Function to find the atoms of a given mask that appear in a region of xyz coordinate space?

### ISSUE THREAD

**Issue by sastrys1** [Amber-MD/pytraj#1640]
The frame.atom() function returns the xyz coordinates of a given atom. I wrote a method to do the inverse - given xyz coordinates, find the closest atom. Or, given a voxel with center (x, y, z) and width/height/length delta, find all water molecules that appear in that voxel for a given frame. 

This was really helpful for me to do residence time analysis for particular parts of my protein interface that were buried - we wanted to see how long the water molecules were residing in those areas (see section 3.5 of [this paper](https://pubs.acs.org/doi/epdf/10.1021/jp020100m)).

This sort of analysis ties in really well with GIST - I used GIST to find the voxels in the protein with the lowest entropy (aka waters that were not able to move around much) then found the frame-by-frame decay in the amount of waters that were present in frame 1 using the voxel centers that I got from GIST.

Would this be a useful function in pytraj? If so, should I just clone the repo and make a PR?

Thanks for this tool, I really love using pytraj!!

**Comment by hainm** [comment]
> Would this be a useful function in pytraj? If so, should I just clone the repo and make a PR?

Dear @sastrys1, feel free to make a PR. I will be happy to review it. Thanks.

> Thanks for this tool, I really love using pytraj!!

Sweet. I am glad that `pytraj` is useful. Cheers.

**Comment by sastrys1** [comment]
@hainm Do you have any advice on how to run pytraj with the changes I've made and then run the test code? I'm not able to build pytraj using the `python setup.py install` command because the libcpptraj installation is failing. Do I need to be able to build the entire thing to test changes?

**Comment by hainm** [comment]
>  Do I need to be able to build the entire thing to test changes? 

yeah, I think so. Otherwise, you can update the source code in the install path directly and make a PR here for CI to test.

> because the libcpptraj installation is failing.

what's the error?

**Comment by sastrys1** [comment]
This is the error:
`Error: LAPACK/BLAS build/link failed: g++  -Wall -fopenmp -O3  -fPIC   -std=gnu++11 -o testp testp.cpp -L/gstore/apps/imkl/2021.4.0/mkl/2021.4.0/lib/intel64/lib -llapack -L/gstore/apps/imkl/2021.4.0/mkl/2021.4.0/lib/intel64/lib -lblas -lgfortran -lpthread  -fopenmp  
Error: Error message follows:
Error: /gstore/apps/binutils/2.37-GCCcore-11.2.0/bin/ld.gold: error: cannot find -llapack
/gstore/apps/binutils/2.37-GCCcore-11.2.0/bin/ld.gold: error: cannot find -lblas
/local/tmp/ccQzyy18.o:testp.cpp:function main: error: undefined reference to 'dsyev_'
/local/tmp/ccQzyy18.o:testp.cpp:function main: error: undefined reference to 'dgemm_'
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/gstore/scratch/u/sastrys1/pytraj/scripts/install_libcpptraj.py", line 225, in <module>
    install_libcpptraj(compiler, build_flag, args.j)
  File "/gstore/scratch/u/sastrys1/pytraj/scripts/install_libcpptraj.py", line 173, in install_libcpptraj
    subprocess.check_call(cm, shell=True)
  File "/gstore/apps/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bash configure --requires-flink -shared -noarpack --with-blas=/gstore/apps/imkl/2021.4.0/mkl/2021.4.0/lib/intel64 --with-lapack=/gstore/apps/imkl/2021.4.0/mkl/2021.4.0/lib/intel64 --with-bzlib=/gstore/apps/Python/3.9.6-GCCcore-11.2.0 --with-zlib=/gstore/apps/Python/3.9.6-GCCcore-11.2.0  -amberlib -openmp  -nosanderlib gnu' returned non-zero exit status 1.
`

**Comment by hainm** [comment]
thanks @sastrys1 for the report.
FYI that here is how we build  libcpptraj and pytraj in github action: https://github.com/Amber-MD/pytraj/blob/f3cbb051f71e15d3f2b4b0d3422d4a4bfcab68e0/.github/workflows/python-package-conda.yml#L47-L55

List of dependency: https://github.com/Amber-MD/pytraj/blob/f3cbb051f71e15d3f2b4b0d3422d4a4bfcab68e0/.github/workflows/python-package-conda.yml#L14-L22

**Comment by sastrys1** [comment]
Decided to just make direct changes to my conda `pytraj` repo and test them, and then commit them. Does simply pushing to my forked repo trigger a travis build?

**Comment by hainm** [comment]
Hi

Please make a PR to master branch of this repo. Add WIP (work in progress)
if needed. Cheers.

**Comment by sastrys1** [comment]
Made a PR. Thanks for the help.

**Comment by hainm** [comment]
Thanks. Let's move our discussion to there #1641 then.

**Comment by hainm** [comment]
oh, for the record: 

you can copy the existing libcpptraj.so{dylib} from the installed pytraj to $CPPTRAJHOME/lib (CPPTRAJHOME points to source folder of cpptraj). Doing this way you don't need to rebuild cpptraj. (pytraj only needs `libcpptraj` and the header files (.h)).
