### ISSUE TITLE
How do I import pytraj?

### ISSUE THREAD

**Issue by d-beltran** [Amber-MD/pytraj#1652]
Hi everyone,

According to the install docs:

> The best way is to install AmberTools via conda: conda install -c conda-forge ambertools compilers

I have done this and the installation was fine. However now I don't see how to import pytraj.

Sorry for the naive question!

**Comment by hainm** [comment]
Dear @d-beltran 

you can try `python3 -c 'import pytraj'`

**Comment by hainm** [comment]
If you have seen this (old) docs yet, please do: https://amber-md.github.io/pytraj/latest/tutorials/basic_examples.html#how-to-run-pytraj

Cheers

**Comment by d-beltran** [comment]
![logs](https://github.com/Amber-MD/pytraj/assets/44979434/7c96e82b-77a9-4c52-960c-0d324709395b)

**Comment by d-beltran** [comment]
It turns out there was some problem with mamba
I have reinstalled everything and now it works :)

Sorry and thank you for your time @hainm
