### ISSUE TITLE
basic example: Nucleic acid analysis

### ISSUE THREAD

**Issue by hainm** [Amber-MD/pytraj#471]
to prepare for official pytraj-doc website.

**Comment by hainm** [comment]
### Nucleic acid analysis

* this is extension of `nastruct` in cpptraj (http://ambermd.org/doc12/Amber15.pdf, check page 580)

```python
In [10]: import pytraj as pt
In [11]: fn = "./data/Test_NAstruct/adh026.3.pdb"
In [12]: traj = pt.load(fn, fn)
In [13]: d = pt.nucleic_acid_analysis(traj)

# install pandas to have pretty print-output (but not require for getting the data)
In [14]: d
Out[14]:
<pytraj.DatasetList with 172 datasets>
                             0           1           2
10G_pucker           18.906134    8.333423  354.677490
11G_pucker            6.072000   11.830161   10.424721
12C_pucker           15.345373   12.297361    0.480747
13G_pucker            6.682173  349.733398  343.851074
14C_pucker          352.914276  342.529724    9.121806
15C_pucker           13.196464   12.002340  359.133850
16C_pucker           21.746746   25.864700   37.439262
1G16C-2G15C_hrise     2.590746    2.869499    3.338340
1G16C-2G15C_htwist   35.951202   33.729923   36.290562
1G16C-2G15C_incl     15.127589    0.892145    3.533539
...                        ...         ...         ...
8C9G_hb               3.000000    3.000000    3.000000
8C9G_major            0.000000    0.000000    0.000000
8C9G_minor           13.455721   13.534509   13.461015
8C9G_open            -4.289060   -2.248649    1.647909
8C9G_prop            -2.397790   -9.845123    2.761922
8C9G_shear            0.859477   -0.306150    0.208358
8C9G_stagger          0.049762    0.004518   -0.422324
8C9G_stretch         -0.316870   -0.126895    0.134625
8C_pucker            27.818029   18.278120   14.501503
9G_pucker             1.146623  355.287659    6.708812

[172 rows x 3 columns]
```

**Comment by hainm** [comment]
* major groove
```python
In [15]: d.groupby("major")
Out[15]:
<pytraj.DatasetList with 8 datasets>
                     0          1          2
1G16C_major   0.000000   0.000000   0.000000
2G15C_major  18.600122  18.828688  18.168209
3G14C_major  18.778240  19.093489  18.774485
4C13G_major  20.350521  19.568445  19.965651
5G12C_major  19.960869  19.295353  19.787498
6C11G_major  18.459402  18.866924  19.155964
7C10G_major  18.789431  18.897825  18.388203
8C9G_major    0.000000   0.000000   0.000000
```

* major and minor
```python
In [16]: d.groupby(['major', 'minor'])
Out[16]:
<pytraj.DatasetList with 16 datasets>
                     0          1          2
1G16C_major   0.000000   0.000000   0.000000
1G16C_minor  13.329270  13.320021  13.340877
2G15C_major  18.600122  18.828688  18.168209
2G15C_minor  13.403409  13.459188  13.537786
3G14C_major  18.778240  19.093489  18.774485
3G14C_minor  13.571599  13.632536  13.570624
4C13G_major  20.350521  19.568445  19.965651
4C13G_minor  13.258562  13.534414  13.611387
5G12C_major  19.960869  19.295353  19.787498
5G12C_minor  13.411052  13.319207  13.481220
6C11G_major  18.459402  18.866924  19.155964
6C11G_minor  13.266559  13.270662  13.290174
7C10G_major  18.789431  18.897825  18.388203
7C10G_minor  13.430545  13.427437  13.385428
8C9G_major    0.000000   0.000000   0.000000
8C9G_minor   13.455721  13.534509  13.461015
```

**Comment by hainm** [comment]
* inclination

```python
In [27]: d.groupby('incl')
Out[27]:
<pytraj.DatasetList with 7 datasets>
                          0          1          2
1G16C-2G15C_incl  15.127589   0.892145   3.533539
2G15C-3G14C_incl   5.539527  18.634190  14.693497
3G14C-4C13G_incl  10.479418   3.612189  11.229621
4C13G-5G12C_incl  14.252966  13.246187  11.480075
5G12C-6C11G_incl   1.662960  -8.385758  10.869900
6C11G-7C10G_incl  -8.911609  19.085766  -3.049505
7C10G-8C9G_incl   12.900895   5.658202  21.608931

In [28]: d.groupby('incl').mean() # for each pair in each frame
Out[28]:
array([  6.51775742,  12.95573807,   8.44040966,  12.99307632,
         1.38236701,   2.37488437,  13.38934326], dtype=float32)

In [29]: d.groupby('incl').mean(axis=0) # mean per frame
Out[29]: array([  7.29310608,   7.53470325,  10.05229378], dtype=float32)
```

**Comment by hainm** [comment]
* write datasetlist to json format so we can reload later or open by another program to create a dict

```python
In [32]: d.to_json("test_na.json")
```

* load back to python as a dict
```python
nadict = pt.read_json("test_na.json")
```

* rmsd with `@P` mask?
```python
In [40]: pt.rmsd(traj, '@P', ref=traj[-1])
Out[40]: array([ 0.73229993,  0.58531645,  0.        ])

In [41]: pt.rmsd(traj, '@P')
Out[41]: array([ 0.        ,  0.47314889,  0.73229993])
```

**Comment by hainm** [comment]
@swails  I am starting to import some commonly used actions to pytraj namespace + working on doc-website. And simplify the workflow in pytraj. It's great if you can have a look above example and let me know if users still struggle in using pytraj. thanks.

**Comment by swails** [comment]
Try leaving out the cute gizmos from your examples.  For instance, `to_json`, `from_json`, `groupby`, `apply`, `map`, ... etc.

For someone just getting started, like myself, that stuff is way too distracting.  My preference is to keep examples and tutorials clean from that kind of stuff, or put it at the end as an easter-egg; something like "and you can use `groupby` and `apply` to do this stuff quickly!".  But if people think they have to know all of those quick-tricks for wrangling data like a pandas expert does in order to use pytraj you'll scare everybody off. (*especially* since `groupby` in `DatasetList` isn't the same as `groupby` in pandas!)

Also see if you can organize the tutorials/examples in some kind of increasing complexity (http://mdtraj.org is a reasonable example) -- this lack of organization is what hurts the utility of your notebooks.

**Comment by hainm** [comment]
thanks for all advices. I always forget the real meaning of 'tutorial'.

I will try to follow `mdtraj` website, make things really simple. And might change 'groupby' to 'grepby' (which is similar to `grep` in unix).

**Comment by swails** [comment]
-1 on `grepby`; too similar to `groupby` that people will almost certainly conflate the two, misread "grep" as "group", or mistype.  It's also not really grouping the data, so `groupby` is a little misleading.  It's really just a regex selector as I understand it (unless you've changed the code in the past week or two for what `groupby` does), so why not something like `select` or `filter`?

People will ultimately get used to whatever you choose if they start using pytraj, but making DSL interchangeable with DataFrame but making DSL.groupby behave differently than DataFrame.groupby is just asking for trouble...

**Comment by hainm** [comment]
yeah, like I said before I named "groupby" in DSL because I misunderstood the meaning of `groupby` in pandas. So I intend to find a better (and non-confused) name.

currently DSL does have `filter` method, which behave like I am expecting, but user need to write a function to filter it.  

For example
```python
dslist.filter(lambda x : x.mean() < 50.)
```

do you think it's reasonable to combine both
```python
dslist.filter('psi') # create a new DSL (as view) having only datasets with 'psi' in legend
```

or just go ahead use `select`. 

thx.

**Comment by swails** [comment]
Could you get the same thing by doing something like

```Python
dslist.filter(lambda x: 'psi' in x.key)
```
?

**Comment by hainm** [comment]
@swails 
yes, your code is identical to `groupby` in pytraj
```python
In [4]: d0 = dslist.filter(lambda x : 'psi' in x.legend)
In [5]: d1 = dslist.groupby("psi")
In [8]: import numpy as np
In [9]: np.any(d0.values == d1.values)
Out[9]: True
```

My motivation to make `groupby` as a subset of `filter` because it's too long to type the function, and the `groupby` (`grep`) is commonly used to select the data (like the `nucleic acid example` above)

**Comment by swails** [comment]
`np.any` is the wrong choice, right?  Shouldn't it be `np.all`?

Anyway, if `groupby` is a special-case of `filter(lambda x: string in x.legend)`, I think it's reasonable to allow `filter` to behave like `groupby` does now if the argument is a string, and the way it currently does if it's `callable`.  But that's really up to you.

**Comment by hainm** [comment]
```python
In [28]: np.all(d0.values == d1.values)
Out[28]: True
```
d0.values and d1.values are 2D array.

I am still really confused about `any` and `all` in this case. seems that they are the same. 
https://docs.scipy.org/doc/numpy-1.5.x/reference/generated/numpy.any.html

> Anyway, if groupby is a special-case of filter(lambda x: string in x.legend), I think it's reasonable to allow filter to behave like groupby does now if the argument is a string, and the way it currently does if it's callable. But that's really up to you.

thanks. I will think about pick whether 'filter', 'grep' or 'select'.

Hai

**Comment by hainm** [comment]
oops. I see what `any` mean. damn.

Yes. It should be `all`.

**Comment by swails** [comment]
> oops. I see what any mean. damn.
> 
> Yes. It should be all.

;).  If I had a nickel for every time I got those two confused...
