### ISSUE TITLE
basic tutorial: moving_average and plot

### ISSUE THREAD

**Issue by hainm** [Amber-MD/pytraj#497]
```python
In [17]: import pytraj as pt

In [18]: dslist  = pt.calc_phi(traj)

In [19]: pt.tools.moving_average(dslist[0], 3).plot(show=True)
Out[19]: [<matplotlib.lines.Line2D at 0x2aaac5c065f8>]
```

**Comment by hainm** [comment]
TODO: assert the result

**Comment by hainm** [comment]
![test](https://cloud.githubusercontent.com/assets/4451957/8510826/be83e5b8-22ca-11e5-85d3-539cc07b478b.png)

**Comment by hainm** [comment]
@swails is this the `moving_average` or moving window average like you mentioned a while ago?

**Comment by swails** [comment]
What's the difference?
