### ISSUE TITLE
introduce traj(0, 10, 2, '@CA').xyz

### ISSUE THREAD

**Issue by hainm** [Amber-MD/pytraj#681]
Motivation: memory saving (vs traj[0:10:2, '@CA'].xyz)?

**Comment by hainm** [comment]
let's wait for @drroe to implement new Frame constructor (https://github.com/Amber-MD/cpptraj/pull/22). If he would, we don't need this method.

**Comment by drroe** [comment]
@hainm Can you open an issue for this in Amber-MD/cpptraj so we can keep track?

**Comment by hainm** [comment]
sure. I just did.
