### ISSUE TITLE
Cannot build pytraj

### ISSUE THREAD

**Issue by swails** [Amber-MD/pytraj#800]
I try the very simple `python setup.py install`.  This is what I get:

```
swails@batman ~/src/pytraj (master) $ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 145, in <module>
    raise RuntimeError('can not find libcpptraj in $CPPTRAJHOME/lib or ./cpptraj/lib folder. '
RuntimeError: can not find libcpptraj in $CPPTRAJHOME/lib or ./cpptraj/lib folder. You need to install ``libcpptraj`` manually. 
```

I thought it was supposed to download and install cpptraj for me?

**Comment by hainm** [comment]
I think you already has ./cpptraj folder. Currently ``pytraj`` only find ``libcpptraj`` in $CPPTRAJHOM/lib or ./cpptraj/lib. It only download cpptraj if there is not $CPTRAJHOMe or ./cpptraj/. Can you double-check?

I will update setup.py so user can specify dir for libcpptraj too (but not sure if it's a good idea or not since ``pytraj`` still need to find cpptraj's header files).

**Comment by swails** [comment]
Possibly, but the same thing happens even if I do a full git clean:

```
swails@batman ~/src/pytraj (master) $ git clean -fxd
Skipping repository cpptraj/
Removing scripts/__init__.pyc
Removing scripts/setup_for_amber.pyc
swails@batman ~/src/pytraj (master) $ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 145, in <module>
    raise RuntimeError('can not find libcpptraj in $CPPTRAJHOME/lib or ./cpptraj/lib folder. '
RuntimeError: can not find libcpptraj in $CPPTRAJHOME/lib or ./cpptraj/lib folder. You need to install ``libcpptraj`` manually. 
```

**Comment by hainm** [comment]
> Skipping repository cpptraj/

can you try delete it? `rm -rf ./cpptraj`?

**Comment by swails** [comment]
Ah, I didn't read it carefully enough.  `git clean -fxd` has never failed me before.  It must only be skipping `cpptraj/` because it is a git repository...

**Comment by hainm** [comment]
I am assuming that this problem is solved and go ahead closing it. Let me know if it is not. thanks.
