### ISSUE TITLE
Segmentation fault when loading Amber netCDF with velocities, forces

### ISSUE THREAD

**Issue by ctlee** [Amber-MD/pytraj#807]
A slightly atypical use case, but it seems that pt.io.load will segmentation fault if the netCDF trajectory contains velocities or forces.

**Comment by hainm** [comment]
hi,

does is happen with ``pt.iterload``?

if possible, can you send a small file so we can test? 

By the way, can you try to get the output of this:

```bash
$ python -c 'import pytraj as pt; pt.show_versions()'
```

thanks.

**Comment by drroe** [comment]
@ctlee Out of curiosity does cpptraj have any problem reading the trajectory?

**Comment by ctlee** [comment]
@hainm, it doesn't initially segmentation fault with `pt.iterload`, but does when I subsequently attempt to reference any frames or slice it. You can find a sample trajectory here (12MB):
https://dl.dropboxusercontent.com/u/2781671/waterbox.tgz
It's a simple box of tip3pf water with coordinates and velocities.

Here is the output of the pytraj and cpptraj versions:

`bash-4.2$ python -c 'import pytraj as pt; pt.show_versions()'
('pytraj version = ', '0.1.2.dev8')
('cpptraj version = ', u'V16.00b')
('cpptraj internal version = ', u'V4.2.4')
('cpptraj compiled flag = ', u' -DHASBZ2 -DHASGZ -DBINTRAJ -DNO_MATHLIB')`

@drroe, cpptraj has no problem reading the trajectory.

**Comment by hainm** [comment]
@ctlee this is a serious problem. I will try to debug it. thanks.

**Comment by hainm** [comment]
@ctlee what is the format of `system.prmtop`?  Can you double-check if it's corrupted when uploading to dropbox?

I can not open it. 

```python
In [1]: traj = pt.iterload('./trunc.nc', 'system.prmtop')
Error: Number of atoms in NetCDF file trunc.nc (5808) does not
Error:   match number in associated parmtop (0)!
```

open it by ``vim``, I got binary file:
```
^_<8b>^H^@^OÖùU^@^C¼üuXVQØî<8b>ÒÝ<8d>`
```

**Comment by ctlee** [comment]
@hainm whoops accidentally corrupted it, sorry, I posted a new version please try again!

**Comment by hainm** [comment]
thanks. I confirm that I reproduce the segmentation fault. Will work on this.

**Comment by hainm** [comment]
@ctlee 

We (with @drroe) just fix our code to work with velocity. Can you try again?

I recommend to use ``conda`` to install both ``pytraj`` and ``libcpptraj``. It takes < 30 seconds to install the most updated one. Please see info here: http://amber-md.github.io/pytraj/doc/build/html/installation.html#from-conda

This is what the output should look like

```python
In [5]: traj = pt.iterload('trunc.nc', 'system.prmtop')

In [6]: traj
Out[6]: 
<pytraj.TrajectoryIterator, 50 frames, include:
<Topology: 5808 atoms, 1936 residues, 1936 mols, PBC with box type = ortho>>
           

In [7]: traj[::2]
Out[7]: 
<pytraj.Trajectory, 25 frames, include:
<Topology: 5808 atoms, 1936 residues, 1936 mols, PBC with box type = ortho>>
           

In [8]: traj[1:20:2, '@O']
Out[8]: 
<pytraj.Trajectory, 10 frames, include:
<Topology: 1936 atoms, 1936 residues, 1936 mols, PBC with box type = ortho>>
           

In [9]: pt.radgyr(traj)
Out[9]: 
array([ 19.36357083,  19.38077041,  19.38671524, ...,  19.33767498,
        19.34773314,  19.33818008])

In [10]: for frame in traj: pass

In [11]: pt.iterchunk(traj, 4)
Out[11]: <generator object iterchunk at 0x2aaac5901048>

In [4]: traj._coordinateinfo
Out[4]: 
{'has_box': True,
 'has_force': False,
 'has_replcica_dims': False,
 'has_temperature': False,
 'has_time': True,
 'has_velocity': True}
```

**Comment by hainm** [comment]
if you want to install ``pytraj`` in harder way (for whatever reason), you should

* cd to_your_pytraj_folder
* git pull
* cd cpptraj
* git pull
* make libcpptraj
* cd ..
* python ./scripts/clean_cythonize_files.py
* python ./setut.py install

` to_your_pytraj_folder` is the root folder of pytraj, which have such folders like './tests', 'scripts', ...

**note** per your files in dropbox, I went ahead including them in our test folder. 

https://github.com/Amber-MD/pytraj/blob/master/tests/issues/test_issue807.py
If you don't want to make your files public, please let me know so I can take them down.

Thanks for your report.

**Comment by hainm** [comment]
uhm, it's likely that there is still segmentation fault with python 2.7. It's fine with python 3.

**Comment by ctlee** [comment]
@hainm I might have broken something in my environment with the update. I'm getting the following error:

bash-4.2$ python
Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, Sep 15 2015, 14:50:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pytraj as pt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/net/home/clee/anaconda/lib/python2.7/site-packages/pytraj/__init__.py", line 63, in <module>
    from .core.cpptraj_core import CpptrajState, ArgList, AtomMask
  File "pytraj/math/cpp_math.pxd", line 28, in init pytraj.core.cpptraj_core (pytraj/core/cpptraj_core.cpp:29852)
  File "/net/home/clee/anaconda/lib/python2.7/site-packages/pytraj/math/__init__.py", line 3, in <module>
    from .cpp_math import Vec3, Matrix_3x3, Grid, torsion, angle, distance_ as distance
ImportError: cannot import name torsion

Here's my LD_LIBRARY_PATH, which I think is setup ok to use the new cpptraj-dev:

bash-4.2$ echo $LD_LIBRARY_PATH
/net/home/clee/anaconda/pkgs/libcpptraj-dev-4.2.5-0/lib:/net/software/pkg/cuda/6.5/lib64:/net/software/pkg/cuda/6.5/lib:/net/software/pkg/openmpi/1.8.4/lib:/net/home/clee/.local/lib:

Please advise! Also, happy to contribute the test case to the git.

**Comment by hainm** [comment]
it's likely that there is still other (another) libcpptraj in another folder that not in LD_LIBRARY_PATH, sometimes conda env works weird.

Can you try 'locate libcpptraj.so' to list all files. If possible, delete them all and install libcpptraj again.

We have fresh installation on travis and all passed.

If possible, delete/uninstall all pytraj dir folders and redo the process. thanks.

this is example from my 'locate' command. Try to remove all old libcpptraj.so and install again.

```
haichit@casegroup ~/amber_conda/conda-recipes (master) $ locate  libcpptraj.so
/u1/haichit/anaconda3/envs/notebook-pytraj/lib/libcpptraj.so
/u1/haichit/anaconda3/envs/notebook-pytraj/lib/cpptraj/lib/libcpptraj.so
/u1/haichit/anaconda3/envs/python2/lib/cpptraj/lib/libcpptraj.so
/u1/haichit/anaconda3/envs/python3.3/lib/cpptraj/lib/libcpptraj.so
/u1/haichit/anaconda3/pkgs/libcpptraj-dev-4.2.5-0/lib/libcpptraj.so
/u1/haichit/anaconda3/pkgs/libcpptraj-dev-4.2.5-0/lib/cpptraj/lib/libcpptraj.so
/u1/haichit/pytraj_git/pytraj/cpptraj/lib/libcpptraj.so
/u1/haichit/test/pytraj/cpptraj/lib/libcpptraj.so
```

**Comment by hainm** [comment]
Another solution is to use conda to create an isolated environment (this is what conda is good for).

```bash
conda create -n try_pytraj python=2.7 numpy cython
source activate try_pytraj
# then install pytraj and libcpptraj
conda install -c ambermd pytraj-dev libcpptraj-dev
# try simple test to make sure pytraj working
python -c 'import pytraj as pt; pt.run_tests()'
```

this should work.

**Comment by hainm** [comment]
ah, if you don't have a strong reason to use python2.7,  I highly recommend to use python 3 (3.4 or 3.5). They are so much better python2, less tendency to have segmentation fault.

With your current anaconda, just
```
conda create -n py3 python=3.4 # and add a list of things you want, like numpy, cython, ...
source activate py3
conda install -c ambermd pytraj-dev libcpptraj-dev
```

**Comment by ctlee** [comment]
After reinstalling pytraj and libcpptraj it's working now! No issues with trajectory loading. Thanks

**Comment by hainm** [comment]
Great. enjoy.
