### ISSUE TITLE
build with PYTHON_VERSION=3.3

### ISSUE THREAD

**Issue by hainm** [Amber-MD/pytraj#817]
not sure why can not build with python3.3

https://travis-ci.org/hainm/pytraj/builds/81113358

**Comment by hainm** [comment]
conda issue?

**Comment by hainm** [comment]
don't mind. Why bother using py3.3?

**Comment by swails** [comment]
Did you look at the text of the Travis build? https://travis-ci.org/hainm/pytraj/jobs/81113360#L1042-L1045

It was a weird temporary problem of cloning cpptraj.  This failed, but the build script still continued.  I suspect Python 3.3 works just fine, it was just a weird git clone failure.

**Comment by hainm** [comment]
@swails yes, py3.3 works fine if 'python setup.py install' in traditional way, but I can not build pytraj by conda, enven in local machine. Always got blank tar file.
