### ISSUE TITLE
Error compiling core/brick.pyx

### ISSUE THREAD

**Issue by jmborr** [Amber-MD/pytraj#970]
When building with setup.py install

Error compiling Cython file core/brick.pyx (Cython version 0.21.1)

        return self.__str__()
    @property
    def element(self):
        name = get_key(self.thisptr.Element(), AtomicElementDict)
        return name, *Element[self.atomic_number]
                    ^

pytraj/core/brick.pyx:90:21: can use starred expression only as assignment target
Cythonizing pytraj/cpp_options.pyx
Cythonizing pytraj/cpptraj_dict.pyx
Cythonizing pytraj/cyutils.pyx
Cythonizing pytraj/datafiles/datafiles.pyx
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 977, in cythonize_one_helper
    return cythonize_one(*m[1:])
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 959, in cythonize_one
    raise CompileError(None, pyx_file)
CompileError: pytraj/core/brick.pyx
Cythonizing pytraj/datasets/DatasetList.pyx
Traceback (most recent call last):
  File "setup.py", line 270, in <module>
    compiler_directives=cython_directives,
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 831, in cythonize
    result.get(99999)  # seconds
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
Cython.Compiler.Errors.CompileError: pytraj/core/brick.pyx

**Comment by hainm** [comment]
Hi, I do not recognize that cython 0.21 does not support unpacking `*Element[self.atomic_number]`

I will fix it. Meanwhile, you can install the newest cython (0.23) to be able to install pytraj.

**Comment by jmborr** [comment]
Thanks for the fast reply. I was compiling in Fedora 20 but tomorrow I'm
upgrading to 22 which has cython 0.22 package. Is this version good enough
or must it be 0.23?
-Jose

**Comment by hainm** [comment]
It is better to make a fix.

And you 'git pull' and try again.

**Comment by hainm** [comment]
I meant I just pushed new change to work with cython0.21

**Comment by jmborr** [comment]
Thanks a million, it worked.

This module is going to forego my embarrassment of having to use cpptraj
through os.system :D

**Comment by hainm** [comment]
Cool.

In case you don't know, we have temporary website too: http://amber-md.github.io/pytraj/doc/build/html/index.html

If you have any thing in mind (bug, new feature, things you don't like in pytraj, ...), don't hesitate to let us know.

Hai

**Comment by jmborr** [comment]
I'll start using pytraj today. I'll surely let you know if I find some
needed feature that is missing.
-Jose
