### ISSUE TITLE
ImportError after cpptraj update #147

### ISSUE THREAD

**Issue by ctlee** [Amber-MD/pytraj#981]
In reference to Amber-MD/cpptraj#147, I'm getting the following error running the simple tests. Any ideas?

```
ImportError: /net/home/clee/anaconda/lib/python2.7/site-packages/pytraj/core/action_list.so: undefined symbol: _ZN10ActionList9AddActionEPFP14DispatchObjectvER7ArgListR10ActionInit
```

**Comment by hainm** [comment]
:D since pytraj require cpptraj at both compiling time and running time, so if you update `libcpptraj.so`, you need ot rebbuild pytraj from fresh.

I would do
`rm -rf /net/home/clee/anaconda/lib/python2.7/site-packages/pytraj`

`rm -rf build`

then
`python ./setup.py install`

let me know if this work for you. thanks.

**Comment by ctlee** [comment]
Got it to work! Took a while, had to do some cleanup of my previous libcpptraj installs via conda and pip. Thanks for the help!

**Comment by hainm** [comment]
> Took a while

Can you let me know which part of reinstalling pytraj made you spend much time? I will try to update troubleshooting for installation so future users (especially inexperienced ones) can quickly debug. thanks.

**Comment by ctlee** [comment]
I had previously installed pytraj via `conda install -c ambermd pytraj libcpptraj` then later on, installed the development versions of each. This lead to me linking to a different `libcpptraj.so` than I thought I was. In my case, I removed all the conflicting versions to just have one!

The thing to consider, is for many users, if they have Amber installed and pytraj bundled with AmberTools, then they perform a `conda install`. I think this would lead to two versions of pytraj, libcpptraj. It may be difficult for a novice user to figure out what's pointing to what.

**Comment by hainm** [comment]
@ctlee 
thanks for experience. This is exactly I am concerning too. 

For compiling time, we can direct distutils to link pytraj to correct libcpptraj.so by export CPPTRAJHOME. But for running time, this is controled by system path and LD_PATH_LIBRARY. So for current solution, I just updated a bit to troubleshooting here: http://amber-md.github.io/pytraj/doc/build/html/installation.html#undefined-symbol-error

I reopen this issue to remind me about this.

**Comment by hainm** [comment]
From now pytraj use `rpath` in both linux and osx, no need for LD_PATH_LIBRARY. Happy closing.

**Comment by hainm** [comment]
From now pytraj use `rpath` in both linux and osx, no need for LD_PATH_LIBRARY. Happy closing.
