### ISSUE TITLE
Error "ValueError: Buffer not C contiguous" when saving trajectory selection

### ISSUE THREAD

**Issue by jmborr** [Amber-MD/pytraj#991]
Perhaps a Github issue is not the right venue for this error, but I am unaware of some email-list for pytraj questions. The script:
<pre>
#Load the first 9 frames with an atom selection
traj = pytraj.load('equil_cropped.dcd', 'pdb', mask='(!:1-256)&(@H1,@H2,@H3,@H4,@H5)', frame_indices=range(9))
# Trajectory of the center of mass of the first two residues
minitraj =  numpy.empty((2,traj.n_frames,3))
minitraj[0] = pytraj.center_of_mass(traj,mask=':1')
minitraj[1] = pytraj.center_of_mass(traj,mask=':2')
minitraj = minitraj.transpose((1,0,2))
# "topology" using the first two atoms
minitop = traj.top['@1,2']
# Save trajectory
pytraj.write_traj(filename='/tmp/junk.crd', traj=minitraj, top=minitop, overwrite=True)
</pre>
Error:
<pre>
Traceback (most recent call last):
  File "./junk.py", line 16, in <module>
    pytraj.write_traj(filename='/tmp/junk.crd', traj=minitraj, top=minitop, overwrite=True)
  File "/usr/lib64/python2.7/site-packages/pytraj/io.py", line 370, in write_traj
    for idx, frame in enumerate(fi):
  File "pytraj/cyutils.pyx", line 76, in _fast_iterptr (pytraj/cyutils.cpp:5078)
  File "pytraj/Frame.pyx", line 118, in pytraj.Frame.Frame.__cinit__ (pytraj/Frame.cpp:4279)
ValueError: Buffer not C contiguous.
</pre>
Some info:
<pre>
(Pdb) traj
pytraj.Trajectory, 9 frames: 
Size: 0.0000 (GB)
(Topology: 640 atoms, 128 residues, 640 mols, PBC with box type = ortho)
(Pdb) minitraj.shape
(9, 2, 3)
(Pdb) minitop
(Topology: 2 atoms, 1 residues, 2 mols, PBC with box type = ortho)
</pre>

**Comment by hainm** [comment]
> Perhaps a Github issue is not the right venue for this error, but I am unaware of some email-list for pytraj questions. 

I am fine with any question in github issue (it's easy to open and close). And actually I prefer to answer questions here due to code's highlight.

> ValueError: Buffer not C contiguous.

For very fast trajectory iterating, pytraj require coords must be stored in a C contiguous memory.

Can you try

`minitraj = np.ascontiguousarray(minitraj.transpose((1,0,2)))`

cython code here: https://github.com/Amber-MD/pytraj/blob/master/pytraj/cyutils.pyx#L69-L81

**Comment by jmborr** [comment]
Thanks, it did work :)
Would you consider inserting a validator in <pre>_fast_iterptr</pre> with an error message containing the solution? I'm not familiar with cython and the message "Buffer not C contiguous" didn't help me solve the problem.

**Comment by hainm** [comment]
do you have any error message in mind? `raise ValueError(...)`. I can add it to different places outside `_fast_iterptr`.

BTW, I just added autoconvert  to `write_traj`

https://github.com/Amber-MD/pytraj/commit/47598649440b1286cb8774cd55d7d51876334a2e

**Comment by jmborr** [comment]
Well, if you just autoconvert to contiguosarray, then the validator message
is not needed. I think this is even better because it's transparent to the
user.

**Comment by hainm** [comment]
The reason I did not make the autoconvert before because I have never met your problem. :D

**Comment by jmborr** [comment]
You wrote an extra 's' in 'ascontiguoussarray'
<pre>  File "/usr/lib64/python2.7/site-packages/pytraj/io.py", line 365, in write_traj
    xyz = np.ascontiguoussarray(xyz)
AttributeError: 'module' object has no attribute 'ascontiguoussarray'</pre>

**Comment by hainm** [comment]
Oops. This is a poor habit of not writting a test for new code. 

Can you send me few snapshots from your traj with topology so I can reproduce your error and write a test. I tried with my own file but can not reproduce with your code. (Numpy version different?)

I will fix the typos. Thanks

**Comment by jmborr** [comment]
Get the files from:
https://www.dropbox.com/s/43f2nzl4bdxtgw9/ascontiguousarray.tar.gz?dl=0

After fixing the typo I can run my script without having to ensure
that minitraj is a contiguous array.

I have numpy 1.9.2

-Jose

**Comment by hainm** [comment]
@jmborr 

can you resend your pdb file?

```bash
pdb -> ../8styrene32.pdb
```

**Comment by jmborr** [comment]
Oops 😅
See attached

**Comment by hainm** [comment]
@jmborr the old attached in dropbox? there is still 0 byte for pdb.

**Comment by jmborr** [comment]
Please ignore the pdb file in the tar file. I just sent you an email with
the pbd file as an attachment.

**Comment by hainm** [comment]
@jmborr which email: mine is hainm.comp at gmail.com

**Comment by hainm** [comment]
@jmborr I am done. Let me know if there are other issues. thanks

code: https://github.com/Amber-MD/pytraj/blob/master/tests/issues/test_issue991_buffer_not_C_contiguous.py
pass travis test: https://travis-ci.org/Amber-MD/pytraj/jobs/89069925#L2279

**Comment by jmborr** [comment]
Thank you!
